package pe.com.pdp.domain.postgres;

import java.io.Serializable;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.web.multipart.MultipartFile;

import pe.com.pdp.domain.model.GridModel;

public class Anuncio extends GridModel implements Serializable{

	private static final long serialVersionUID = 1L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_anuncio.id
     *
     * @mbg.generated Sun May 07 17:02:54 COT 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_anuncio.tipo_anuncio
     *
     * @mbg.generated Sun May 07 17:02:54 COT 2017
     */
    private Integer tipoAnuncio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_anuncio.descripcion
     *
     * @mbg.generated Sun May 07 17:02:54 COT 2017
     */
    @DateTimeFormat(pattern="dd/MM/yyyy")
    private String descripcion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_anuncio.fecha_anuncio
     *
     * @mbg.generated Sun May 07 17:02:54 COT 2017
     */
    @DateTimeFormat(pattern="dd/MM/yyyy")
    private Date fechaAnuncio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_anuncio.fecha_vencimiento
     *
     * @mbg.generated Sun May 07 17:02:54 COT 2017
     */
    @DateTimeFormat(pattern="dd/MM/yyyy")
    private Date fechaVencimiento;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_anuncio.foto
     *
     * @mbg.generated Sun May 07 17:02:54 COT 2017
     */
    private String foto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_anuncio.titulo
     *
     * @mbg.generated Sun May 07 17:02:54 COT 2017
     */
    private String titulo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_anuncio.estaoo
     *
     * @mbg.generated Sun May 07 17:02:54 COT 2017
     */
    private Integer estaoo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_anuncio.usuario_registro
     *
     * @mbg.generated Sun May 07 17:02:54 COT 2017
     */
    private String usuarioRegistro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_anuncio.fecha_registro
     *
     * @mbg.generated Sun May 07 17:02:54 COT 2017
     */
    private Date fechaRegistro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_anuncio.usuario_modifico
     *
     * @mbg.generated Sun May 07 17:02:54 COT 2017
     */
    private String usuarioModifico;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_anuncio.fecha_modifico
     *
     * @mbg.generated Sun May 07 17:02:54 COT 2017
     */
    private Date fechaModifico;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_anuncio.distrito
     *
     * @mbg.generated Sun May 07 17:02:54 COT 2017
     */
    private Integer distrito;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_anuncio.id
     *
     * @return the value of pataPerro.tm_anuncio.id
     *
     * @mbg.generated Sun May 07 17:02:54 COT 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_anuncio.id
     *
     * @param id the value for pataPerro.tm_anuncio.id
     *
     * @mbg.generated Sun May 07 17:02:54 COT 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_anuncio.tipo_anuncio
     *
     * @return the value of pataPerro.tm_anuncio.tipo_anuncio
     *
     * @mbg.generated Sun May 07 17:02:54 COT 2017
     */
    public Integer getTipoAnuncio() {
        return tipoAnuncio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_anuncio.tipo_anuncio
     *
     * @param tipoAnuncio the value for pataPerro.tm_anuncio.tipo_anuncio
     *
     * @mbg.generated Sun May 07 17:02:54 COT 2017
     */
    public void setTipoAnuncio(Integer tipoAnuncio) {
        this.tipoAnuncio = tipoAnuncio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_anuncio.descripcion
     *
     * @return the value of pataPerro.tm_anuncio.descripcion
     *
     * @mbg.generated Sun May 07 17:02:54 COT 2017
     */
    public String getDescripcion() {
        return descripcion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_anuncio.descripcion
     *
     * @param descripcion the value for pataPerro.tm_anuncio.descripcion
     *
     * @mbg.generated Sun May 07 17:02:54 COT 2017
     */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_anuncio.fecha_anuncio
     *
     * @return the value of pataPerro.tm_anuncio.fecha_anuncio
     *
     * @mbg.generated Sun May 07 17:02:54 COT 2017
     */
    public Date getFechaAnuncio() {
        return fechaAnuncio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_anuncio.fecha_anuncio
     *
     * @param fechaAnuncio the value for pataPerro.tm_anuncio.fecha_anuncio
     *
     * @mbg.generated Sun May 07 17:02:54 COT 2017
     */
    public void setFechaAnuncio(Date fechaAnuncio) {
        this.fechaAnuncio = fechaAnuncio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_anuncio.fecha_vencimiento
     *
     * @return the value of pataPerro.tm_anuncio.fecha_vencimiento
     *
     * @mbg.generated Sun May 07 17:02:54 COT 2017
     */
    public Date getFechaVencimiento() {
        return fechaVencimiento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_anuncio.fecha_vencimiento
     *
     * @param fechaVencimiento the value for pataPerro.tm_anuncio.fecha_vencimiento
     *
     * @mbg.generated Sun May 07 17:02:54 COT 2017
     */
    public void setFechaVencimiento(Date fechaVencimiento) {
        this.fechaVencimiento = fechaVencimiento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_anuncio.foto
     *
     * @return the value of pataPerro.tm_anuncio.foto
     *
     * @mbg.generated Sun May 07 17:02:54 COT 2017
     */
    public String getFoto() {
        return foto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_anuncio.foto
     *
     * @param foto the value for pataPerro.tm_anuncio.foto
     *
     * @mbg.generated Sun May 07 17:02:54 COT 2017
     */
    public void setFoto(String foto) {
        this.foto = foto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_anuncio.titulo
     *
     * @return the value of pataPerro.tm_anuncio.titulo
     *
     * @mbg.generated Sun May 07 17:02:54 COT 2017
     */
    public String getTitulo() {
        return titulo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_anuncio.titulo
     *
     * @param titulo the value for pataPerro.tm_anuncio.titulo
     *
     * @mbg.generated Sun May 07 17:02:54 COT 2017
     */
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_anuncio.estaoo
     *
     * @return the value of pataPerro.tm_anuncio.estaoo
     *
     * @mbg.generated Sun May 07 17:02:54 COT 2017
     */
    public Integer getEstaoo() {
        return estaoo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_anuncio.estaoo
     *
     * @param estaoo the value for pataPerro.tm_anuncio.estaoo
     *
     * @mbg.generated Sun May 07 17:02:54 COT 2017
     */
    public void setEstaoo(Integer estaoo) {
        this.estaoo = estaoo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_anuncio.usuario_registro
     *
     * @return the value of pataPerro.tm_anuncio.usuario_registro
     *
     * @mbg.generated Sun May 07 17:02:54 COT 2017
     */
    public String getUsuarioRegistro() {
        return usuarioRegistro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_anuncio.usuario_registro
     *
     * @param usuarioRegistro the value for pataPerro.tm_anuncio.usuario_registro
     *
     * @mbg.generated Sun May 07 17:02:54 COT 2017
     */
    public void setUsuarioRegistro(String usuarioRegistro) {
        this.usuarioRegistro = usuarioRegistro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_anuncio.fecha_registro
     *
     * @return the value of pataPerro.tm_anuncio.fecha_registro
     *
     * @mbg.generated Sun May 07 17:02:54 COT 2017
     */
    public Date getFechaRegistro() {
        return fechaRegistro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_anuncio.fecha_registro
     *
     * @param fechaRegistro the value for pataPerro.tm_anuncio.fecha_registro
     *
     * @mbg.generated Sun May 07 17:02:54 COT 2017
     */
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_anuncio.usuario_modifico
     *
     * @return the value of pataPerro.tm_anuncio.usuario_modifico
     *
     * @mbg.generated Sun May 07 17:02:54 COT 2017
     */
    public String getUsuarioModifico() {
        return usuarioModifico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_anuncio.usuario_modifico
     *
     * @param usuarioModifico the value for pataPerro.tm_anuncio.usuario_modifico
     *
     * @mbg.generated Sun May 07 17:02:54 COT 2017
     */
    public void setUsuarioModifico(String usuarioModifico) {
        this.usuarioModifico = usuarioModifico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_anuncio.fecha_modifico
     *
     * @return the value of pataPerro.tm_anuncio.fecha_modifico
     *
     * @mbg.generated Sun May 07 17:02:54 COT 2017
     */
    public Date getFechaModifico() {
        return fechaModifico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_anuncio.fecha_modifico
     *
     * @param fechaModifico the value for pataPerro.tm_anuncio.fecha_modifico
     *
     * @mbg.generated Sun May 07 17:02:54 COT 2017
     */
    public void setFechaModifico(Date fechaModifico) {
        this.fechaModifico = fechaModifico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_anuncio.distrito
     *
     * @return the value of pataPerro.tm_anuncio.distrito
     *
     * @mbg.generated Sun May 07 17:02:54 COT 2017
     */
    public Integer getDistrito() {
        return distrito;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_anuncio.distrito
     *
     * @param distrito the value for pataPerro.tm_anuncio.distrito
     *
     * @mbg.generated Sun May 07 17:02:54 COT 2017
     */
    public void setDistrito(Integer distrito) {
        this.distrito = distrito;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_anuncio
     *
     * @mbg.generated Sun May 07 17:02:54 COT 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Anuncio other = (Anuncio) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getTipoAnuncio() == null ? other.getTipoAnuncio() == null : this.getTipoAnuncio().equals(other.getTipoAnuncio()))
            && (this.getDescripcion() == null ? other.getDescripcion() == null : this.getDescripcion().equals(other.getDescripcion()))
            && (this.getFechaAnuncio() == null ? other.getFechaAnuncio() == null : this.getFechaAnuncio().equals(other.getFechaAnuncio()))
            && (this.getFechaVencimiento() == null ? other.getFechaVencimiento() == null : this.getFechaVencimiento().equals(other.getFechaVencimiento()))
            && (this.getFoto() == null ? other.getFoto() == null : this.getFoto().equals(other.getFoto()))
            && (this.getTitulo() == null ? other.getTitulo() == null : this.getTitulo().equals(other.getTitulo()))
            && (this.getEstaoo() == null ? other.getEstaoo() == null : this.getEstaoo().equals(other.getEstaoo()))
            && (this.getUsuarioRegistro() == null ? other.getUsuarioRegistro() == null : this.getUsuarioRegistro().equals(other.getUsuarioRegistro()))
            && (this.getFechaRegistro() == null ? other.getFechaRegistro() == null : this.getFechaRegistro().equals(other.getFechaRegistro()))
            && (this.getUsuarioModifico() == null ? other.getUsuarioModifico() == null : this.getUsuarioModifico().equals(other.getUsuarioModifico()))
            && (this.getFechaModifico() == null ? other.getFechaModifico() == null : this.getFechaModifico().equals(other.getFechaModifico()))
            && (this.getDistrito() == null ? other.getDistrito() == null : this.getDistrito().equals(other.getDistrito()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_anuncio
     *
     * @mbg.generated Sun May 07 17:02:54 COT 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getTipoAnuncio() == null) ? 0 : getTipoAnuncio().hashCode());
        result = prime * result + ((getDescripcion() == null) ? 0 : getDescripcion().hashCode());
        result = prime * result + ((getFechaAnuncio() == null) ? 0 : getFechaAnuncio().hashCode());
        result = prime * result + ((getFechaVencimiento() == null) ? 0 : getFechaVencimiento().hashCode());
        result = prime * result + ((getFoto() == null) ? 0 : getFoto().hashCode());
        result = prime * result + ((getTitulo() == null) ? 0 : getTitulo().hashCode());
        result = prime * result + ((getEstaoo() == null) ? 0 : getEstaoo().hashCode());
        result = prime * result + ((getUsuarioRegistro() == null) ? 0 : getUsuarioRegistro().hashCode());
        result = prime * result + ((getFechaRegistro() == null) ? 0 : getFechaRegistro().hashCode());
        result = prime * result + ((getUsuarioModifico() == null) ? 0 : getUsuarioModifico().hashCode());
        result = prime * result + ((getFechaModifico() == null) ? 0 : getFechaModifico().hashCode());
        result = prime * result + ((getDistrito() == null) ? 0 : getDistrito().hashCode());
        return result;
    }
    
    /** Atributos adicionales **/
    private MultipartFile fileFoto;

	public MultipartFile getFileFoto() {
		return fileFoto;
	}

	public void setFileFoto(MultipartFile fileFoto) {
		this.fileFoto = fileFoto;
	}
	private Ubigeo ubigeo;

	public Ubigeo getUbigeo() {
		return ubigeo;
	}

	public void setUbigeo(Ubigeo ubigeo) {
		this.ubigeo = ubigeo;
	}
	
	
}