package pe.com.pdp.domain.postgres;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BusquedaCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pataPerro.tm_busqueda
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pataPerro.tm_busqueda
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pataPerro.tm_busqueda
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_busqueda
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public BusquedaCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_busqueda
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_busqueda
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_busqueda
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_busqueda
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_busqueda
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_busqueda
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_busqueda
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_busqueda
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_busqueda
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_busqueda
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pataPerro.tm_busqueda
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("\"id\" is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("\"id\" is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("\"id\" =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("\"id\" <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("\"id\" >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("\"id\" >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("\"id\" <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("\"id\" <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("\"id\" in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("\"id\" not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("\"id\" between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("\"id\" not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andMascotaIdIsNull() {
            addCriterion("\"mascota_id\" is null");
            return (Criteria) this;
        }

        public Criteria andMascotaIdIsNotNull() {
            addCriterion("\"mascota_id\" is not null");
            return (Criteria) this;
        }

        public Criteria andMascotaIdEqualTo(Integer value) {
            addCriterion("\"mascota_id\" =", value, "mascotaId");
            return (Criteria) this;
        }

        public Criteria andMascotaIdNotEqualTo(Integer value) {
            addCriterion("\"mascota_id\" <>", value, "mascotaId");
            return (Criteria) this;
        }

        public Criteria andMascotaIdGreaterThan(Integer value) {
            addCriterion("\"mascota_id\" >", value, "mascotaId");
            return (Criteria) this;
        }

        public Criteria andMascotaIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("\"mascota_id\" >=", value, "mascotaId");
            return (Criteria) this;
        }

        public Criteria andMascotaIdLessThan(Integer value) {
            addCriterion("\"mascota_id\" <", value, "mascotaId");
            return (Criteria) this;
        }

        public Criteria andMascotaIdLessThanOrEqualTo(Integer value) {
            addCriterion("\"mascota_id\" <=", value, "mascotaId");
            return (Criteria) this;
        }

        public Criteria andMascotaIdIn(List<Integer> values) {
            addCriterion("\"mascota_id\" in", values, "mascotaId");
            return (Criteria) this;
        }

        public Criteria andMascotaIdNotIn(List<Integer> values) {
            addCriterion("\"mascota_id\" not in", values, "mascotaId");
            return (Criteria) this;
        }

        public Criteria andMascotaIdBetween(Integer value1, Integer value2) {
            addCriterion("\"mascota_id\" between", value1, value2, "mascotaId");
            return (Criteria) this;
        }

        public Criteria andMascotaIdNotBetween(Integer value1, Integer value2) {
            addCriterion("\"mascota_id\" not between", value1, value2, "mascotaId");
            return (Criteria) this;
        }

        public Criteria andFechaPerdidaIsNull() {
            addCriterion("\"fecha_perdida\" is null");
            return (Criteria) this;
        }

        public Criteria andFechaPerdidaIsNotNull() {
            addCriterion("\"fecha_perdida\" is not null");
            return (Criteria) this;
        }

        public Criteria andFechaPerdidaEqualTo(Date value) {
            addCriterion("\"fecha_perdida\" =", value, "fechaPerdida");
            return (Criteria) this;
        }

        public Criteria andFechaPerdidaNotEqualTo(Date value) {
            addCriterion("\"fecha_perdida\" <>", value, "fechaPerdida");
            return (Criteria) this;
        }

        public Criteria andFechaPerdidaGreaterThan(Date value) {
            addCriterion("\"fecha_perdida\" >", value, "fechaPerdida");
            return (Criteria) this;
        }

        public Criteria andFechaPerdidaGreaterThanOrEqualTo(Date value) {
            addCriterion("\"fecha_perdida\" >=", value, "fechaPerdida");
            return (Criteria) this;
        }

        public Criteria andFechaPerdidaLessThan(Date value) {
            addCriterion("\"fecha_perdida\" <", value, "fechaPerdida");
            return (Criteria) this;
        }

        public Criteria andFechaPerdidaLessThanOrEqualTo(Date value) {
            addCriterion("\"fecha_perdida\" <=", value, "fechaPerdida");
            return (Criteria) this;
        }

        public Criteria andFechaPerdidaIn(List<Date> values) {
            addCriterion("\"fecha_perdida\" in", values, "fechaPerdida");
            return (Criteria) this;
        }

        public Criteria andFechaPerdidaNotIn(List<Date> values) {
            addCriterion("\"fecha_perdida\" not in", values, "fechaPerdida");
            return (Criteria) this;
        }

        public Criteria andFechaPerdidaBetween(Date value1, Date value2) {
            addCriterion("\"fecha_perdida\" between", value1, value2, "fechaPerdida");
            return (Criteria) this;
        }

        public Criteria andFechaPerdidaNotBetween(Date value1, Date value2) {
            addCriterion("\"fecha_perdida\" not between", value1, value2, "fechaPerdida");
            return (Criteria) this;
        }

        public Criteria andUbicacionCatastroIsNull() {
            addCriterion("\"ubicacion_catastro\" is null");
            return (Criteria) this;
        }

        public Criteria andUbicacionCatastroIsNotNull() {
            addCriterion("\"ubicacion_catastro\" is not null");
            return (Criteria) this;
        }

        public Criteria andUbicacionCatastroEqualTo(String value) {
            addCriterion("\"ubicacion_catastro\" =", value, "ubicacionCatastro");
            return (Criteria) this;
        }

        public Criteria andUbicacionCatastroNotEqualTo(String value) {
            addCriterion("\"ubicacion_catastro\" <>", value, "ubicacionCatastro");
            return (Criteria) this;
        }

        public Criteria andUbicacionCatastroGreaterThan(String value) {
            addCriterion("\"ubicacion_catastro\" >", value, "ubicacionCatastro");
            return (Criteria) this;
        }

        public Criteria andUbicacionCatastroGreaterThanOrEqualTo(String value) {
            addCriterion("\"ubicacion_catastro\" >=", value, "ubicacionCatastro");
            return (Criteria) this;
        }

        public Criteria andUbicacionCatastroLessThan(String value) {
            addCriterion("\"ubicacion_catastro\" <", value, "ubicacionCatastro");
            return (Criteria) this;
        }

        public Criteria andUbicacionCatastroLessThanOrEqualTo(String value) {
            addCriterion("\"ubicacion_catastro\" <=", value, "ubicacionCatastro");
            return (Criteria) this;
        }

        public Criteria andUbicacionCatastroLike(String value) {
            addCriterion("\"ubicacion_catastro\" like", value, "ubicacionCatastro");
            return (Criteria) this;
        }

        public Criteria andUbicacionCatastroNotLike(String value) {
            addCriterion("\"ubicacion_catastro\" not like", value, "ubicacionCatastro");
            return (Criteria) this;
        }

        public Criteria andUbicacionCatastroIn(List<String> values) {
            addCriterion("\"ubicacion_catastro\" in", values, "ubicacionCatastro");
            return (Criteria) this;
        }

        public Criteria andUbicacionCatastroNotIn(List<String> values) {
            addCriterion("\"ubicacion_catastro\" not in", values, "ubicacionCatastro");
            return (Criteria) this;
        }

        public Criteria andUbicacionCatastroBetween(String value1, String value2) {
            addCriterion("\"ubicacion_catastro\" between", value1, value2, "ubicacionCatastro");
            return (Criteria) this;
        }

        public Criteria andUbicacionCatastroNotBetween(String value1, String value2) {
            addCriterion("\"ubicacion_catastro\" not between", value1, value2, "ubicacionCatastro");
            return (Criteria) this;
        }

        public Criteria andDescripcionIsNull() {
            addCriterion("\"descripcion\" is null");
            return (Criteria) this;
        }

        public Criteria andDescripcionIsNotNull() {
            addCriterion("\"descripcion\" is not null");
            return (Criteria) this;
        }

        public Criteria andDescripcionEqualTo(String value) {
            addCriterion("\"descripcion\" =", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionNotEqualTo(String value) {
            addCriterion("\"descripcion\" <>", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionGreaterThan(String value) {
            addCriterion("\"descripcion\" >", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionGreaterThanOrEqualTo(String value) {
            addCriterion("\"descripcion\" >=", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionLessThan(String value) {
            addCriterion("\"descripcion\" <", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionLessThanOrEqualTo(String value) {
            addCriterion("\"descripcion\" <=", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionLike(String value) {
            addCriterion("\"descripcion\" like", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionNotLike(String value) {
            addCriterion("\"descripcion\" not like", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionIn(List<String> values) {
            addCriterion("\"descripcion\" in", values, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionNotIn(List<String> values) {
            addCriterion("\"descripcion\" not in", values, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionBetween(String value1, String value2) {
            addCriterion("\"descripcion\" between", value1, value2, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionNotBetween(String value1, String value2) {
            addCriterion("\"descripcion\" not between", value1, value2, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDistritoIsNull() {
            addCriterion("\"distrito\" is null");
            return (Criteria) this;
        }

        public Criteria andDistritoIsNotNull() {
            addCriterion("\"distrito\" is not null");
            return (Criteria) this;
        }

        public Criteria andDistritoEqualTo(Integer value) {
            addCriterion("\"distrito\" =", value, "distrito");
            return (Criteria) this;
        }

        public Criteria andDistritoNotEqualTo(Integer value) {
            addCriterion("\"distrito\" <>", value, "distrito");
            return (Criteria) this;
        }

        public Criteria andDistritoGreaterThan(Integer value) {
            addCriterion("\"distrito\" >", value, "distrito");
            return (Criteria) this;
        }

        public Criteria andDistritoGreaterThanOrEqualTo(Integer value) {
            addCriterion("\"distrito\" >=", value, "distrito");
            return (Criteria) this;
        }

        public Criteria andDistritoLessThan(Integer value) {
            addCriterion("\"distrito\" <", value, "distrito");
            return (Criteria) this;
        }

        public Criteria andDistritoLessThanOrEqualTo(Integer value) {
            addCriterion("\"distrito\" <=", value, "distrito");
            return (Criteria) this;
        }

        public Criteria andDistritoIn(List<Integer> values) {
            addCriterion("\"distrito\" in", values, "distrito");
            return (Criteria) this;
        }

        public Criteria andDistritoNotIn(List<Integer> values) {
            addCriterion("\"distrito\" not in", values, "distrito");
            return (Criteria) this;
        }

        public Criteria andDistritoBetween(Integer value1, Integer value2) {
            addCriterion("\"distrito\" between", value1, value2, "distrito");
            return (Criteria) this;
        }

        public Criteria andDistritoNotBetween(Integer value1, Integer value2) {
            addCriterion("\"distrito\" not between", value1, value2, "distrito");
            return (Criteria) this;
        }

        public Criteria andEstadoBusquedaIsNull() {
            addCriterion("\"estado_busqueda\" is null");
            return (Criteria) this;
        }

        public Criteria andEstadoBusquedaIsNotNull() {
            addCriterion("\"estado_busqueda\" is not null");
            return (Criteria) this;
        }

        public Criteria andEstadoBusquedaEqualTo(Integer value) {
            addCriterion("\"estado_busqueda\" =", value, "estadoBusqueda");
            return (Criteria) this;
        }

        public Criteria andEstadoBusquedaNotEqualTo(Integer value) {
            addCriterion("\"estado_busqueda\" <>", value, "estadoBusqueda");
            return (Criteria) this;
        }

        public Criteria andEstadoBusquedaGreaterThan(Integer value) {
            addCriterion("\"estado_busqueda\" >", value, "estadoBusqueda");
            return (Criteria) this;
        }

        public Criteria andEstadoBusquedaGreaterThanOrEqualTo(Integer value) {
            addCriterion("\"estado_busqueda\" >=", value, "estadoBusqueda");
            return (Criteria) this;
        }

        public Criteria andEstadoBusquedaLessThan(Integer value) {
            addCriterion("\"estado_busqueda\" <", value, "estadoBusqueda");
            return (Criteria) this;
        }

        public Criteria andEstadoBusquedaLessThanOrEqualTo(Integer value) {
            addCriterion("\"estado_busqueda\" <=", value, "estadoBusqueda");
            return (Criteria) this;
        }

        public Criteria andEstadoBusquedaIn(List<Integer> values) {
            addCriterion("\"estado_busqueda\" in", values, "estadoBusqueda");
            return (Criteria) this;
        }

        public Criteria andEstadoBusquedaNotIn(List<Integer> values) {
            addCriterion("\"estado_busqueda\" not in", values, "estadoBusqueda");
            return (Criteria) this;
        }

        public Criteria andEstadoBusquedaBetween(Integer value1, Integer value2) {
            addCriterion("\"estado_busqueda\" between", value1, value2, "estadoBusqueda");
            return (Criteria) this;
        }

        public Criteria andEstadoBusquedaNotBetween(Integer value1, Integer value2) {
            addCriterion("\"estado_busqueda\" not between", value1, value2, "estadoBusqueda");
            return (Criteria) this;
        }

        public Criteria andEstadoIsNull() {
            addCriterion("\"estado\" is null");
            return (Criteria) this;
        }

        public Criteria andEstadoIsNotNull() {
            addCriterion("\"estado\" is not null");
            return (Criteria) this;
        }

        public Criteria andEstadoEqualTo(Integer value) {
            addCriterion("\"estado\" =", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoNotEqualTo(Integer value) {
            addCriterion("\"estado\" <>", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoGreaterThan(Integer value) {
            addCriterion("\"estado\" >", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoGreaterThanOrEqualTo(Integer value) {
            addCriterion("\"estado\" >=", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoLessThan(Integer value) {
            addCriterion("\"estado\" <", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoLessThanOrEqualTo(Integer value) {
            addCriterion("\"estado\" <=", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoIn(List<Integer> values) {
            addCriterion("\"estado\" in", values, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoNotIn(List<Integer> values) {
            addCriterion("\"estado\" not in", values, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoBetween(Integer value1, Integer value2) {
            addCriterion("\"estado\" between", value1, value2, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoNotBetween(Integer value1, Integer value2) {
            addCriterion("\"estado\" not between", value1, value2, "estado");
            return (Criteria) this;
        }

        public Criteria andIndRecompensaIsNull() {
            addCriterion("\"ind_recompensa\" is null");
            return (Criteria) this;
        }

        public Criteria andIndRecompensaIsNotNull() {
            addCriterion("\"ind_recompensa\" is not null");
            return (Criteria) this;
        }

        public Criteria andIndRecompensaEqualTo(Integer value) {
            addCriterion("\"ind_recompensa\" =", value, "indRecompensa");
            return (Criteria) this;
        }

        public Criteria andIndRecompensaNotEqualTo(Integer value) {
            addCriterion("\"ind_recompensa\" <>", value, "indRecompensa");
            return (Criteria) this;
        }

        public Criteria andIndRecompensaGreaterThan(Integer value) {
            addCriterion("\"ind_recompensa\" >", value, "indRecompensa");
            return (Criteria) this;
        }

        public Criteria andIndRecompensaGreaterThanOrEqualTo(Integer value) {
            addCriterion("\"ind_recompensa\" >=", value, "indRecompensa");
            return (Criteria) this;
        }

        public Criteria andIndRecompensaLessThan(Integer value) {
            addCriterion("\"ind_recompensa\" <", value, "indRecompensa");
            return (Criteria) this;
        }

        public Criteria andIndRecompensaLessThanOrEqualTo(Integer value) {
            addCriterion("\"ind_recompensa\" <=", value, "indRecompensa");
            return (Criteria) this;
        }

        public Criteria andIndRecompensaIn(List<Integer> values) {
            addCriterion("\"ind_recompensa\" in", values, "indRecompensa");
            return (Criteria) this;
        }

        public Criteria andIndRecompensaNotIn(List<Integer> values) {
            addCriterion("\"ind_recompensa\" not in", values, "indRecompensa");
            return (Criteria) this;
        }

        public Criteria andIndRecompensaBetween(Integer value1, Integer value2) {
            addCriterion("\"ind_recompensa\" between", value1, value2, "indRecompensa");
            return (Criteria) this;
        }

        public Criteria andIndRecompensaNotBetween(Integer value1, Integer value2) {
            addCriterion("\"ind_recompensa\" not between", value1, value2, "indRecompensa");
            return (Criteria) this;
        }

        public Criteria andComentarioAdicionalIsNull() {
            addCriterion("\"comentario_adicional\" is null");
            return (Criteria) this;
        }

        public Criteria andComentarioAdicionalIsNotNull() {
            addCriterion("\"comentario_adicional\" is not null");
            return (Criteria) this;
        }

        public Criteria andComentarioAdicionalEqualTo(String value) {
            addCriterion("\"comentario_adicional\" =", value, "comentarioAdicional");
            return (Criteria) this;
        }

        public Criteria andComentarioAdicionalNotEqualTo(String value) {
            addCriterion("\"comentario_adicional\" <>", value, "comentarioAdicional");
            return (Criteria) this;
        }

        public Criteria andComentarioAdicionalGreaterThan(String value) {
            addCriterion("\"comentario_adicional\" >", value, "comentarioAdicional");
            return (Criteria) this;
        }

        public Criteria andComentarioAdicionalGreaterThanOrEqualTo(String value) {
            addCriterion("\"comentario_adicional\" >=", value, "comentarioAdicional");
            return (Criteria) this;
        }

        public Criteria andComentarioAdicionalLessThan(String value) {
            addCriterion("\"comentario_adicional\" <", value, "comentarioAdicional");
            return (Criteria) this;
        }

        public Criteria andComentarioAdicionalLessThanOrEqualTo(String value) {
            addCriterion("\"comentario_adicional\" <=", value, "comentarioAdicional");
            return (Criteria) this;
        }

        public Criteria andComentarioAdicionalLike(String value) {
            addCriterion("\"comentario_adicional\" like", value, "comentarioAdicional");
            return (Criteria) this;
        }

        public Criteria andComentarioAdicionalNotLike(String value) {
            addCriterion("\"comentario_adicional\" not like", value, "comentarioAdicional");
            return (Criteria) this;
        }

        public Criteria andComentarioAdicionalIn(List<String> values) {
            addCriterion("\"comentario_adicional\" in", values, "comentarioAdicional");
            return (Criteria) this;
        }

        public Criteria andComentarioAdicionalNotIn(List<String> values) {
            addCriterion("\"comentario_adicional\" not in", values, "comentarioAdicional");
            return (Criteria) this;
        }

        public Criteria andComentarioAdicionalBetween(String value1, String value2) {
            addCriterion("\"comentario_adicional\" between", value1, value2, "comentarioAdicional");
            return (Criteria) this;
        }

        public Criteria andComentarioAdicionalNotBetween(String value1, String value2) {
            addCriterion("\"comentario_adicional\" not between", value1, value2, "comentarioAdicional");
            return (Criteria) this;
        }

        public Criteria andUsuarioRegistroIsNull() {
            addCriterion("\"usuario_registro\" is null");
            return (Criteria) this;
        }

        public Criteria andUsuarioRegistroIsNotNull() {
            addCriterion("\"usuario_registro\" is not null");
            return (Criteria) this;
        }

        public Criteria andUsuarioRegistroEqualTo(String value) {
            addCriterion("\"usuario_registro\" =", value, "usuarioRegistro");
            return (Criteria) this;
        }

        public Criteria andUsuarioRegistroNotEqualTo(String value) {
            addCriterion("\"usuario_registro\" <>", value, "usuarioRegistro");
            return (Criteria) this;
        }

        public Criteria andUsuarioRegistroGreaterThan(String value) {
            addCriterion("\"usuario_registro\" >", value, "usuarioRegistro");
            return (Criteria) this;
        }

        public Criteria andUsuarioRegistroGreaterThanOrEqualTo(String value) {
            addCriterion("\"usuario_registro\" >=", value, "usuarioRegistro");
            return (Criteria) this;
        }

        public Criteria andUsuarioRegistroLessThan(String value) {
            addCriterion("\"usuario_registro\" <", value, "usuarioRegistro");
            return (Criteria) this;
        }

        public Criteria andUsuarioRegistroLessThanOrEqualTo(String value) {
            addCriterion("\"usuario_registro\" <=", value, "usuarioRegistro");
            return (Criteria) this;
        }

        public Criteria andUsuarioRegistroLike(String value) {
            addCriterion("\"usuario_registro\" like", value, "usuarioRegistro");
            return (Criteria) this;
        }

        public Criteria andUsuarioRegistroNotLike(String value) {
            addCriterion("\"usuario_registro\" not like", value, "usuarioRegistro");
            return (Criteria) this;
        }

        public Criteria andUsuarioRegistroIn(List<String> values) {
            addCriterion("\"usuario_registro\" in", values, "usuarioRegistro");
            return (Criteria) this;
        }

        public Criteria andUsuarioRegistroNotIn(List<String> values) {
            addCriterion("\"usuario_registro\" not in", values, "usuarioRegistro");
            return (Criteria) this;
        }

        public Criteria andUsuarioRegistroBetween(String value1, String value2) {
            addCriterion("\"usuario_registro\" between", value1, value2, "usuarioRegistro");
            return (Criteria) this;
        }

        public Criteria andUsuarioRegistroNotBetween(String value1, String value2) {
            addCriterion("\"usuario_registro\" not between", value1, value2, "usuarioRegistro");
            return (Criteria) this;
        }

        public Criteria andFechaRegistroIsNull() {
            addCriterion("\"fecha_registro\" is null");
            return (Criteria) this;
        }

        public Criteria andFechaRegistroIsNotNull() {
            addCriterion("\"fecha_registro\" is not null");
            return (Criteria) this;
        }

        public Criteria andFechaRegistroEqualTo(Date value) {
            addCriterion("\"fecha_registro\" =", value, "fechaRegistro");
            return (Criteria) this;
        }

        public Criteria andFechaRegistroNotEqualTo(Date value) {
            addCriterion("\"fecha_registro\" <>", value, "fechaRegistro");
            return (Criteria) this;
        }

        public Criteria andFechaRegistroGreaterThan(Date value) {
            addCriterion("\"fecha_registro\" >", value, "fechaRegistro");
            return (Criteria) this;
        }

        public Criteria andFechaRegistroGreaterThanOrEqualTo(Date value) {
            addCriterion("\"fecha_registro\" >=", value, "fechaRegistro");
            return (Criteria) this;
        }

        public Criteria andFechaRegistroLessThan(Date value) {
            addCriterion("\"fecha_registro\" <", value, "fechaRegistro");
            return (Criteria) this;
        }

        public Criteria andFechaRegistroLessThanOrEqualTo(Date value) {
            addCriterion("\"fecha_registro\" <=", value, "fechaRegistro");
            return (Criteria) this;
        }

        public Criteria andFechaRegistroIn(List<Date> values) {
            addCriterion("\"fecha_registro\" in", values, "fechaRegistro");
            return (Criteria) this;
        }

        public Criteria andFechaRegistroNotIn(List<Date> values) {
            addCriterion("\"fecha_registro\" not in", values, "fechaRegistro");
            return (Criteria) this;
        }

        public Criteria andFechaRegistroBetween(Date value1, Date value2) {
            addCriterion("\"fecha_registro\" between", value1, value2, "fechaRegistro");
            return (Criteria) this;
        }

        public Criteria andFechaRegistroNotBetween(Date value1, Date value2) {
            addCriterion("\"fecha_registro\" not between", value1, value2, "fechaRegistro");
            return (Criteria) this;
        }

        public Criteria andUsuarioModificoIsNull() {
            addCriterion("\"usuario_modifico\" is null");
            return (Criteria) this;
        }

        public Criteria andUsuarioModificoIsNotNull() {
            addCriterion("\"usuario_modifico\" is not null");
            return (Criteria) this;
        }

        public Criteria andUsuarioModificoEqualTo(String value) {
            addCriterion("\"usuario_modifico\" =", value, "usuarioModifico");
            return (Criteria) this;
        }

        public Criteria andUsuarioModificoNotEqualTo(String value) {
            addCriterion("\"usuario_modifico\" <>", value, "usuarioModifico");
            return (Criteria) this;
        }

        public Criteria andUsuarioModificoGreaterThan(String value) {
            addCriterion("\"usuario_modifico\" >", value, "usuarioModifico");
            return (Criteria) this;
        }

        public Criteria andUsuarioModificoGreaterThanOrEqualTo(String value) {
            addCriterion("\"usuario_modifico\" >=", value, "usuarioModifico");
            return (Criteria) this;
        }

        public Criteria andUsuarioModificoLessThan(String value) {
            addCriterion("\"usuario_modifico\" <", value, "usuarioModifico");
            return (Criteria) this;
        }

        public Criteria andUsuarioModificoLessThanOrEqualTo(String value) {
            addCriterion("\"usuario_modifico\" <=", value, "usuarioModifico");
            return (Criteria) this;
        }

        public Criteria andUsuarioModificoLike(String value) {
            addCriterion("\"usuario_modifico\" like", value, "usuarioModifico");
            return (Criteria) this;
        }

        public Criteria andUsuarioModificoNotLike(String value) {
            addCriterion("\"usuario_modifico\" not like", value, "usuarioModifico");
            return (Criteria) this;
        }

        public Criteria andUsuarioModificoIn(List<String> values) {
            addCriterion("\"usuario_modifico\" in", values, "usuarioModifico");
            return (Criteria) this;
        }

        public Criteria andUsuarioModificoNotIn(List<String> values) {
            addCriterion("\"usuario_modifico\" not in", values, "usuarioModifico");
            return (Criteria) this;
        }

        public Criteria andUsuarioModificoBetween(String value1, String value2) {
            addCriterion("\"usuario_modifico\" between", value1, value2, "usuarioModifico");
            return (Criteria) this;
        }

        public Criteria andUsuarioModificoNotBetween(String value1, String value2) {
            addCriterion("\"usuario_modifico\" not between", value1, value2, "usuarioModifico");
            return (Criteria) this;
        }

        public Criteria andFechaModificoIsNull() {
            addCriterion("\"fecha_modifico\" is null");
            return (Criteria) this;
        }

        public Criteria andFechaModificoIsNotNull() {
            addCriterion("\"fecha_modifico\" is not null");
            return (Criteria) this;
        }

        public Criteria andFechaModificoEqualTo(Date value) {
            addCriterion("\"fecha_modifico\" =", value, "fechaModifico");
            return (Criteria) this;
        }

        public Criteria andFechaModificoNotEqualTo(Date value) {
            addCriterion("\"fecha_modifico\" <>", value, "fechaModifico");
            return (Criteria) this;
        }

        public Criteria andFechaModificoGreaterThan(Date value) {
            addCriterion("\"fecha_modifico\" >", value, "fechaModifico");
            return (Criteria) this;
        }

        public Criteria andFechaModificoGreaterThanOrEqualTo(Date value) {
            addCriterion("\"fecha_modifico\" >=", value, "fechaModifico");
            return (Criteria) this;
        }

        public Criteria andFechaModificoLessThan(Date value) {
            addCriterion("\"fecha_modifico\" <", value, "fechaModifico");
            return (Criteria) this;
        }

        public Criteria andFechaModificoLessThanOrEqualTo(Date value) {
            addCriterion("\"fecha_modifico\" <=", value, "fechaModifico");
            return (Criteria) this;
        }

        public Criteria andFechaModificoIn(List<Date> values) {
            addCriterion("\"fecha_modifico\" in", values, "fechaModifico");
            return (Criteria) this;
        }

        public Criteria andFechaModificoNotIn(List<Date> values) {
            addCriterion("\"fecha_modifico\" not in", values, "fechaModifico");
            return (Criteria) this;
        }

        public Criteria andFechaModificoBetween(Date value1, Date value2) {
            addCriterion("\"fecha_modifico\" between", value1, value2, "fechaModifico");
            return (Criteria) this;
        }

        public Criteria andFechaModificoNotBetween(Date value1, Date value2) {
            addCriterion("\"fecha_modifico\" not between", value1, value2, "fechaModifico");
            return (Criteria) this;
        }

        public Criteria andIndMascotaPropiaIsNull() {
            addCriterion("\"ind_mascota_propia\" is null");
            return (Criteria) this;
        }

        public Criteria andIndMascotaPropiaIsNotNull() {
            addCriterion("\"ind_mascota_propia\" is not null");
            return (Criteria) this;
        }

        public Criteria andIndMascotaPropiaEqualTo(Integer value) {
            addCriterion("\"ind_mascota_propia\" =", value, "indMascotaPropia");
            return (Criteria) this;
        }

        public Criteria andIndMascotaPropiaNotEqualTo(Integer value) {
            addCriterion("\"ind_mascota_propia\" <>", value, "indMascotaPropia");
            return (Criteria) this;
        }

        public Criteria andIndMascotaPropiaGreaterThan(Integer value) {
            addCriterion("\"ind_mascota_propia\" >", value, "indMascotaPropia");
            return (Criteria) this;
        }

        public Criteria andIndMascotaPropiaGreaterThanOrEqualTo(Integer value) {
            addCriterion("\"ind_mascota_propia\" >=", value, "indMascotaPropia");
            return (Criteria) this;
        }

        public Criteria andIndMascotaPropiaLessThan(Integer value) {
            addCriterion("\"ind_mascota_propia\" <", value, "indMascotaPropia");
            return (Criteria) this;
        }

        public Criteria andIndMascotaPropiaLessThanOrEqualTo(Integer value) {
            addCriterion("\"ind_mascota_propia\" <=", value, "indMascotaPropia");
            return (Criteria) this;
        }

        public Criteria andIndMascotaPropiaIn(List<Integer> values) {
            addCriterion("\"ind_mascota_propia\" in", values, "indMascotaPropia");
            return (Criteria) this;
        }

        public Criteria andIndMascotaPropiaNotIn(List<Integer> values) {
            addCriterion("\"ind_mascota_propia\" not in", values, "indMascotaPropia");
            return (Criteria) this;
        }

        public Criteria andIndMascotaPropiaBetween(Integer value1, Integer value2) {
            addCriterion("\"ind_mascota_propia\" between", value1, value2, "indMascotaPropia");
            return (Criteria) this;
        }

        public Criteria andIndMascotaPropiaNotBetween(Integer value1, Integer value2) {
            addCriterion("\"ind_mascota_propia\" not between", value1, value2, "indMascotaPropia");
            return (Criteria) this;
        }

        public Criteria andFotoQrIsNull() {
            addCriterion("\"foto_qr\" is null");
            return (Criteria) this;
        }

        public Criteria andFotoQrIsNotNull() {
            addCriterion("\"foto_qr\" is not null");
            return (Criteria) this;
        }

        public Criteria andFotoQrEqualTo(String value) {
            addCriterion("\"foto_qr\" =", value, "fotoQr");
            return (Criteria) this;
        }

        public Criteria andFotoQrNotEqualTo(String value) {
            addCriterion("\"foto_qr\" <>", value, "fotoQr");
            return (Criteria) this;
        }

        public Criteria andFotoQrGreaterThan(String value) {
            addCriterion("\"foto_qr\" >", value, "fotoQr");
            return (Criteria) this;
        }

        public Criteria andFotoQrGreaterThanOrEqualTo(String value) {
            addCriterion("\"foto_qr\" >=", value, "fotoQr");
            return (Criteria) this;
        }

        public Criteria andFotoQrLessThan(String value) {
            addCriterion("\"foto_qr\" <", value, "fotoQr");
            return (Criteria) this;
        }

        public Criteria andFotoQrLessThanOrEqualTo(String value) {
            addCriterion("\"foto_qr\" <=", value, "fotoQr");
            return (Criteria) this;
        }

        public Criteria andFotoQrLike(String value) {
            addCriterion("\"foto_qr\" like", value, "fotoQr");
            return (Criteria) this;
        }

        public Criteria andFotoQrNotLike(String value) {
            addCriterion("\"foto_qr\" not like", value, "fotoQr");
            return (Criteria) this;
        }

        public Criteria andFotoQrIn(List<String> values) {
            addCriterion("\"foto_qr\" in", values, "fotoQr");
            return (Criteria) this;
        }

        public Criteria andFotoQrNotIn(List<String> values) {
            addCriterion("\"foto_qr\" not in", values, "fotoQr");
            return (Criteria) this;
        }

        public Criteria andFotoQrBetween(String value1, String value2) {
            addCriterion("\"foto_qr\" between", value1, value2, "fotoQr");
            return (Criteria) this;
        }

        public Criteria andFotoQrNotBetween(String value1, String value2) {
            addCriterion("\"foto_qr\" not between", value1, value2, "fotoQr");
            return (Criteria) this;
        }

        public Criteria andTelefonoIsNull() {
            addCriterion("\"telefono\" is null");
            return (Criteria) this;
        }

        public Criteria andTelefonoIsNotNull() {
            addCriterion("\"telefono\" is not null");
            return (Criteria) this;
        }

        public Criteria andTelefonoEqualTo(String value) {
            addCriterion("\"telefono\" =", value, "telefono");
            return (Criteria) this;
        }

        public Criteria andTelefonoNotEqualTo(String value) {
            addCriterion("\"telefono\" <>", value, "telefono");
            return (Criteria) this;
        }

        public Criteria andTelefonoGreaterThan(String value) {
            addCriterion("\"telefono\" >", value, "telefono");
            return (Criteria) this;
        }

        public Criteria andTelefonoGreaterThanOrEqualTo(String value) {
            addCriterion("\"telefono\" >=", value, "telefono");
            return (Criteria) this;
        }

        public Criteria andTelefonoLessThan(String value) {
            addCriterion("\"telefono\" <", value, "telefono");
            return (Criteria) this;
        }

        public Criteria andTelefonoLessThanOrEqualTo(String value) {
            addCriterion("\"telefono\" <=", value, "telefono");
            return (Criteria) this;
        }

        public Criteria andTelefonoLike(String value) {
            addCriterion("\"telefono\" like", value, "telefono");
            return (Criteria) this;
        }

        public Criteria andTelefonoNotLike(String value) {
            addCriterion("\"telefono\" not like", value, "telefono");
            return (Criteria) this;
        }

        public Criteria andTelefonoIn(List<String> values) {
            addCriterion("\"telefono\" in", values, "telefono");
            return (Criteria) this;
        }

        public Criteria andTelefonoNotIn(List<String> values) {
            addCriterion("\"telefono\" not in", values, "telefono");
            return (Criteria) this;
        }

        public Criteria andTelefonoBetween(String value1, String value2) {
            addCriterion("\"telefono\" between", value1, value2, "telefono");
            return (Criteria) this;
        }

        public Criteria andTelefonoNotBetween(String value1, String value2) {
            addCriterion("\"telefono\" not between", value1, value2, "telefono");
            return (Criteria) this;
        }

        public Criteria andIndvigenciaIsNull() {
            addCriterion("\"indVigencia\" is null");
            return (Criteria) this;
        }

        public Criteria andIndvigenciaIsNotNull() {
            addCriterion("\"indVigencia\" is not null");
            return (Criteria) this;
        }

        public Criteria andIndvigenciaEqualTo(Integer value) {
            addCriterion("\"indVigencia\" =", value, "indvigencia");
            return (Criteria) this;
        }

        public Criteria andIndvigenciaNotEqualTo(Integer value) {
            addCriterion("\"indVigencia\" <>", value, "indvigencia");
            return (Criteria) this;
        }

        public Criteria andIndvigenciaGreaterThan(Integer value) {
            addCriterion("\"indVigencia\" >", value, "indvigencia");
            return (Criteria) this;
        }

        public Criteria andIndvigenciaGreaterThanOrEqualTo(Integer value) {
            addCriterion("\"indVigencia\" >=", value, "indvigencia");
            return (Criteria) this;
        }

        public Criteria andIndvigenciaLessThan(Integer value) {
            addCriterion("\"indVigencia\" <", value, "indvigencia");
            return (Criteria) this;
        }

        public Criteria andIndvigenciaLessThanOrEqualTo(Integer value) {
            addCriterion("\"indVigencia\" <=", value, "indvigencia");
            return (Criteria) this;
        }

        public Criteria andIndvigenciaIn(List<Integer> values) {
            addCriterion("\"indVigencia\" in", values, "indvigencia");
            return (Criteria) this;
        }

        public Criteria andIndvigenciaNotIn(List<Integer> values) {
            addCriterion("\"indVigencia\" not in", values, "indvigencia");
            return (Criteria) this;
        }

        public Criteria andIndvigenciaBetween(Integer value1, Integer value2) {
            addCriterion("\"indVigencia\" between", value1, value2, "indvigencia");
            return (Criteria) this;
        }

        public Criteria andIndvigenciaNotBetween(Integer value1, Integer value2) {
            addCriterion("\"indVigencia\" not between", value1, value2, "indvigencia");
            return (Criteria) this;
        }

        public Criteria andVigenciaIsNull() {
            addCriterion("\"vigencia\" is null");
            return (Criteria) this;
        }

        public Criteria andVigenciaIsNotNull() {
            addCriterion("\"vigencia\" is not null");
            return (Criteria) this;
        }

        public Criteria andVigenciaEqualTo(Date value) {
            addCriterion("\"vigencia\" =", value, "vigencia");
            return (Criteria) this;
        }

        public Criteria andVigenciaNotEqualTo(Date value) {
            addCriterion("\"vigencia\" <>", value, "vigencia");
            return (Criteria) this;
        }

        public Criteria andVigenciaGreaterThan(Date value) {
            addCriterion("\"vigencia\" >", value, "vigencia");
            return (Criteria) this;
        }

        public Criteria andVigenciaGreaterThanOrEqualTo(Date value) {
            addCriterion("\"vigencia\" >=", value, "vigencia");
            return (Criteria) this;
        }

        public Criteria andVigenciaLessThan(Date value) {
            addCriterion("\"vigencia\" <", value, "vigencia");
            return (Criteria) this;
        }

        public Criteria andVigenciaLessThanOrEqualTo(Date value) {
            addCriterion("\"vigencia\" <=", value, "vigencia");
            return (Criteria) this;
        }

        public Criteria andVigenciaIn(List<Date> values) {
            addCriterion("\"vigencia\" in", values, "vigencia");
            return (Criteria) this;
        }

        public Criteria andVigenciaNotIn(List<Date> values) {
            addCriterion("\"vigencia\" not in", values, "vigencia");
            return (Criteria) this;
        }

        public Criteria andVigenciaBetween(Date value1, Date value2) {
            addCriterion("\"vigencia\" between", value1, value2, "vigencia");
            return (Criteria) this;
        }

        public Criteria andVigenciaNotBetween(Date value1, Date value2) {
            addCriterion("\"vigencia\" not between", value1, value2, "vigencia");
            return (Criteria) this;
        }

        public Criteria andDesParametro1IsNull() {
            addCriterion("\"des_parametro1\" is null");
            return (Criteria) this;
        }

        public Criteria andDesParametro1IsNotNull() {
            addCriterion("\"des_parametro1\" is not null");
            return (Criteria) this;
        }

        public Criteria andDesParametro1EqualTo(String value) {
            addCriterion("\"des_parametro1\" =", value, "desParametro1");
            return (Criteria) this;
        }

        public Criteria andDesParametro1NotEqualTo(String value) {
            addCriterion("\"des_parametro1\" <>", value, "desParametro1");
            return (Criteria) this;
        }

        public Criteria andDesParametro1GreaterThan(String value) {
            addCriterion("\"des_parametro1\" >", value, "desParametro1");
            return (Criteria) this;
        }

        public Criteria andDesParametro1GreaterThanOrEqualTo(String value) {
            addCriterion("\"des_parametro1\" >=", value, "desParametro1");
            return (Criteria) this;
        }

        public Criteria andDesParametro1LessThan(String value) {
            addCriterion("\"des_parametro1\" <", value, "desParametro1");
            return (Criteria) this;
        }

        public Criteria andDesParametro1LessThanOrEqualTo(String value) {
            addCriterion("\"des_parametro1\" <=", value, "desParametro1");
            return (Criteria) this;
        }

        public Criteria andDesParametro1Like(String value) {
            addCriterion("\"des_parametro1\" like", value, "desParametro1");
            return (Criteria) this;
        }

        public Criteria andDesParametro1NotLike(String value) {
            addCriterion("\"des_parametro1\" not like", value, "desParametro1");
            return (Criteria) this;
        }

        public Criteria andDesParametro1In(List<String> values) {
            addCriterion("\"des_parametro1\" in", values, "desParametro1");
            return (Criteria) this;
        }

        public Criteria andDesParametro1NotIn(List<String> values) {
            addCriterion("\"des_parametro1\" not in", values, "desParametro1");
            return (Criteria) this;
        }

        public Criteria andDesParametro1Between(String value1, String value2) {
            addCriterion("\"des_parametro1\" between", value1, value2, "desParametro1");
            return (Criteria) this;
        }

        public Criteria andDesParametro1NotBetween(String value1, String value2) {
            addCriterion("\"des_parametro1\" not between", value1, value2, "desParametro1");
            return (Criteria) this;
        }

        public Criteria andDesParametro2IsNull() {
            addCriterion("\"des_parametro2\" is null");
            return (Criteria) this;
        }

        public Criteria andDesParametro2IsNotNull() {
            addCriterion("\"des_parametro2\" is not null");
            return (Criteria) this;
        }

        public Criteria andDesParametro2EqualTo(String value) {
            addCriterion("\"des_parametro2\" =", value, "desParametro2");
            return (Criteria) this;
        }

        public Criteria andDesParametro2NotEqualTo(String value) {
            addCriterion("\"des_parametro2\" <>", value, "desParametro2");
            return (Criteria) this;
        }

        public Criteria andDesParametro2GreaterThan(String value) {
            addCriterion("\"des_parametro2\" >", value, "desParametro2");
            return (Criteria) this;
        }

        public Criteria andDesParametro2GreaterThanOrEqualTo(String value) {
            addCriterion("\"des_parametro2\" >=", value, "desParametro2");
            return (Criteria) this;
        }

        public Criteria andDesParametro2LessThan(String value) {
            addCriterion("\"des_parametro2\" <", value, "desParametro2");
            return (Criteria) this;
        }

        public Criteria andDesParametro2LessThanOrEqualTo(String value) {
            addCriterion("\"des_parametro2\" <=", value, "desParametro2");
            return (Criteria) this;
        }

        public Criteria andDesParametro2Like(String value) {
            addCriterion("\"des_parametro2\" like", value, "desParametro2");
            return (Criteria) this;
        }

        public Criteria andDesParametro2NotLike(String value) {
            addCriterion("\"des_parametro2\" not like", value, "desParametro2");
            return (Criteria) this;
        }

        public Criteria andDesParametro2In(List<String> values) {
            addCriterion("\"des_parametro2\" in", values, "desParametro2");
            return (Criteria) this;
        }

        public Criteria andDesParametro2NotIn(List<String> values) {
            addCriterion("\"des_parametro2\" not in", values, "desParametro2");
            return (Criteria) this;
        }

        public Criteria andDesParametro2Between(String value1, String value2) {
            addCriterion("\"des_parametro2\" between", value1, value2, "desParametro2");
            return (Criteria) this;
        }

        public Criteria andDesParametro2NotBetween(String value1, String value2) {
            addCriterion("\"des_parametro2\" not between", value1, value2, "desParametro2");
            return (Criteria) this;
        }

        public Criteria andNumParametro1IsNull() {
            addCriterion("\"num_parametro1\" is null");
            return (Criteria) this;
        }

        public Criteria andNumParametro1IsNotNull() {
            addCriterion("\"num_parametro1\" is not null");
            return (Criteria) this;
        }

        public Criteria andNumParametro1EqualTo(Integer value) {
            addCriterion("\"num_parametro1\" =", value, "numParametro1");
            return (Criteria) this;
        }

        public Criteria andNumParametro1NotEqualTo(Integer value) {
            addCriterion("\"num_parametro1\" <>", value, "numParametro1");
            return (Criteria) this;
        }

        public Criteria andNumParametro1GreaterThan(Integer value) {
            addCriterion("\"num_parametro1\" >", value, "numParametro1");
            return (Criteria) this;
        }

        public Criteria andNumParametro1GreaterThanOrEqualTo(Integer value) {
            addCriterion("\"num_parametro1\" >=", value, "numParametro1");
            return (Criteria) this;
        }

        public Criteria andNumParametro1LessThan(Integer value) {
            addCriterion("\"num_parametro1\" <", value, "numParametro1");
            return (Criteria) this;
        }

        public Criteria andNumParametro1LessThanOrEqualTo(Integer value) {
            addCriterion("\"num_parametro1\" <=", value, "numParametro1");
            return (Criteria) this;
        }

        public Criteria andNumParametro1In(List<Integer> values) {
            addCriterion("\"num_parametro1\" in", values, "numParametro1");
            return (Criteria) this;
        }

        public Criteria andNumParametro1NotIn(List<Integer> values) {
            addCriterion("\"num_parametro1\" not in", values, "numParametro1");
            return (Criteria) this;
        }

        public Criteria andNumParametro1Between(Integer value1, Integer value2) {
            addCriterion("\"num_parametro1\" between", value1, value2, "numParametro1");
            return (Criteria) this;
        }

        public Criteria andNumParametro1NotBetween(Integer value1, Integer value2) {
            addCriterion("\"num_parametro1\" not between", value1, value2, "numParametro1");
            return (Criteria) this;
        }

        public Criteria andNumParametro2IsNull() {
            addCriterion("\"num_parametro2\" is null");
            return (Criteria) this;
        }

        public Criteria andNumParametro2IsNotNull() {
            addCriterion("\"num_parametro2\" is not null");
            return (Criteria) this;
        }

        public Criteria andNumParametro2EqualTo(Integer value) {
            addCriterion("\"num_parametro2\" =", value, "numParametro2");
            return (Criteria) this;
        }

        public Criteria andNumParametro2NotEqualTo(Integer value) {
            addCriterion("\"num_parametro2\" <>", value, "numParametro2");
            return (Criteria) this;
        }

        public Criteria andNumParametro2GreaterThan(Integer value) {
            addCriterion("\"num_parametro2\" >", value, "numParametro2");
            return (Criteria) this;
        }

        public Criteria andNumParametro2GreaterThanOrEqualTo(Integer value) {
            addCriterion("\"num_parametro2\" >=", value, "numParametro2");
            return (Criteria) this;
        }

        public Criteria andNumParametro2LessThan(Integer value) {
            addCriterion("\"num_parametro2\" <", value, "numParametro2");
            return (Criteria) this;
        }

        public Criteria andNumParametro2LessThanOrEqualTo(Integer value) {
            addCriterion("\"num_parametro2\" <=", value, "numParametro2");
            return (Criteria) this;
        }

        public Criteria andNumParametro2In(List<Integer> values) {
            addCriterion("\"num_parametro2\" in", values, "numParametro2");
            return (Criteria) this;
        }

        public Criteria andNumParametro2NotIn(List<Integer> values) {
            addCriterion("\"num_parametro2\" not in", values, "numParametro2");
            return (Criteria) this;
        }

        public Criteria andNumParametro2Between(Integer value1, Integer value2) {
            addCriterion("\"num_parametro2\" between", value1, value2, "numParametro2");
            return (Criteria) this;
        }

        public Criteria andNumParametro2NotBetween(Integer value1, Integer value2) {
            addCriterion("\"num_parametro2\" not between", value1, value2, "numParametro2");
            return (Criteria) this;
        }

        public Criteria andDateParametro1IsNull() {
            addCriterion("\"date_parametro1\" is null");
            return (Criteria) this;
        }

        public Criteria andDateParametro1IsNotNull() {
            addCriterion("\"date_parametro1\" is not null");
            return (Criteria) this;
        }

        public Criteria andDateParametro1EqualTo(Date value) {
            addCriterion("\"date_parametro1\" =", value, "dateParametro1");
            return (Criteria) this;
        }

        public Criteria andDateParametro1NotEqualTo(Date value) {
            addCriterion("\"date_parametro1\" <>", value, "dateParametro1");
            return (Criteria) this;
        }

        public Criteria andDateParametro1GreaterThan(Date value) {
            addCriterion("\"date_parametro1\" >", value, "dateParametro1");
            return (Criteria) this;
        }

        public Criteria andDateParametro1GreaterThanOrEqualTo(Date value) {
            addCriterion("\"date_parametro1\" >=", value, "dateParametro1");
            return (Criteria) this;
        }

        public Criteria andDateParametro1LessThan(Date value) {
            addCriterion("\"date_parametro1\" <", value, "dateParametro1");
            return (Criteria) this;
        }

        public Criteria andDateParametro1LessThanOrEqualTo(Date value) {
            addCriterion("\"date_parametro1\" <=", value, "dateParametro1");
            return (Criteria) this;
        }

        public Criteria andDateParametro1In(List<Date> values) {
            addCriterion("\"date_parametro1\" in", values, "dateParametro1");
            return (Criteria) this;
        }

        public Criteria andDateParametro1NotIn(List<Date> values) {
            addCriterion("\"date_parametro1\" not in", values, "dateParametro1");
            return (Criteria) this;
        }

        public Criteria andDateParametro1Between(Date value1, Date value2) {
            addCriterion("\"date_parametro1\" between", value1, value2, "dateParametro1");
            return (Criteria) this;
        }

        public Criteria andDateParametro1NotBetween(Date value1, Date value2) {
            addCriterion("\"date_parametro1\" not between", value1, value2, "dateParametro1");
            return (Criteria) this;
        }

        public Criteria andDateParametro2IsNull() {
            addCriterion("\"date_parametro2\" is null");
            return (Criteria) this;
        }

        public Criteria andDateParametro2IsNotNull() {
            addCriterion("\"date_parametro2\" is not null");
            return (Criteria) this;
        }

        public Criteria andDateParametro2EqualTo(Date value) {
            addCriterion("\"date_parametro2\" =", value, "dateParametro2");
            return (Criteria) this;
        }

        public Criteria andDateParametro2NotEqualTo(Date value) {
            addCriterion("\"date_parametro2\" <>", value, "dateParametro2");
            return (Criteria) this;
        }

        public Criteria andDateParametro2GreaterThan(Date value) {
            addCriterion("\"date_parametro2\" >", value, "dateParametro2");
            return (Criteria) this;
        }

        public Criteria andDateParametro2GreaterThanOrEqualTo(Date value) {
            addCriterion("\"date_parametro2\" >=", value, "dateParametro2");
            return (Criteria) this;
        }

        public Criteria andDateParametro2LessThan(Date value) {
            addCriterion("\"date_parametro2\" <", value, "dateParametro2");
            return (Criteria) this;
        }

        public Criteria andDateParametro2LessThanOrEqualTo(Date value) {
            addCriterion("\"date_parametro2\" <=", value, "dateParametro2");
            return (Criteria) this;
        }

        public Criteria andDateParametro2In(List<Date> values) {
            addCriterion("\"date_parametro2\" in", values, "dateParametro2");
            return (Criteria) this;
        }

        public Criteria andDateParametro2NotIn(List<Date> values) {
            addCriterion("\"date_parametro2\" not in", values, "dateParametro2");
            return (Criteria) this;
        }

        public Criteria andDateParametro2Between(Date value1, Date value2) {
            addCriterion("\"date_parametro2\" between", value1, value2, "dateParametro2");
            return (Criteria) this;
        }

        public Criteria andDateParametro2NotBetween(Date value1, Date value2) {
            addCriterion("\"date_parametro2\" not between", value1, value2, "dateParametro2");
            return (Criteria) this;
        }

        public Criteria andNombrecompletoIsNull() {
            addCriterion("\"nombrecompleto\" is null");
            return (Criteria) this;
        }

        public Criteria andNombrecompletoIsNotNull() {
            addCriterion("\"nombrecompleto\" is not null");
            return (Criteria) this;
        }

        public Criteria andNombrecompletoEqualTo(String value) {
            addCriterion("\"nombrecompleto\" =", value, "nombrecompleto");
            return (Criteria) this;
        }

        public Criteria andNombrecompletoNotEqualTo(String value) {
            addCriterion("\"nombrecompleto\" <>", value, "nombrecompleto");
            return (Criteria) this;
        }

        public Criteria andNombrecompletoGreaterThan(String value) {
            addCriterion("\"nombrecompleto\" >", value, "nombrecompleto");
            return (Criteria) this;
        }

        public Criteria andNombrecompletoGreaterThanOrEqualTo(String value) {
            addCriterion("\"nombrecompleto\" >=", value, "nombrecompleto");
            return (Criteria) this;
        }

        public Criteria andNombrecompletoLessThan(String value) {
            addCriterion("\"nombrecompleto\" <", value, "nombrecompleto");
            return (Criteria) this;
        }

        public Criteria andNombrecompletoLessThanOrEqualTo(String value) {
            addCriterion("\"nombrecompleto\" <=", value, "nombrecompleto");
            return (Criteria) this;
        }

        public Criteria andNombrecompletoLike(String value) {
            addCriterion("\"nombrecompleto\" like", value, "nombrecompleto");
            return (Criteria) this;
        }

        public Criteria andNombrecompletoNotLike(String value) {
            addCriterion("\"nombrecompleto\" not like", value, "nombrecompleto");
            return (Criteria) this;
        }

        public Criteria andNombrecompletoIn(List<String> values) {
            addCriterion("\"nombrecompleto\" in", values, "nombrecompleto");
            return (Criteria) this;
        }

        public Criteria andNombrecompletoNotIn(List<String> values) {
            addCriterion("\"nombrecompleto\" not in", values, "nombrecompleto");
            return (Criteria) this;
        }

        public Criteria andNombrecompletoBetween(String value1, String value2) {
            addCriterion("\"nombrecompleto\" between", value1, value2, "nombrecompleto");
            return (Criteria) this;
        }

        public Criteria andNombrecompletoNotBetween(String value1, String value2) {
            addCriterion("\"nombrecompleto\" not between", value1, value2, "nombrecompleto");
            return (Criteria) this;
        }

        public Criteria andFotopublicacionIsNull() {
            addCriterion("\"fotopublicacion\" is null");
            return (Criteria) this;
        }

        public Criteria andFotopublicacionIsNotNull() {
            addCriterion("\"fotopublicacion\" is not null");
            return (Criteria) this;
        }

        public Criteria andFotopublicacionEqualTo(String value) {
            addCriterion("\"fotopublicacion\" =", value, "fotopublicacion");
            return (Criteria) this;
        }

        public Criteria andFotopublicacionNotEqualTo(String value) {
            addCriterion("\"fotopublicacion\" <>", value, "fotopublicacion");
            return (Criteria) this;
        }

        public Criteria andFotopublicacionGreaterThan(String value) {
            addCriterion("\"fotopublicacion\" >", value, "fotopublicacion");
            return (Criteria) this;
        }

        public Criteria andFotopublicacionGreaterThanOrEqualTo(String value) {
            addCriterion("\"fotopublicacion\" >=", value, "fotopublicacion");
            return (Criteria) this;
        }

        public Criteria andFotopublicacionLessThan(String value) {
            addCriterion("\"fotopublicacion\" <", value, "fotopublicacion");
            return (Criteria) this;
        }

        public Criteria andFotopublicacionLessThanOrEqualTo(String value) {
            addCriterion("\"fotopublicacion\" <=", value, "fotopublicacion");
            return (Criteria) this;
        }

        public Criteria andFotopublicacionLike(String value) {
            addCriterion("\"fotopublicacion\" like", value, "fotopublicacion");
            return (Criteria) this;
        }

        public Criteria andFotopublicacionNotLike(String value) {
            addCriterion("\"fotopublicacion\" not like", value, "fotopublicacion");
            return (Criteria) this;
        }

        public Criteria andFotopublicacionIn(List<String> values) {
            addCriterion("\"fotopublicacion\" in", values, "fotopublicacion");
            return (Criteria) this;
        }

        public Criteria andFotopublicacionNotIn(List<String> values) {
            addCriterion("\"fotopublicacion\" not in", values, "fotopublicacion");
            return (Criteria) this;
        }

        public Criteria andFotopublicacionBetween(String value1, String value2) {
            addCriterion("\"fotopublicacion\" between", value1, value2, "fotopublicacion");
            return (Criteria) this;
        }

        public Criteria andFotopublicacionNotBetween(String value1, String value2) {
            addCriterion("\"fotopublicacion\" not between", value1, value2, "fotopublicacion");
            return (Criteria) this;
        }

        public Criteria andDesparametro3IsNull() {
            addCriterion("\"desparametro3\" is null");
            return (Criteria) this;
        }

        public Criteria andDesparametro3IsNotNull() {
            addCriterion("\"desparametro3\" is not null");
            return (Criteria) this;
        }

        public Criteria andDesparametro3EqualTo(String value) {
            addCriterion("\"desparametro3\" =", value, "desparametro3");
            return (Criteria) this;
        }

        public Criteria andDesparametro3NotEqualTo(String value) {
            addCriterion("\"desparametro3\" <>", value, "desparametro3");
            return (Criteria) this;
        }

        public Criteria andDesparametro3GreaterThan(String value) {
            addCriterion("\"desparametro3\" >", value, "desparametro3");
            return (Criteria) this;
        }

        public Criteria andDesparametro3GreaterThanOrEqualTo(String value) {
            addCriterion("\"desparametro3\" >=", value, "desparametro3");
            return (Criteria) this;
        }

        public Criteria andDesparametro3LessThan(String value) {
            addCriterion("\"desparametro3\" <", value, "desparametro3");
            return (Criteria) this;
        }

        public Criteria andDesparametro3LessThanOrEqualTo(String value) {
            addCriterion("\"desparametro3\" <=", value, "desparametro3");
            return (Criteria) this;
        }

        public Criteria andDesparametro3Like(String value) {
            addCriterion("\"desparametro3\" like", value, "desparametro3");
            return (Criteria) this;
        }

        public Criteria andDesparametro3NotLike(String value) {
            addCriterion("\"desparametro3\" not like", value, "desparametro3");
            return (Criteria) this;
        }

        public Criteria andDesparametro3In(List<String> values) {
            addCriterion("\"desparametro3\" in", values, "desparametro3");
            return (Criteria) this;
        }

        public Criteria andDesparametro3NotIn(List<String> values) {
            addCriterion("\"desparametro3\" not in", values, "desparametro3");
            return (Criteria) this;
        }

        public Criteria andDesparametro3Between(String value1, String value2) {
            addCriterion("\"desparametro3\" between", value1, value2, "desparametro3");
            return (Criteria) this;
        }

        public Criteria andDesparametro3NotBetween(String value1, String value2) {
            addCriterion("\"desparametro3\" not between", value1, value2, "desparametro3");
            return (Criteria) this;
        }

        public Criteria andDesparametro4IsNull() {
            addCriterion("\"desparametro4\" is null");
            return (Criteria) this;
        }

        public Criteria andDesparametro4IsNotNull() {
            addCriterion("\"desparametro4\" is not null");
            return (Criteria) this;
        }

        public Criteria andDesparametro4EqualTo(String value) {
            addCriterion("\"desparametro4\" =", value, "desparametro4");
            return (Criteria) this;
        }

        public Criteria andDesparametro4NotEqualTo(String value) {
            addCriterion("\"desparametro4\" <>", value, "desparametro4");
            return (Criteria) this;
        }

        public Criteria andDesparametro4GreaterThan(String value) {
            addCriterion("\"desparametro4\" >", value, "desparametro4");
            return (Criteria) this;
        }

        public Criteria andDesparametro4GreaterThanOrEqualTo(String value) {
            addCriterion("\"desparametro4\" >=", value, "desparametro4");
            return (Criteria) this;
        }

        public Criteria andDesparametro4LessThan(String value) {
            addCriterion("\"desparametro4\" <", value, "desparametro4");
            return (Criteria) this;
        }

        public Criteria andDesparametro4LessThanOrEqualTo(String value) {
            addCriterion("\"desparametro4\" <=", value, "desparametro4");
            return (Criteria) this;
        }

        public Criteria andDesparametro4Like(String value) {
            addCriterion("\"desparametro4\" like", value, "desparametro4");
            return (Criteria) this;
        }

        public Criteria andDesparametro4NotLike(String value) {
            addCriterion("\"desparametro4\" not like", value, "desparametro4");
            return (Criteria) this;
        }

        public Criteria andDesparametro4In(List<String> values) {
            addCriterion("\"desparametro4\" in", values, "desparametro4");
            return (Criteria) this;
        }

        public Criteria andDesparametro4NotIn(List<String> values) {
            addCriterion("\"desparametro4\" not in", values, "desparametro4");
            return (Criteria) this;
        }

        public Criteria andDesparametro4Between(String value1, String value2) {
            addCriterion("\"desparametro4\" between", value1, value2, "desparametro4");
            return (Criteria) this;
        }

        public Criteria andDesparametro4NotBetween(String value1, String value2) {
            addCriterion("\"desparametro4\" not between", value1, value2, "desparametro4");
            return (Criteria) this;
        }

        public Criteria andMontoRecompensaIsNull() {
            addCriterion("\"monto_recompensa\" is null");
            return (Criteria) this;
        }

        public Criteria andMontoRecompensaIsNotNull() {
            addCriterion("\"monto_recompensa\" is not null");
            return (Criteria) this;
        }

        public Criteria andMontoRecompensaEqualTo(String value) {
            addCriterion("\"monto_recompensa\" =", value, "montoRecompensa");
            return (Criteria) this;
        }

        public Criteria andMontoRecompensaNotEqualTo(String value) {
            addCriterion("\"monto_recompensa\" <>", value, "montoRecompensa");
            return (Criteria) this;
        }

        public Criteria andMontoRecompensaGreaterThan(String value) {
            addCriterion("\"monto_recompensa\" >", value, "montoRecompensa");
            return (Criteria) this;
        }

        public Criteria andMontoRecompensaGreaterThanOrEqualTo(String value) {
            addCriterion("\"monto_recompensa\" >=", value, "montoRecompensa");
            return (Criteria) this;
        }

        public Criteria andMontoRecompensaLessThan(String value) {
            addCriterion("\"monto_recompensa\" <", value, "montoRecompensa");
            return (Criteria) this;
        }

        public Criteria andMontoRecompensaLessThanOrEqualTo(String value) {
            addCriterion("\"monto_recompensa\" <=", value, "montoRecompensa");
            return (Criteria) this;
        }

        public Criteria andMontoRecompensaLike(String value) {
            addCriterion("\"monto_recompensa\" like", value, "montoRecompensa");
            return (Criteria) this;
        }

        public Criteria andMontoRecompensaNotLike(String value) {
            addCriterion("\"monto_recompensa\" not like", value, "montoRecompensa");
            return (Criteria) this;
        }

        public Criteria andMontoRecompensaIn(List<String> values) {
            addCriterion("\"monto_recompensa\" in", values, "montoRecompensa");
            return (Criteria) this;
        }

        public Criteria andMontoRecompensaNotIn(List<String> values) {
            addCriterion("\"monto_recompensa\" not in", values, "montoRecompensa");
            return (Criteria) this;
        }

        public Criteria andMontoRecompensaBetween(String value1, String value2) {
            addCriterion("\"monto_recompensa\" between", value1, value2, "montoRecompensa");
            return (Criteria) this;
        }

        public Criteria andMontoRecompensaNotBetween(String value1, String value2) {
            addCriterion("\"monto_recompensa\" not between", value1, value2, "montoRecompensa");
            return (Criteria) this;
        }

        public Criteria andUbicacionCatastroLikeInsensitive(String value) {
            addCriterion("upper(\"ubicacion_catastro\") like", value.toUpperCase(), "ubicacionCatastro");
            return (Criteria) this;
        }

        public Criteria andDescripcionLikeInsensitive(String value) {
            addCriterion("upper(\"descripcion\") like", value.toUpperCase(), "descripcion");
            return (Criteria) this;
        }

        public Criteria andComentarioAdicionalLikeInsensitive(String value) {
            addCriterion("upper(\"comentario_adicional\") like", value.toUpperCase(), "comentarioAdicional");
            return (Criteria) this;
        }

        public Criteria andUsuarioRegistroLikeInsensitive(String value) {
            addCriterion("upper(\"usuario_registro\") like", value.toUpperCase(), "usuarioRegistro");
            return (Criteria) this;
        }

        public Criteria andUsuarioModificoLikeInsensitive(String value) {
            addCriterion("upper(\"usuario_modifico\") like", value.toUpperCase(), "usuarioModifico");
            return (Criteria) this;
        }

        public Criteria andFotoQrLikeInsensitive(String value) {
            addCriterion("upper(\"foto_qr\") like", value.toUpperCase(), "fotoQr");
            return (Criteria) this;
        }

        public Criteria andTelefonoLikeInsensitive(String value) {
            addCriterion("upper(\"telefono\") like", value.toUpperCase(), "telefono");
            return (Criteria) this;
        }

        public Criteria andDesParametro1LikeInsensitive(String value) {
            addCriterion("upper(\"des_parametro1\") like", value.toUpperCase(), "desParametro1");
            return (Criteria) this;
        }

        public Criteria andDesParametro2LikeInsensitive(String value) {
            addCriterion("upper(\"des_parametro2\") like", value.toUpperCase(), "desParametro2");
            return (Criteria) this;
        }

        public Criteria andNombrecompletoLikeInsensitive(String value) {
            addCriterion("upper(\"nombrecompleto\") like", value.toUpperCase(), "nombrecompleto");
            return (Criteria) this;
        }

        public Criteria andFotopublicacionLikeInsensitive(String value) {
            addCriterion("upper(\"fotopublicacion\") like", value.toUpperCase(), "fotopublicacion");
            return (Criteria) this;
        }

        public Criteria andDesparametro3LikeInsensitive(String value) {
            addCriterion("upper(\"desparametro3\") like", value.toUpperCase(), "desparametro3");
            return (Criteria) this;
        }

        public Criteria andDesparametro4LikeInsensitive(String value) {
            addCriterion("upper(\"desparametro4\") like", value.toUpperCase(), "desparametro4");
            return (Criteria) this;
        }

        public Criteria andMontoRecompensaLikeInsensitive(String value) {
            addCriterion("upper(\"monto_recompensa\") like", value.toUpperCase(), "montoRecompensa");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pataPerro.tm_busqueda
     *
     * @mbggenerated do_not_delete_during_merge Wed Jun 14 23:04:58 COT 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pataPerro.tm_busqueda
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}