package pe.com.pdp.domain.postgres;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.web.multipart.MultipartFile;

import pe.com.pdp.domain.model.GridModel;

public class Busqueda extends GridModel implements Serializable{
    
	private static final long serialVersionUID = 1L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_busqueda.id
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_busqueda.mascota_id
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    private Integer mascotaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_busqueda.fecha_perdida
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    @DateTimeFormat(pattern="dd/MM/yyyy")
    private Date fechaPerdida;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_busqueda.ubicacion_catastro
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    private String ubicacionCatastro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_busqueda.descripcion
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    private String descripcion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_busqueda.distrito
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    private Integer distrito;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_busqueda.estado_busqueda
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    private Integer estadoBusqueda;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_busqueda.estado
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    private Integer estado;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_busqueda.ind_recompensa
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    private Integer indRecompensa;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_busqueda.comentario_adicional
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    private String comentarioAdicional;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_busqueda.usuario_registro
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    private String usuarioRegistro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_busqueda.fecha_registro
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    private Date fechaRegistro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_busqueda.usuario_modifico
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    private String usuarioModifico;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_busqueda.fecha_modifico
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    private Date fechaModifico;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_busqueda.ind_mascota_propia
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    private Integer indMascotaPropia;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_busqueda.foto_qr
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    private String fotoQr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_busqueda.telefono
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    private String telefono;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_busqueda.indVigencia
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    private Integer indvigencia;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_busqueda.vigencia
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    private Date vigencia;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_busqueda.des_parametro1
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    private String desParametro1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_busqueda.des_parametro2
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    private String desParametro2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_busqueda.num_parametro1
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    private Integer numParametro1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_busqueda.num_parametro2
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    private Integer numParametro2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_busqueda.date_parametro1
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    private Date dateParametro1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_busqueda.date_parametro2
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    private Date dateParametro2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_busqueda.nombrecompleto
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    private String nombrecompleto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_busqueda.fotopublicacion
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    private String fotopublicacion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_busqueda.desparametro3
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    private String desparametro3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_busqueda.desparametro4
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    private String desparametro4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_busqueda.monto_recompensa
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    private String montoRecompensa;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_busqueda.id
     *
     * @return the value of pataPerro.tm_busqueda.id
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_busqueda.id
     *
     * @param id the value for pataPerro.tm_busqueda.id
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_busqueda.mascota_id
     *
     * @return the value of pataPerro.tm_busqueda.mascota_id
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public Integer getMascotaId() {
        return mascotaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_busqueda.mascota_id
     *
     * @param mascotaId the value for pataPerro.tm_busqueda.mascota_id
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public void setMascotaId(Integer mascotaId) {
        this.mascotaId = mascotaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_busqueda.fecha_perdida
     *
     * @return the value of pataPerro.tm_busqueda.fecha_perdida
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public Date getFechaPerdida() {
        return fechaPerdida;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_busqueda.fecha_perdida
     *
     * @param fechaPerdida the value for pataPerro.tm_busqueda.fecha_perdida
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public void setFechaPerdida(Date fechaPerdida) {
        this.fechaPerdida = fechaPerdida;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_busqueda.ubicacion_catastro
     *
     * @return the value of pataPerro.tm_busqueda.ubicacion_catastro
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public String getUbicacionCatastro() {
        return ubicacionCatastro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_busqueda.ubicacion_catastro
     *
     * @param ubicacionCatastro the value for pataPerro.tm_busqueda.ubicacion_catastro
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public void setUbicacionCatastro(String ubicacionCatastro) {
        this.ubicacionCatastro = ubicacionCatastro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_busqueda.descripcion
     *
     * @return the value of pataPerro.tm_busqueda.descripcion
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public String getDescripcion() {
        return descripcion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_busqueda.descripcion
     *
     * @param descripcion the value for pataPerro.tm_busqueda.descripcion
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_busqueda.distrito
     *
     * @return the value of pataPerro.tm_busqueda.distrito
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public Integer getDistrito() {
        return distrito;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_busqueda.distrito
     *
     * @param distrito the value for pataPerro.tm_busqueda.distrito
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public void setDistrito(Integer distrito) {
        this.distrito = distrito;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_busqueda.estado_busqueda
     *
     * @return the value of pataPerro.tm_busqueda.estado_busqueda
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public Integer getEstadoBusqueda() {
        return estadoBusqueda;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_busqueda.estado_busqueda
     *
     * @param estadoBusqueda the value for pataPerro.tm_busqueda.estado_busqueda
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public void setEstadoBusqueda(Integer estadoBusqueda) {
        this.estadoBusqueda = estadoBusqueda;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_busqueda.estado
     *
     * @return the value of pataPerro.tm_busqueda.estado
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public Integer getEstado() {
        return estado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_busqueda.estado
     *
     * @param estado the value for pataPerro.tm_busqueda.estado
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public void setEstado(Integer estado) {
        this.estado = estado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_busqueda.ind_recompensa
     *
     * @return the value of pataPerro.tm_busqueda.ind_recompensa
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public Integer getIndRecompensa() {
        return indRecompensa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_busqueda.ind_recompensa
     *
     * @param indRecompensa the value for pataPerro.tm_busqueda.ind_recompensa
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public void setIndRecompensa(Integer indRecompensa) {
        this.indRecompensa = indRecompensa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_busqueda.comentario_adicional
     *
     * @return the value of pataPerro.tm_busqueda.comentario_adicional
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public String getComentarioAdicional() {
        return comentarioAdicional;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_busqueda.comentario_adicional
     *
     * @param comentarioAdicional the value for pataPerro.tm_busqueda.comentario_adicional
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public void setComentarioAdicional(String comentarioAdicional) {
        this.comentarioAdicional = comentarioAdicional;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_busqueda.usuario_registro
     *
     * @return the value of pataPerro.tm_busqueda.usuario_registro
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public String getUsuarioRegistro() {
        return usuarioRegistro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_busqueda.usuario_registro
     *
     * @param usuarioRegistro the value for pataPerro.tm_busqueda.usuario_registro
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public void setUsuarioRegistro(String usuarioRegistro) {
        this.usuarioRegistro = usuarioRegistro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_busqueda.fecha_registro
     *
     * @return the value of pataPerro.tm_busqueda.fecha_registro
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public Date getFechaRegistro() {
        return fechaRegistro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_busqueda.fecha_registro
     *
     * @param fechaRegistro the value for pataPerro.tm_busqueda.fecha_registro
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_busqueda.usuario_modifico
     *
     * @return the value of pataPerro.tm_busqueda.usuario_modifico
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public String getUsuarioModifico() {
        return usuarioModifico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_busqueda.usuario_modifico
     *
     * @param usuarioModifico the value for pataPerro.tm_busqueda.usuario_modifico
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public void setUsuarioModifico(String usuarioModifico) {
        this.usuarioModifico = usuarioModifico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_busqueda.fecha_modifico
     *
     * @return the value of pataPerro.tm_busqueda.fecha_modifico
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public Date getFechaModifico() {
        return fechaModifico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_busqueda.fecha_modifico
     *
     * @param fechaModifico the value for pataPerro.tm_busqueda.fecha_modifico
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public void setFechaModifico(Date fechaModifico) {
        this.fechaModifico = fechaModifico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_busqueda.ind_mascota_propia
     *
     * @return the value of pataPerro.tm_busqueda.ind_mascota_propia
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public Integer getIndMascotaPropia() {
        return indMascotaPropia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_busqueda.ind_mascota_propia
     *
     * @param indMascotaPropia the value for pataPerro.tm_busqueda.ind_mascota_propia
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public void setIndMascotaPropia(Integer indMascotaPropia) {
        this.indMascotaPropia = indMascotaPropia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_busqueda.foto_qr
     *
     * @return the value of pataPerro.tm_busqueda.foto_qr
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public String getFotoQr() {
        return fotoQr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_busqueda.foto_qr
     *
     * @param fotoQr the value for pataPerro.tm_busqueda.foto_qr
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public void setFotoQr(String fotoQr) {
        this.fotoQr = fotoQr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_busqueda.telefono
     *
     * @return the value of pataPerro.tm_busqueda.telefono
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public String getTelefono() {
        return telefono;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_busqueda.telefono
     *
     * @param telefono the value for pataPerro.tm_busqueda.telefono
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_busqueda.indVigencia
     *
     * @return the value of pataPerro.tm_busqueda.indVigencia
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public Integer getIndvigencia() {
        return indvigencia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_busqueda.indVigencia
     *
     * @param indvigencia the value for pataPerro.tm_busqueda.indVigencia
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public void setIndvigencia(Integer indvigencia) {
        this.indvigencia = indvigencia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_busqueda.vigencia
     *
     * @return the value of pataPerro.tm_busqueda.vigencia
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public Date getVigencia() {
        return vigencia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_busqueda.vigencia
     *
     * @param vigencia the value for pataPerro.tm_busqueda.vigencia
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public void setVigencia(Date vigencia) {
        this.vigencia = vigencia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_busqueda.des_parametro1
     *
     * @return the value of pataPerro.tm_busqueda.des_parametro1
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public String getDesParametro1() {
        return desParametro1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_busqueda.des_parametro1
     *
     * @param desParametro1 the value for pataPerro.tm_busqueda.des_parametro1
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public void setDesParametro1(String desParametro1) {
        this.desParametro1 = desParametro1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_busqueda.des_parametro2
     *
     * @return the value of pataPerro.tm_busqueda.des_parametro2
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public String getDesParametro2() {
        return desParametro2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_busqueda.des_parametro2
     *
     * @param desParametro2 the value for pataPerro.tm_busqueda.des_parametro2
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public void setDesParametro2(String desParametro2) {
        this.desParametro2 = desParametro2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_busqueda.num_parametro1
     *
     * @return the value of pataPerro.tm_busqueda.num_parametro1
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public Integer getNumParametro1() {
        return numParametro1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_busqueda.num_parametro1
     *
     * @param numParametro1 the value for pataPerro.tm_busqueda.num_parametro1
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public void setNumParametro1(Integer numParametro1) {
        this.numParametro1 = numParametro1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_busqueda.num_parametro2
     *
     * @return the value of pataPerro.tm_busqueda.num_parametro2
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public Integer getNumParametro2() {
        return numParametro2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_busqueda.num_parametro2
     *
     * @param numParametro2 the value for pataPerro.tm_busqueda.num_parametro2
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public void setNumParametro2(Integer numParametro2) {
        this.numParametro2 = numParametro2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_busqueda.date_parametro1
     *
     * @return the value of pataPerro.tm_busqueda.date_parametro1
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public Date getDateParametro1() {
        return dateParametro1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_busqueda.date_parametro1
     *
     * @param dateParametro1 the value for pataPerro.tm_busqueda.date_parametro1
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public void setDateParametro1(Date dateParametro1) {
        this.dateParametro1 = dateParametro1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_busqueda.date_parametro2
     *
     * @return the value of pataPerro.tm_busqueda.date_parametro2
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public Date getDateParametro2() {
        return dateParametro2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_busqueda.date_parametro2
     *
     * @param dateParametro2 the value for pataPerro.tm_busqueda.date_parametro2
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public void setDateParametro2(Date dateParametro2) {
        this.dateParametro2 = dateParametro2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_busqueda.nombrecompleto
     *
     * @return the value of pataPerro.tm_busqueda.nombrecompleto
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public String getNombrecompleto() {
        return nombrecompleto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_busqueda.nombrecompleto
     *
     * @param nombrecompleto the value for pataPerro.tm_busqueda.nombrecompleto
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public void setNombrecompleto(String nombrecompleto) {
        this.nombrecompleto = nombrecompleto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_busqueda.fotopublicacion
     *
     * @return the value of pataPerro.tm_busqueda.fotopublicacion
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public String getFotopublicacion() {
        return fotopublicacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_busqueda.fotopublicacion
     *
     * @param fotopublicacion the value for pataPerro.tm_busqueda.fotopublicacion
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public void setFotopublicacion(String fotopublicacion) {
        this.fotopublicacion = fotopublicacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_busqueda.desparametro3
     *
     * @return the value of pataPerro.tm_busqueda.desparametro3
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public String getDesparametro3() {
        return desparametro3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_busqueda.desparametro3
     *
     * @param desparametro3 the value for pataPerro.tm_busqueda.desparametro3
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public void setDesparametro3(String desparametro3) {
        this.desparametro3 = desparametro3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_busqueda.desparametro4
     *
     * @return the value of pataPerro.tm_busqueda.desparametro4
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public String getDesparametro4() {
        return desparametro4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_busqueda.desparametro4
     *
     * @param desparametro4 the value for pataPerro.tm_busqueda.desparametro4
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public void setDesparametro4(String desparametro4) {
        this.desparametro4 = desparametro4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_busqueda.monto_recompensa
     *
     * @return the value of pataPerro.tm_busqueda.monto_recompensa
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public String getMontoRecompensa() {
        return montoRecompensa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_busqueda.monto_recompensa
     *
     * @param montoRecompensa the value for pataPerro.tm_busqueda.monto_recompensa
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public void setMontoRecompensa(String montoRecompensa) {
        this.montoRecompensa = montoRecompensa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_busqueda
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Busqueda other = (Busqueda) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getMascotaId() == null ? other.getMascotaId() == null : this.getMascotaId().equals(other.getMascotaId()))
            && (this.getFechaPerdida() == null ? other.getFechaPerdida() == null : this.getFechaPerdida().equals(other.getFechaPerdida()))
            && (this.getUbicacionCatastro() == null ? other.getUbicacionCatastro() == null : this.getUbicacionCatastro().equals(other.getUbicacionCatastro()))
            && (this.getDescripcion() == null ? other.getDescripcion() == null : this.getDescripcion().equals(other.getDescripcion()))
            && (this.getDistrito() == null ? other.getDistrito() == null : this.getDistrito().equals(other.getDistrito()))
            && (this.getEstadoBusqueda() == null ? other.getEstadoBusqueda() == null : this.getEstadoBusqueda().equals(other.getEstadoBusqueda()))
            && (this.getEstado() == null ? other.getEstado() == null : this.getEstado().equals(other.getEstado()))
            && (this.getIndRecompensa() == null ? other.getIndRecompensa() == null : this.getIndRecompensa().equals(other.getIndRecompensa()))
            && (this.getComentarioAdicional() == null ? other.getComentarioAdicional() == null : this.getComentarioAdicional().equals(other.getComentarioAdicional()))
            && (this.getUsuarioRegistro() == null ? other.getUsuarioRegistro() == null : this.getUsuarioRegistro().equals(other.getUsuarioRegistro()))
            && (this.getFechaRegistro() == null ? other.getFechaRegistro() == null : this.getFechaRegistro().equals(other.getFechaRegistro()))
            && (this.getUsuarioModifico() == null ? other.getUsuarioModifico() == null : this.getUsuarioModifico().equals(other.getUsuarioModifico()))
            && (this.getFechaModifico() == null ? other.getFechaModifico() == null : this.getFechaModifico().equals(other.getFechaModifico()))
            && (this.getIndMascotaPropia() == null ? other.getIndMascotaPropia() == null : this.getIndMascotaPropia().equals(other.getIndMascotaPropia()))
            && (this.getFotoQr() == null ? other.getFotoQr() == null : this.getFotoQr().equals(other.getFotoQr()))
            && (this.getTelefono() == null ? other.getTelefono() == null : this.getTelefono().equals(other.getTelefono()))
            && (this.getIndvigencia() == null ? other.getIndvigencia() == null : this.getIndvigencia().equals(other.getIndvigencia()))
            && (this.getVigencia() == null ? other.getVigencia() == null : this.getVigencia().equals(other.getVigencia()))
            && (this.getDesParametro1() == null ? other.getDesParametro1() == null : this.getDesParametro1().equals(other.getDesParametro1()))
            && (this.getDesParametro2() == null ? other.getDesParametro2() == null : this.getDesParametro2().equals(other.getDesParametro2()))
            && (this.getNumParametro1() == null ? other.getNumParametro1() == null : this.getNumParametro1().equals(other.getNumParametro1()))
            && (this.getNumParametro2() == null ? other.getNumParametro2() == null : this.getNumParametro2().equals(other.getNumParametro2()))
            && (this.getDateParametro1() == null ? other.getDateParametro1() == null : this.getDateParametro1().equals(other.getDateParametro1()))
            && (this.getDateParametro2() == null ? other.getDateParametro2() == null : this.getDateParametro2().equals(other.getDateParametro2()))
            && (this.getNombrecompleto() == null ? other.getNombrecompleto() == null : this.getNombrecompleto().equals(other.getNombrecompleto()))
            && (this.getFotopublicacion() == null ? other.getFotopublicacion() == null : this.getFotopublicacion().equals(other.getFotopublicacion()))
            && (this.getDesparametro3() == null ? other.getDesparametro3() == null : this.getDesparametro3().equals(other.getDesparametro3()))
            && (this.getDesparametro4() == null ? other.getDesparametro4() == null : this.getDesparametro4().equals(other.getDesparametro4()))
            && (this.getMontoRecompensa() == null ? other.getMontoRecompensa() == null : this.getMontoRecompensa().equals(other.getMontoRecompensa()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_busqueda
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getMascotaId() == null) ? 0 : getMascotaId().hashCode());
        result = prime * result + ((getFechaPerdida() == null) ? 0 : getFechaPerdida().hashCode());
        result = prime * result + ((getUbicacionCatastro() == null) ? 0 : getUbicacionCatastro().hashCode());
        result = prime * result + ((getDescripcion() == null) ? 0 : getDescripcion().hashCode());
        result = prime * result + ((getDistrito() == null) ? 0 : getDistrito().hashCode());
        result = prime * result + ((getEstadoBusqueda() == null) ? 0 : getEstadoBusqueda().hashCode());
        result = prime * result + ((getEstado() == null) ? 0 : getEstado().hashCode());
        result = prime * result + ((getIndRecompensa() == null) ? 0 : getIndRecompensa().hashCode());
        result = prime * result + ((getComentarioAdicional() == null) ? 0 : getComentarioAdicional().hashCode());
        result = prime * result + ((getUsuarioRegistro() == null) ? 0 : getUsuarioRegistro().hashCode());
        result = prime * result + ((getFechaRegistro() == null) ? 0 : getFechaRegistro().hashCode());
        result = prime * result + ((getUsuarioModifico() == null) ? 0 : getUsuarioModifico().hashCode());
        result = prime * result + ((getFechaModifico() == null) ? 0 : getFechaModifico().hashCode());
        result = prime * result + ((getIndMascotaPropia() == null) ? 0 : getIndMascotaPropia().hashCode());
        result = prime * result + ((getFotoQr() == null) ? 0 : getFotoQr().hashCode());
        result = prime * result + ((getTelefono() == null) ? 0 : getTelefono().hashCode());
        result = prime * result + ((getIndvigencia() == null) ? 0 : getIndvigencia().hashCode());
        result = prime * result + ((getVigencia() == null) ? 0 : getVigencia().hashCode());
        result = prime * result + ((getDesParametro1() == null) ? 0 : getDesParametro1().hashCode());
        result = prime * result + ((getDesParametro2() == null) ? 0 : getDesParametro2().hashCode());
        result = prime * result + ((getNumParametro1() == null) ? 0 : getNumParametro1().hashCode());
        result = prime * result + ((getNumParametro2() == null) ? 0 : getNumParametro2().hashCode());
        result = prime * result + ((getDateParametro1() == null) ? 0 : getDateParametro1().hashCode());
        result = prime * result + ((getDateParametro2() == null) ? 0 : getDateParametro2().hashCode());
        result = prime * result + ((getNombrecompleto() == null) ? 0 : getNombrecompleto().hashCode());
        result = prime * result + ((getFotopublicacion() == null) ? 0 : getFotopublicacion().hashCode());
        result = prime * result + ((getDesparametro3() == null) ? 0 : getDesparametro3().hashCode());
        result = prime * result + ((getDesparametro4() == null) ? 0 : getDesparametro4().hashCode());
        result = prime * result + ((getMontoRecompensa() == null) ? 0 : getMontoRecompensa().hashCode());
        return result;
    }
    
/** Atributos adicionales **/
    
    private Mascota mascota;
    
    private List<BusquedaFoto> busquedaMascotaFotos;

    private Persona persona;
    private String mascotaNombre;
    private Integer mascotaRaza;
    private Integer mascotaTamanio;
    private Integer mascotaGenero;
    private Integer mascotaColor;
    private String desDistrito;
    private MascotaFoto foto;
    private MultipartFile fileFoto;
    
	public List<BusquedaFoto> getBusquedaMascotaFotos() {
		return busquedaMascotaFotos;
	}

	public void setBusquedaMascotaFotos(List<BusquedaFoto> busquedaMascotaFotos) {
		this.busquedaMascotaFotos = busquedaMascotaFotos;
	}

	public Mascota getMascota() {
		return mascota;
	}

	public void setMascota(Mascota mascota) {
		this.mascota = mascota;
	}

	public String getMascotaNombre() {
		return mascotaNombre;
	}

	public void setMascotaNombre(String mascotaNombre) {
		this.mascotaNombre = mascotaNombre;
	}

	public Integer getMascotaRaza() {
		return mascotaRaza;
	}

	public void setMascotaRaza(Integer mascotaRaza) {
		this.mascotaRaza = mascotaRaza;
	}

	public Integer getMascotaTamanio() {
		return mascotaTamanio;
	}

	public void setMascotaTamanio(Integer mascotaTamanio) {
		this.mascotaTamanio = mascotaTamanio;
	}

	public Integer getMascotaGenero() {
		return mascotaGenero;
	}

	public void setMascotaGenero(Integer mascotaGenero) {
		this.mascotaGenero = mascotaGenero;
	}

	public Integer getMascotaColor() {
		return mascotaColor;
	}

	public void setMascotaColor(Integer mascotaColor) {
		this.mascotaColor = mascotaColor;
	}

	public MascotaFoto getFoto() {
		return foto;
	}

	public void setFoto(MascotaFoto foto) {
		this.foto = foto;
	}

	public MultipartFile getFileFoto() {
		return fileFoto;
	}

	public void setFileFoto(MultipartFile fileFoto) {
		this.fileFoto = fileFoto;
	}

	public String getDesDistrito() {
		return desDistrito;
	}

	public void setDesDistrito(String desDistrito) {
		this.desDistrito = desDistrito;
	}

	public Persona getPersona() {
		return persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}
}