package pe.com.pdp.domain.postgres;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.web.multipart.MultipartFile;

import pe.com.pdp.domain.model.GridModel;


public class Encontrado extends GridModel implements Serializable {
	private static final long serialVersionUID = 1L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_encontrado.id
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_encontrado.fecha_encontrado
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    @DateTimeFormat(pattern="dd/MM/yyyy")
    private Date fechaEncontrado;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_encontrado.estado_encontrado
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    private Integer estadoEncontrado;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_encontrado.ubicacion_catastro
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    private String ubicacionCatastro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_encontrado.descripcion
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    private String descripcion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_encontrado.usuario_encontro
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    private Integer usuarioEncontro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_encontrado.email
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_encontrado.distrito
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    private Integer distrito;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_encontrado.comentario
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    private String comentario;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_encontrado.tipo_encuentro
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    private Integer tipoEncuentro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_encontrado.estado
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    private Integer estado;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_encontrado.usuario_registro
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    private String usuarioRegistro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_encontrado.fecha_registro
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    private Date fechaRegistro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_encontrado.usuario_modifico
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    private String usuarioModifico;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_encontrado.fecha_modifico
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    private Date fechaModifico;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_encontrado.nombre_completo
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    private String nombreCompleto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_encontrado.mascota_id
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    private Integer mascotaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_encontrado.foto_qr
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    private String fotoQr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_encontrado.indVigencia
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    private Integer indvigencia;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_encontrado.vigencia
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    private Date vigencia;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_encontrado.des_parametro1
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    private String desParametro1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_encontrado.des_parametro2
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    private String desParametro2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_encontrado.num_parametro1
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    private Integer numParametro1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_encontrado.num_parametro2
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    private Integer numParametro2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_encontrado.date_parametro1
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    private Date dateParametro1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_encontrado.date_parametro2
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    private Date dateParametro2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_encontrado.nombrecompleto
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    private String nombrecompleto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_encontrado.fotopublicacion
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    private String fotopublicacion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_encontrado.desparametro3
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    private String desparametro3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_encontrado.desparametro4
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    private String desparametro4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_encontrado.telefono
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    private String telefono;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_encontrado.id
     *
     * @return the value of pataPerro.tm_encontrado.id
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_encontrado.id
     *
     * @param id the value for pataPerro.tm_encontrado.id
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_encontrado.fecha_encontrado
     *
     * @return the value of pataPerro.tm_encontrado.fecha_encontrado
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public Date getFechaEncontrado() {
        return fechaEncontrado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_encontrado.fecha_encontrado
     *
     * @param fechaEncontrado the value for pataPerro.tm_encontrado.fecha_encontrado
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public void setFechaEncontrado(Date fechaEncontrado) {
        this.fechaEncontrado = fechaEncontrado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_encontrado.estado_encontrado
     *
     * @return the value of pataPerro.tm_encontrado.estado_encontrado
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public Integer getEstadoEncontrado() {
        return estadoEncontrado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_encontrado.estado_encontrado
     *
     * @param estadoEncontrado the value for pataPerro.tm_encontrado.estado_encontrado
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public void setEstadoEncontrado(Integer estadoEncontrado) {
        this.estadoEncontrado = estadoEncontrado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_encontrado.ubicacion_catastro
     *
     * @return the value of pataPerro.tm_encontrado.ubicacion_catastro
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public String getUbicacionCatastro() {
        return ubicacionCatastro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_encontrado.ubicacion_catastro
     *
     * @param ubicacionCatastro the value for pataPerro.tm_encontrado.ubicacion_catastro
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public void setUbicacionCatastro(String ubicacionCatastro) {
        this.ubicacionCatastro = ubicacionCatastro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_encontrado.descripcion
     *
     * @return the value of pataPerro.tm_encontrado.descripcion
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public String getDescripcion() {
        return descripcion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_encontrado.descripcion
     *
     * @param descripcion the value for pataPerro.tm_encontrado.descripcion
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_encontrado.usuario_encontro
     *
     * @return the value of pataPerro.tm_encontrado.usuario_encontro
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public Integer getUsuarioEncontro() {
        return usuarioEncontro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_encontrado.usuario_encontro
     *
     * @param usuarioEncontro the value for pataPerro.tm_encontrado.usuario_encontro
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public void setUsuarioEncontro(Integer usuarioEncontro) {
        this.usuarioEncontro = usuarioEncontro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_encontrado.email
     *
     * @return the value of pataPerro.tm_encontrado.email
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_encontrado.email
     *
     * @param email the value for pataPerro.tm_encontrado.email
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_encontrado.distrito
     *
     * @return the value of pataPerro.tm_encontrado.distrito
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public Integer getDistrito() {
        return distrito;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_encontrado.distrito
     *
     * @param distrito the value for pataPerro.tm_encontrado.distrito
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public void setDistrito(Integer distrito) {
        this.distrito = distrito;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_encontrado.comentario
     *
     * @return the value of pataPerro.tm_encontrado.comentario
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public String getComentario() {
        return comentario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_encontrado.comentario
     *
     * @param comentario the value for pataPerro.tm_encontrado.comentario
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_encontrado.tipo_encuentro
     *
     * @return the value of pataPerro.tm_encontrado.tipo_encuentro
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public Integer getTipoEncuentro() {
        return tipoEncuentro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_encontrado.tipo_encuentro
     *
     * @param tipoEncuentro the value for pataPerro.tm_encontrado.tipo_encuentro
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public void setTipoEncuentro(Integer tipoEncuentro) {
        this.tipoEncuentro = tipoEncuentro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_encontrado.estado
     *
     * @return the value of pataPerro.tm_encontrado.estado
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public Integer getEstado() {
        return estado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_encontrado.estado
     *
     * @param estado the value for pataPerro.tm_encontrado.estado
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public void setEstado(Integer estado) {
        this.estado = estado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_encontrado.usuario_registro
     *
     * @return the value of pataPerro.tm_encontrado.usuario_registro
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public String getUsuarioRegistro() {
        return usuarioRegistro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_encontrado.usuario_registro
     *
     * @param usuarioRegistro the value for pataPerro.tm_encontrado.usuario_registro
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public void setUsuarioRegistro(String usuarioRegistro) {
        this.usuarioRegistro = usuarioRegistro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_encontrado.fecha_registro
     *
     * @return the value of pataPerro.tm_encontrado.fecha_registro
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public Date getFechaRegistro() {
        return fechaRegistro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_encontrado.fecha_registro
     *
     * @param fechaRegistro the value for pataPerro.tm_encontrado.fecha_registro
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_encontrado.usuario_modifico
     *
     * @return the value of pataPerro.tm_encontrado.usuario_modifico
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public String getUsuarioModifico() {
        return usuarioModifico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_encontrado.usuario_modifico
     *
     * @param usuarioModifico the value for pataPerro.tm_encontrado.usuario_modifico
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public void setUsuarioModifico(String usuarioModifico) {
        this.usuarioModifico = usuarioModifico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_encontrado.fecha_modifico
     *
     * @return the value of pataPerro.tm_encontrado.fecha_modifico
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public Date getFechaModifico() {
        return fechaModifico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_encontrado.fecha_modifico
     *
     * @param fechaModifico the value for pataPerro.tm_encontrado.fecha_modifico
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public void setFechaModifico(Date fechaModifico) {
        this.fechaModifico = fechaModifico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_encontrado.nombre_completo
     *
     * @return the value of pataPerro.tm_encontrado.nombre_completo
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public String getNombreCompleto() {
        return nombreCompleto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_encontrado.nombre_completo
     *
     * @param nombreCompleto the value for pataPerro.tm_encontrado.nombre_completo
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public void setNombreCompleto(String nombreCompleto) {
        this.nombreCompleto = nombreCompleto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_encontrado.mascota_id
     *
     * @return the value of pataPerro.tm_encontrado.mascota_id
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public Integer getMascotaId() {
        return mascotaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_encontrado.mascota_id
     *
     * @param mascotaId the value for pataPerro.tm_encontrado.mascota_id
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public void setMascotaId(Integer mascotaId) {
        this.mascotaId = mascotaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_encontrado.foto_qr
     *
     * @return the value of pataPerro.tm_encontrado.foto_qr
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public String getFotoQr() {
        return fotoQr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_encontrado.foto_qr
     *
     * @param fotoQr the value for pataPerro.tm_encontrado.foto_qr
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public void setFotoQr(String fotoQr) {
        this.fotoQr = fotoQr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_encontrado.indVigencia
     *
     * @return the value of pataPerro.tm_encontrado.indVigencia
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public Integer getIndvigencia() {
        return indvigencia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_encontrado.indVigencia
     *
     * @param indvigencia the value for pataPerro.tm_encontrado.indVigencia
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public void setIndvigencia(Integer indvigencia) {
        this.indvigencia = indvigencia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_encontrado.vigencia
     *
     * @return the value of pataPerro.tm_encontrado.vigencia
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public Date getVigencia() {
        return vigencia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_encontrado.vigencia
     *
     * @param vigencia the value for pataPerro.tm_encontrado.vigencia
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public void setVigencia(Date vigencia) {
        this.vigencia = vigencia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_encontrado.des_parametro1
     *
     * @return the value of pataPerro.tm_encontrado.des_parametro1
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public String getDesParametro1() {
        return desParametro1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_encontrado.des_parametro1
     *
     * @param desParametro1 the value for pataPerro.tm_encontrado.des_parametro1
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public void setDesParametro1(String desParametro1) {
        this.desParametro1 = desParametro1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_encontrado.des_parametro2
     *
     * @return the value of pataPerro.tm_encontrado.des_parametro2
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public String getDesParametro2() {
        return desParametro2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_encontrado.des_parametro2
     *
     * @param desParametro2 the value for pataPerro.tm_encontrado.des_parametro2
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public void setDesParametro2(String desParametro2) {
        this.desParametro2 = desParametro2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_encontrado.num_parametro1
     *
     * @return the value of pataPerro.tm_encontrado.num_parametro1
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public Integer getNumParametro1() {
        return numParametro1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_encontrado.num_parametro1
     *
     * @param numParametro1 the value for pataPerro.tm_encontrado.num_parametro1
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public void setNumParametro1(Integer numParametro1) {
        this.numParametro1 = numParametro1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_encontrado.num_parametro2
     *
     * @return the value of pataPerro.tm_encontrado.num_parametro2
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public Integer getNumParametro2() {
        return numParametro2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_encontrado.num_parametro2
     *
     * @param numParametro2 the value for pataPerro.tm_encontrado.num_parametro2
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public void setNumParametro2(Integer numParametro2) {
        this.numParametro2 = numParametro2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_encontrado.date_parametro1
     *
     * @return the value of pataPerro.tm_encontrado.date_parametro1
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public Date getDateParametro1() {
        return dateParametro1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_encontrado.date_parametro1
     *
     * @param dateParametro1 the value for pataPerro.tm_encontrado.date_parametro1
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public void setDateParametro1(Date dateParametro1) {
        this.dateParametro1 = dateParametro1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_encontrado.date_parametro2
     *
     * @return the value of pataPerro.tm_encontrado.date_parametro2
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public Date getDateParametro2() {
        return dateParametro2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_encontrado.date_parametro2
     *
     * @param dateParametro2 the value for pataPerro.tm_encontrado.date_parametro2
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public void setDateParametro2(Date dateParametro2) {
        this.dateParametro2 = dateParametro2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_encontrado.nombrecompleto
     *
     * @return the value of pataPerro.tm_encontrado.nombrecompleto
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public String getNombrecompleto() {
        return nombrecompleto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_encontrado.nombrecompleto
     *
     * @param nombrecompleto the value for pataPerro.tm_encontrado.nombrecompleto
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public void setNombrecompleto(String nombrecompleto) {
        this.nombrecompleto = nombrecompleto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_encontrado.fotopublicacion
     *
     * @return the value of pataPerro.tm_encontrado.fotopublicacion
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public String getFotopublicacion() {
        return fotopublicacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_encontrado.fotopublicacion
     *
     * @param fotopublicacion the value for pataPerro.tm_encontrado.fotopublicacion
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public void setFotopublicacion(String fotopublicacion) {
        this.fotopublicacion = fotopublicacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_encontrado.desparametro3
     *
     * @return the value of pataPerro.tm_encontrado.desparametro3
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public String getDesparametro3() {
        return desparametro3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_encontrado.desparametro3
     *
     * @param desparametro3 the value for pataPerro.tm_encontrado.desparametro3
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public void setDesparametro3(String desparametro3) {
        this.desparametro3 = desparametro3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_encontrado.desparametro4
     *
     * @return the value of pataPerro.tm_encontrado.desparametro4
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public String getDesparametro4() {
        return desparametro4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_encontrado.desparametro4
     *
     * @param desparametro4 the value for pataPerro.tm_encontrado.desparametro4
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public void setDesparametro4(String desparametro4) {
        this.desparametro4 = desparametro4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_encontrado.telefono
     *
     * @return the value of pataPerro.tm_encontrado.telefono
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public String getTelefono() {
        return telefono;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_encontrado.telefono
     *
     * @param telefono the value for pataPerro.tm_encontrado.telefono
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_encontrado
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Encontrado other = (Encontrado) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getFechaEncontrado() == null ? other.getFechaEncontrado() == null : this.getFechaEncontrado().equals(other.getFechaEncontrado()))
            && (this.getEstadoEncontrado() == null ? other.getEstadoEncontrado() == null : this.getEstadoEncontrado().equals(other.getEstadoEncontrado()))
            && (this.getUbicacionCatastro() == null ? other.getUbicacionCatastro() == null : this.getUbicacionCatastro().equals(other.getUbicacionCatastro()))
            && (this.getDescripcion() == null ? other.getDescripcion() == null : this.getDescripcion().equals(other.getDescripcion()))
            && (this.getUsuarioEncontro() == null ? other.getUsuarioEncontro() == null : this.getUsuarioEncontro().equals(other.getUsuarioEncontro()))
            && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
            && (this.getDistrito() == null ? other.getDistrito() == null : this.getDistrito().equals(other.getDistrito()))
            && (this.getComentario() == null ? other.getComentario() == null : this.getComentario().equals(other.getComentario()))
            && (this.getTipoEncuentro() == null ? other.getTipoEncuentro() == null : this.getTipoEncuentro().equals(other.getTipoEncuentro()))
            && (this.getEstado() == null ? other.getEstado() == null : this.getEstado().equals(other.getEstado()))
            && (this.getUsuarioRegistro() == null ? other.getUsuarioRegistro() == null : this.getUsuarioRegistro().equals(other.getUsuarioRegistro()))
            && (this.getFechaRegistro() == null ? other.getFechaRegistro() == null : this.getFechaRegistro().equals(other.getFechaRegistro()))
            && (this.getUsuarioModifico() == null ? other.getUsuarioModifico() == null : this.getUsuarioModifico().equals(other.getUsuarioModifico()))
            && (this.getFechaModifico() == null ? other.getFechaModifico() == null : this.getFechaModifico().equals(other.getFechaModifico()))
            && (this.getNombreCompleto() == null ? other.getNombreCompleto() == null : this.getNombreCompleto().equals(other.getNombreCompleto()))
            && (this.getMascotaId() == null ? other.getMascotaId() == null : this.getMascotaId().equals(other.getMascotaId()))
            && (this.getFotoQr() == null ? other.getFotoQr() == null : this.getFotoQr().equals(other.getFotoQr()))
            && (this.getIndvigencia() == null ? other.getIndvigencia() == null : this.getIndvigencia().equals(other.getIndvigencia()))
            && (this.getVigencia() == null ? other.getVigencia() == null : this.getVigencia().equals(other.getVigencia()))
            && (this.getDesParametro1() == null ? other.getDesParametro1() == null : this.getDesParametro1().equals(other.getDesParametro1()))
            && (this.getDesParametro2() == null ? other.getDesParametro2() == null : this.getDesParametro2().equals(other.getDesParametro2()))
            && (this.getNumParametro1() == null ? other.getNumParametro1() == null : this.getNumParametro1().equals(other.getNumParametro1()))
            && (this.getNumParametro2() == null ? other.getNumParametro2() == null : this.getNumParametro2().equals(other.getNumParametro2()))
            && (this.getDateParametro1() == null ? other.getDateParametro1() == null : this.getDateParametro1().equals(other.getDateParametro1()))
            && (this.getDateParametro2() == null ? other.getDateParametro2() == null : this.getDateParametro2().equals(other.getDateParametro2()))
            && (this.getNombrecompleto() == null ? other.getNombrecompleto() == null : this.getNombrecompleto().equals(other.getNombrecompleto()))
            && (this.getFotopublicacion() == null ? other.getFotopublicacion() == null : this.getFotopublicacion().equals(other.getFotopublicacion()))
            && (this.getDesparametro3() == null ? other.getDesparametro3() == null : this.getDesparametro3().equals(other.getDesparametro3()))
            && (this.getDesparametro4() == null ? other.getDesparametro4() == null : this.getDesparametro4().equals(other.getDesparametro4()))
            && (this.getTelefono() == null ? other.getTelefono() == null : this.getTelefono().equals(other.getTelefono()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_encontrado
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getFechaEncontrado() == null) ? 0 : getFechaEncontrado().hashCode());
        result = prime * result + ((getEstadoEncontrado() == null) ? 0 : getEstadoEncontrado().hashCode());
        result = prime * result + ((getUbicacionCatastro() == null) ? 0 : getUbicacionCatastro().hashCode());
        result = prime * result + ((getDescripcion() == null) ? 0 : getDescripcion().hashCode());
        result = prime * result + ((getUsuarioEncontro() == null) ? 0 : getUsuarioEncontro().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        result = prime * result + ((getDistrito() == null) ? 0 : getDistrito().hashCode());
        result = prime * result + ((getComentario() == null) ? 0 : getComentario().hashCode());
        result = prime * result + ((getTipoEncuentro() == null) ? 0 : getTipoEncuentro().hashCode());
        result = prime * result + ((getEstado() == null) ? 0 : getEstado().hashCode());
        result = prime * result + ((getUsuarioRegistro() == null) ? 0 : getUsuarioRegistro().hashCode());
        result = prime * result + ((getFechaRegistro() == null) ? 0 : getFechaRegistro().hashCode());
        result = prime * result + ((getUsuarioModifico() == null) ? 0 : getUsuarioModifico().hashCode());
        result = prime * result + ((getFechaModifico() == null) ? 0 : getFechaModifico().hashCode());
        result = prime * result + ((getNombreCompleto() == null) ? 0 : getNombreCompleto().hashCode());
        result = prime * result + ((getMascotaId() == null) ? 0 : getMascotaId().hashCode());
        result = prime * result + ((getFotoQr() == null) ? 0 : getFotoQr().hashCode());
        result = prime * result + ((getIndvigencia() == null) ? 0 : getIndvigencia().hashCode());
        result = prime * result + ((getVigencia() == null) ? 0 : getVigencia().hashCode());
        result = prime * result + ((getDesParametro1() == null) ? 0 : getDesParametro1().hashCode());
        result = prime * result + ((getDesParametro2() == null) ? 0 : getDesParametro2().hashCode());
        result = prime * result + ((getNumParametro1() == null) ? 0 : getNumParametro1().hashCode());
        result = prime * result + ((getNumParametro2() == null) ? 0 : getNumParametro2().hashCode());
        result = prime * result + ((getDateParametro1() == null) ? 0 : getDateParametro1().hashCode());
        result = prime * result + ((getDateParametro2() == null) ? 0 : getDateParametro2().hashCode());
        result = prime * result + ((getNombrecompleto() == null) ? 0 : getNombrecompleto().hashCode());
        result = prime * result + ((getFotopublicacion() == null) ? 0 : getFotopublicacion().hashCode());
        result = prime * result + ((getDesparametro3() == null) ? 0 : getDesparametro3().hashCode());
        result = prime * result + ((getDesparametro4() == null) ? 0 : getDesparametro4().hashCode());
        result = prime * result + ((getTelefono() == null) ? 0 : getTelefono().hashCode());
        return result;
    }
    
    /** Atributos adicionales **/
    private Mascota mascota;
    private List<EncontradoFoto> encontradoMascotaFotos;
    private String mascotaNombre;
    private Integer mascotaRaza;
    private Integer mascotaTamanio;
    private Integer mascotaGenero;
    private Integer mascotaColor;
    private String desDistrito;
    private Persona  persona;
    private MascotaFoto foto;
    private MultipartFile fileFoto;
    
	public Persona getPersona() {
		return persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	public Mascota getMascota() {
		return mascota;
	}

	public void setMascota(Mascota mascota) {
		this.mascota = mascota;
	}

	public List<EncontradoFoto> getEncontradoMascotaFotos() {
		return encontradoMascotaFotos;
	}

	public void setEncontradoMascotaFotos(List<EncontradoFoto> encontradoMascotaFotos) {
		this.encontradoMascotaFotos = encontradoMascotaFotos;
	}

	public String getMascotaNombre() {
		return mascotaNombre;
	}

	public void setMascotaNombre(String mascotaNombre) {
		this.mascotaNombre = mascotaNombre;
	}

	public Integer getMascotaRaza() {
		return mascotaRaza;
	}

	public void setMascotaRaza(Integer mascotaRaza) {
		this.mascotaRaza = mascotaRaza;
	}

	public Integer getMascotaTamanio() {
		return mascotaTamanio;
	}

	public void setMascotaTamanio(Integer mascotaTamanio) {
		this.mascotaTamanio = mascotaTamanio;
	}

	public Integer getMascotaGenero() {
		return mascotaGenero;
	}

	public void setMascotaGenero(Integer mascotaGenero) {
		this.mascotaGenero = mascotaGenero;
	}

	public Integer getMascotaColor() {
		return mascotaColor;
	}

	public void setMascotaColor(Integer mascotaColor) {
		this.mascotaColor = mascotaColor;
	}

	public String getDesDistrito() {
		return desDistrito;
	}

	public void setDesDistrito(String desDistrito) {
		this.desDistrito = desDistrito;
	}

	public MascotaFoto getFoto() {
		return foto;
	}

	public void setFoto(MascotaFoto foto) {
		this.foto = foto;
	}

	public MultipartFile getFileFoto() {
		return fileFoto;
	}

	public void setFileFoto(MultipartFile fileFoto) {
		this.fileFoto = fileFoto;
	}	
    
}