package pe.com.pdp.domain.postgres;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MascotaCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pataPerro.tm_mascota
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pataPerro.tm_mascota
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pataPerro.tm_mascota
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_mascota
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public MascotaCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_mascota
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_mascota
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_mascota
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_mascota
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_mascota
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_mascota
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_mascota
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_mascota
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_mascota
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_mascota
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pataPerro.tm_mascota
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("\"id\" is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("\"id\" is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("\"id\" =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("\"id\" <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("\"id\" >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("\"id\" >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("\"id\" <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("\"id\" <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("\"id\" in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("\"id\" not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("\"id\" between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("\"id\" not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNombreIsNull() {
            addCriterion("\"nombre\" is null");
            return (Criteria) this;
        }

        public Criteria andNombreIsNotNull() {
            addCriterion("\"nombre\" is not null");
            return (Criteria) this;
        }

        public Criteria andNombreEqualTo(String value) {
            addCriterion("\"nombre\" =", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreNotEqualTo(String value) {
            addCriterion("\"nombre\" <>", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreGreaterThan(String value) {
            addCriterion("\"nombre\" >", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreGreaterThanOrEqualTo(String value) {
            addCriterion("\"nombre\" >=", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreLessThan(String value) {
            addCriterion("\"nombre\" <", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreLessThanOrEqualTo(String value) {
            addCriterion("\"nombre\" <=", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreLike(String value) {
            addCriterion("\"nombre\" like", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreNotLike(String value) {
            addCriterion("\"nombre\" not like", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreIn(List<String> values) {
            addCriterion("\"nombre\" in", values, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreNotIn(List<String> values) {
            addCriterion("\"nombre\" not in", values, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreBetween(String value1, String value2) {
            addCriterion("\"nombre\" between", value1, value2, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreNotBetween(String value1, String value2) {
            addCriterion("\"nombre\" not between", value1, value2, "nombre");
            return (Criteria) this;
        }

        public Criteria andGeneroIsNull() {
            addCriterion("\"genero\" is null");
            return (Criteria) this;
        }

        public Criteria andGeneroIsNotNull() {
            addCriterion("\"genero\" is not null");
            return (Criteria) this;
        }

        public Criteria andGeneroEqualTo(Integer value) {
            addCriterion("\"genero\" =", value, "genero");
            return (Criteria) this;
        }

        public Criteria andGeneroNotEqualTo(Integer value) {
            addCriterion("\"genero\" <>", value, "genero");
            return (Criteria) this;
        }

        public Criteria andGeneroGreaterThan(Integer value) {
            addCriterion("\"genero\" >", value, "genero");
            return (Criteria) this;
        }

        public Criteria andGeneroGreaterThanOrEqualTo(Integer value) {
            addCriterion("\"genero\" >=", value, "genero");
            return (Criteria) this;
        }

        public Criteria andGeneroLessThan(Integer value) {
            addCriterion("\"genero\" <", value, "genero");
            return (Criteria) this;
        }

        public Criteria andGeneroLessThanOrEqualTo(Integer value) {
            addCriterion("\"genero\" <=", value, "genero");
            return (Criteria) this;
        }

        public Criteria andGeneroIn(List<Integer> values) {
            addCriterion("\"genero\" in", values, "genero");
            return (Criteria) this;
        }

        public Criteria andGeneroNotIn(List<Integer> values) {
            addCriterion("\"genero\" not in", values, "genero");
            return (Criteria) this;
        }

        public Criteria andGeneroBetween(Integer value1, Integer value2) {
            addCriterion("\"genero\" between", value1, value2, "genero");
            return (Criteria) this;
        }

        public Criteria andGeneroNotBetween(Integer value1, Integer value2) {
            addCriterion("\"genero\" not between", value1, value2, "genero");
            return (Criteria) this;
        }

        public Criteria andTamanioIsNull() {
            addCriterion("\"tamanio\" is null");
            return (Criteria) this;
        }

        public Criteria andTamanioIsNotNull() {
            addCriterion("\"tamanio\" is not null");
            return (Criteria) this;
        }

        public Criteria andTamanioEqualTo(Integer value) {
            addCriterion("\"tamanio\" =", value, "tamanio");
            return (Criteria) this;
        }

        public Criteria andTamanioNotEqualTo(Integer value) {
            addCriterion("\"tamanio\" <>", value, "tamanio");
            return (Criteria) this;
        }

        public Criteria andTamanioGreaterThan(Integer value) {
            addCriterion("\"tamanio\" >", value, "tamanio");
            return (Criteria) this;
        }

        public Criteria andTamanioGreaterThanOrEqualTo(Integer value) {
            addCriterion("\"tamanio\" >=", value, "tamanio");
            return (Criteria) this;
        }

        public Criteria andTamanioLessThan(Integer value) {
            addCriterion("\"tamanio\" <", value, "tamanio");
            return (Criteria) this;
        }

        public Criteria andTamanioLessThanOrEqualTo(Integer value) {
            addCriterion("\"tamanio\" <=", value, "tamanio");
            return (Criteria) this;
        }

        public Criteria andTamanioIn(List<Integer> values) {
            addCriterion("\"tamanio\" in", values, "tamanio");
            return (Criteria) this;
        }

        public Criteria andTamanioNotIn(List<Integer> values) {
            addCriterion("\"tamanio\" not in", values, "tamanio");
            return (Criteria) this;
        }

        public Criteria andTamanioBetween(Integer value1, Integer value2) {
            addCriterion("\"tamanio\" between", value1, value2, "tamanio");
            return (Criteria) this;
        }

        public Criteria andTamanioNotBetween(Integer value1, Integer value2) {
            addCriterion("\"tamanio\" not between", value1, value2, "tamanio");
            return (Criteria) this;
        }

        public Criteria andRazaIsNull() {
            addCriterion("\"raza\" is null");
            return (Criteria) this;
        }

        public Criteria andRazaIsNotNull() {
            addCriterion("\"raza\" is not null");
            return (Criteria) this;
        }

        public Criteria andRazaEqualTo(Integer value) {
            addCriterion("\"raza\" =", value, "raza");
            return (Criteria) this;
        }

        public Criteria andRazaNotEqualTo(Integer value) {
            addCriterion("\"raza\" <>", value, "raza");
            return (Criteria) this;
        }

        public Criteria andRazaGreaterThan(Integer value) {
            addCriterion("\"raza\" >", value, "raza");
            return (Criteria) this;
        }

        public Criteria andRazaGreaterThanOrEqualTo(Integer value) {
            addCriterion("\"raza\" >=", value, "raza");
            return (Criteria) this;
        }

        public Criteria andRazaLessThan(Integer value) {
            addCriterion("\"raza\" <", value, "raza");
            return (Criteria) this;
        }

        public Criteria andRazaLessThanOrEqualTo(Integer value) {
            addCriterion("\"raza\" <=", value, "raza");
            return (Criteria) this;
        }

        public Criteria andRazaIn(List<Integer> values) {
            addCriterion("\"raza\" in", values, "raza");
            return (Criteria) this;
        }

        public Criteria andRazaNotIn(List<Integer> values) {
            addCriterion("\"raza\" not in", values, "raza");
            return (Criteria) this;
        }

        public Criteria andRazaBetween(Integer value1, Integer value2) {
            addCriterion("\"raza\" between", value1, value2, "raza");
            return (Criteria) this;
        }

        public Criteria andRazaNotBetween(Integer value1, Integer value2) {
            addCriterion("\"raza\" not between", value1, value2, "raza");
            return (Criteria) this;
        }

        public Criteria andDistritoIsNull() {
            addCriterion("\"distrito\" is null");
            return (Criteria) this;
        }

        public Criteria andDistritoIsNotNull() {
            addCriterion("\"distrito\" is not null");
            return (Criteria) this;
        }

        public Criteria andDistritoEqualTo(Integer value) {
            addCriterion("\"distrito\" =", value, "distrito");
            return (Criteria) this;
        }

        public Criteria andDistritoNotEqualTo(Integer value) {
            addCriterion("\"distrito\" <>", value, "distrito");
            return (Criteria) this;
        }

        public Criteria andDistritoGreaterThan(Integer value) {
            addCriterion("\"distrito\" >", value, "distrito");
            return (Criteria) this;
        }

        public Criteria andDistritoGreaterThanOrEqualTo(Integer value) {
            addCriterion("\"distrito\" >=", value, "distrito");
            return (Criteria) this;
        }

        public Criteria andDistritoLessThan(Integer value) {
            addCriterion("\"distrito\" <", value, "distrito");
            return (Criteria) this;
        }

        public Criteria andDistritoLessThanOrEqualTo(Integer value) {
            addCriterion("\"distrito\" <=", value, "distrito");
            return (Criteria) this;
        }

        public Criteria andDistritoIn(List<Integer> values) {
            addCriterion("\"distrito\" in", values, "distrito");
            return (Criteria) this;
        }

        public Criteria andDistritoNotIn(List<Integer> values) {
            addCriterion("\"distrito\" not in", values, "distrito");
            return (Criteria) this;
        }

        public Criteria andDistritoBetween(Integer value1, Integer value2) {
            addCriterion("\"distrito\" between", value1, value2, "distrito");
            return (Criteria) this;
        }

        public Criteria andDistritoNotBetween(Integer value1, Integer value2) {
            addCriterion("\"distrito\" not between", value1, value2, "distrito");
            return (Criteria) this;
        }

        public Criteria andCaracteristicaIsNull() {
            addCriterion("\"caracteristica\" is null");
            return (Criteria) this;
        }

        public Criteria andCaracteristicaIsNotNull() {
            addCriterion("\"caracteristica\" is not null");
            return (Criteria) this;
        }

        public Criteria andCaracteristicaEqualTo(String value) {
            addCriterion("\"caracteristica\" =", value, "caracteristica");
            return (Criteria) this;
        }

        public Criteria andCaracteristicaNotEqualTo(String value) {
            addCriterion("\"caracteristica\" <>", value, "caracteristica");
            return (Criteria) this;
        }

        public Criteria andCaracteristicaGreaterThan(String value) {
            addCriterion("\"caracteristica\" >", value, "caracteristica");
            return (Criteria) this;
        }

        public Criteria andCaracteristicaGreaterThanOrEqualTo(String value) {
            addCriterion("\"caracteristica\" >=", value, "caracteristica");
            return (Criteria) this;
        }

        public Criteria andCaracteristicaLessThan(String value) {
            addCriterion("\"caracteristica\" <", value, "caracteristica");
            return (Criteria) this;
        }

        public Criteria andCaracteristicaLessThanOrEqualTo(String value) {
            addCriterion("\"caracteristica\" <=", value, "caracteristica");
            return (Criteria) this;
        }

        public Criteria andCaracteristicaLike(String value) {
            addCriterion("\"caracteristica\" like", value, "caracteristica");
            return (Criteria) this;
        }

        public Criteria andCaracteristicaNotLike(String value) {
            addCriterion("\"caracteristica\" not like", value, "caracteristica");
            return (Criteria) this;
        }

        public Criteria andCaracteristicaIn(List<String> values) {
            addCriterion("\"caracteristica\" in", values, "caracteristica");
            return (Criteria) this;
        }

        public Criteria andCaracteristicaNotIn(List<String> values) {
            addCriterion("\"caracteristica\" not in", values, "caracteristica");
            return (Criteria) this;
        }

        public Criteria andCaracteristicaBetween(String value1, String value2) {
            addCriterion("\"caracteristica\" between", value1, value2, "caracteristica");
            return (Criteria) this;
        }

        public Criteria andCaracteristicaNotBetween(String value1, String value2) {
            addCriterion("\"caracteristica\" not between", value1, value2, "caracteristica");
            return (Criteria) this;
        }

        public Criteria andIndRecibidoIsNull() {
            addCriterion("\"ind_recibido\" is null");
            return (Criteria) this;
        }

        public Criteria andIndRecibidoIsNotNull() {
            addCriterion("\"ind_recibido\" is not null");
            return (Criteria) this;
        }

        public Criteria andIndRecibidoEqualTo(Integer value) {
            addCriterion("\"ind_recibido\" =", value, "indRecibido");
            return (Criteria) this;
        }

        public Criteria andIndRecibidoNotEqualTo(Integer value) {
            addCriterion("\"ind_recibido\" <>", value, "indRecibido");
            return (Criteria) this;
        }

        public Criteria andIndRecibidoGreaterThan(Integer value) {
            addCriterion("\"ind_recibido\" >", value, "indRecibido");
            return (Criteria) this;
        }

        public Criteria andIndRecibidoGreaterThanOrEqualTo(Integer value) {
            addCriterion("\"ind_recibido\" >=", value, "indRecibido");
            return (Criteria) this;
        }

        public Criteria andIndRecibidoLessThan(Integer value) {
            addCriterion("\"ind_recibido\" <", value, "indRecibido");
            return (Criteria) this;
        }

        public Criteria andIndRecibidoLessThanOrEqualTo(Integer value) {
            addCriterion("\"ind_recibido\" <=", value, "indRecibido");
            return (Criteria) this;
        }

        public Criteria andIndRecibidoIn(List<Integer> values) {
            addCriterion("\"ind_recibido\" in", values, "indRecibido");
            return (Criteria) this;
        }

        public Criteria andIndRecibidoNotIn(List<Integer> values) {
            addCriterion("\"ind_recibido\" not in", values, "indRecibido");
            return (Criteria) this;
        }

        public Criteria andIndRecibidoBetween(Integer value1, Integer value2) {
            addCriterion("\"ind_recibido\" between", value1, value2, "indRecibido");
            return (Criteria) this;
        }

        public Criteria andIndRecibidoNotBetween(Integer value1, Integer value2) {
            addCriterion("\"ind_recibido\" not between", value1, value2, "indRecibido");
            return (Criteria) this;
        }

        public Criteria andDesComentarioIsNull() {
            addCriterion("\"des_comentario\" is null");
            return (Criteria) this;
        }

        public Criteria andDesComentarioIsNotNull() {
            addCriterion("\"des_comentario\" is not null");
            return (Criteria) this;
        }

        public Criteria andDesComentarioEqualTo(String value) {
            addCriterion("\"des_comentario\" =", value, "desComentario");
            return (Criteria) this;
        }

        public Criteria andDesComentarioNotEqualTo(String value) {
            addCriterion("\"des_comentario\" <>", value, "desComentario");
            return (Criteria) this;
        }

        public Criteria andDesComentarioGreaterThan(String value) {
            addCriterion("\"des_comentario\" >", value, "desComentario");
            return (Criteria) this;
        }

        public Criteria andDesComentarioGreaterThanOrEqualTo(String value) {
            addCriterion("\"des_comentario\" >=", value, "desComentario");
            return (Criteria) this;
        }

        public Criteria andDesComentarioLessThan(String value) {
            addCriterion("\"des_comentario\" <", value, "desComentario");
            return (Criteria) this;
        }

        public Criteria andDesComentarioLessThanOrEqualTo(String value) {
            addCriterion("\"des_comentario\" <=", value, "desComentario");
            return (Criteria) this;
        }

        public Criteria andDesComentarioLike(String value) {
            addCriterion("\"des_comentario\" like", value, "desComentario");
            return (Criteria) this;
        }

        public Criteria andDesComentarioNotLike(String value) {
            addCriterion("\"des_comentario\" not like", value, "desComentario");
            return (Criteria) this;
        }

        public Criteria andDesComentarioIn(List<String> values) {
            addCriterion("\"des_comentario\" in", values, "desComentario");
            return (Criteria) this;
        }

        public Criteria andDesComentarioNotIn(List<String> values) {
            addCriterion("\"des_comentario\" not in", values, "desComentario");
            return (Criteria) this;
        }

        public Criteria andDesComentarioBetween(String value1, String value2) {
            addCriterion("\"des_comentario\" between", value1, value2, "desComentario");
            return (Criteria) this;
        }

        public Criteria andDesComentarioNotBetween(String value1, String value2) {
            addCriterion("\"des_comentario\" not between", value1, value2, "desComentario");
            return (Criteria) this;
        }

        public Criteria andUbicacionCatastroIsNull() {
            addCriterion("\"ubicacion_catastro\" is null");
            return (Criteria) this;
        }

        public Criteria andUbicacionCatastroIsNotNull() {
            addCriterion("\"ubicacion_catastro\" is not null");
            return (Criteria) this;
        }

        public Criteria andUbicacionCatastroEqualTo(String value) {
            addCriterion("\"ubicacion_catastro\" =", value, "ubicacionCatastro");
            return (Criteria) this;
        }

        public Criteria andUbicacionCatastroNotEqualTo(String value) {
            addCriterion("\"ubicacion_catastro\" <>", value, "ubicacionCatastro");
            return (Criteria) this;
        }

        public Criteria andUbicacionCatastroGreaterThan(String value) {
            addCriterion("\"ubicacion_catastro\" >", value, "ubicacionCatastro");
            return (Criteria) this;
        }

        public Criteria andUbicacionCatastroGreaterThanOrEqualTo(String value) {
            addCriterion("\"ubicacion_catastro\" >=", value, "ubicacionCatastro");
            return (Criteria) this;
        }

        public Criteria andUbicacionCatastroLessThan(String value) {
            addCriterion("\"ubicacion_catastro\" <", value, "ubicacionCatastro");
            return (Criteria) this;
        }

        public Criteria andUbicacionCatastroLessThanOrEqualTo(String value) {
            addCriterion("\"ubicacion_catastro\" <=", value, "ubicacionCatastro");
            return (Criteria) this;
        }

        public Criteria andUbicacionCatastroLike(String value) {
            addCriterion("\"ubicacion_catastro\" like", value, "ubicacionCatastro");
            return (Criteria) this;
        }

        public Criteria andUbicacionCatastroNotLike(String value) {
            addCriterion("\"ubicacion_catastro\" not like", value, "ubicacionCatastro");
            return (Criteria) this;
        }

        public Criteria andUbicacionCatastroIn(List<String> values) {
            addCriterion("\"ubicacion_catastro\" in", values, "ubicacionCatastro");
            return (Criteria) this;
        }

        public Criteria andUbicacionCatastroNotIn(List<String> values) {
            addCriterion("\"ubicacion_catastro\" not in", values, "ubicacionCatastro");
            return (Criteria) this;
        }

        public Criteria andUbicacionCatastroBetween(String value1, String value2) {
            addCriterion("\"ubicacion_catastro\" between", value1, value2, "ubicacionCatastro");
            return (Criteria) this;
        }

        public Criteria andUbicacionCatastroNotBetween(String value1, String value2) {
            addCriterion("\"ubicacion_catastro\" not between", value1, value2, "ubicacionCatastro");
            return (Criteria) this;
        }

        public Criteria andUsuarioRegistroIsNull() {
            addCriterion("\"usuario_registro\" is null");
            return (Criteria) this;
        }

        public Criteria andUsuarioRegistroIsNotNull() {
            addCriterion("\"usuario_registro\" is not null");
            return (Criteria) this;
        }

        public Criteria andUsuarioRegistroEqualTo(String value) {
            addCriterion("\"usuario_registro\" =", value, "usuarioRegistro");
            return (Criteria) this;
        }

        public Criteria andUsuarioRegistroNotEqualTo(String value) {
            addCriterion("\"usuario_registro\" <>", value, "usuarioRegistro");
            return (Criteria) this;
        }

        public Criteria andUsuarioRegistroGreaterThan(String value) {
            addCriterion("\"usuario_registro\" >", value, "usuarioRegistro");
            return (Criteria) this;
        }

        public Criteria andUsuarioRegistroGreaterThanOrEqualTo(String value) {
            addCriterion("\"usuario_registro\" >=", value, "usuarioRegistro");
            return (Criteria) this;
        }

        public Criteria andUsuarioRegistroLessThan(String value) {
            addCriterion("\"usuario_registro\" <", value, "usuarioRegistro");
            return (Criteria) this;
        }

        public Criteria andUsuarioRegistroLessThanOrEqualTo(String value) {
            addCriterion("\"usuario_registro\" <=", value, "usuarioRegistro");
            return (Criteria) this;
        }

        public Criteria andUsuarioRegistroLike(String value) {
            addCriterion("\"usuario_registro\" like", value, "usuarioRegistro");
            return (Criteria) this;
        }

        public Criteria andUsuarioRegistroNotLike(String value) {
            addCriterion("\"usuario_registro\" not like", value, "usuarioRegistro");
            return (Criteria) this;
        }

        public Criteria andUsuarioRegistroIn(List<String> values) {
            addCriterion("\"usuario_registro\" in", values, "usuarioRegistro");
            return (Criteria) this;
        }

        public Criteria andUsuarioRegistroNotIn(List<String> values) {
            addCriterion("\"usuario_registro\" not in", values, "usuarioRegistro");
            return (Criteria) this;
        }

        public Criteria andUsuarioRegistroBetween(String value1, String value2) {
            addCriterion("\"usuario_registro\" between", value1, value2, "usuarioRegistro");
            return (Criteria) this;
        }

        public Criteria andUsuarioRegistroNotBetween(String value1, String value2) {
            addCriterion("\"usuario_registro\" not between", value1, value2, "usuarioRegistro");
            return (Criteria) this;
        }

        public Criteria andFechaRegistroIsNull() {
            addCriterion("\"fecha_registro\" is null");
            return (Criteria) this;
        }

        public Criteria andFechaRegistroIsNotNull() {
            addCriterion("\"fecha_registro\" is not null");
            return (Criteria) this;
        }

        public Criteria andFechaRegistroEqualTo(Date value) {
            addCriterion("\"fecha_registro\" =", value, "fechaRegistro");
            return (Criteria) this;
        }

        public Criteria andFechaRegistroNotEqualTo(Date value) {
            addCriterion("\"fecha_registro\" <>", value, "fechaRegistro");
            return (Criteria) this;
        }

        public Criteria andFechaRegistroGreaterThan(Date value) {
            addCriterion("\"fecha_registro\" >", value, "fechaRegistro");
            return (Criteria) this;
        }

        public Criteria andFechaRegistroGreaterThanOrEqualTo(Date value) {
            addCriterion("\"fecha_registro\" >=", value, "fechaRegistro");
            return (Criteria) this;
        }

        public Criteria andFechaRegistroLessThan(Date value) {
            addCriterion("\"fecha_registro\" <", value, "fechaRegistro");
            return (Criteria) this;
        }

        public Criteria andFechaRegistroLessThanOrEqualTo(Date value) {
            addCriterion("\"fecha_registro\" <=", value, "fechaRegistro");
            return (Criteria) this;
        }

        public Criteria andFechaRegistroIn(List<Date> values) {
            addCriterion("\"fecha_registro\" in", values, "fechaRegistro");
            return (Criteria) this;
        }

        public Criteria andFechaRegistroNotIn(List<Date> values) {
            addCriterion("\"fecha_registro\" not in", values, "fechaRegistro");
            return (Criteria) this;
        }

        public Criteria andFechaRegistroBetween(Date value1, Date value2) {
            addCriterion("\"fecha_registro\" between", value1, value2, "fechaRegistro");
            return (Criteria) this;
        }

        public Criteria andFechaRegistroNotBetween(Date value1, Date value2) {
            addCriterion("\"fecha_registro\" not between", value1, value2, "fechaRegistro");
            return (Criteria) this;
        }

        public Criteria andUsuarioModificoIsNull() {
            addCriterion("\"usuario_modifico\" is null");
            return (Criteria) this;
        }

        public Criteria andUsuarioModificoIsNotNull() {
            addCriterion("\"usuario_modifico\" is not null");
            return (Criteria) this;
        }

        public Criteria andUsuarioModificoEqualTo(String value) {
            addCriterion("\"usuario_modifico\" =", value, "usuarioModifico");
            return (Criteria) this;
        }

        public Criteria andUsuarioModificoNotEqualTo(String value) {
            addCriterion("\"usuario_modifico\" <>", value, "usuarioModifico");
            return (Criteria) this;
        }

        public Criteria andUsuarioModificoGreaterThan(String value) {
            addCriterion("\"usuario_modifico\" >", value, "usuarioModifico");
            return (Criteria) this;
        }

        public Criteria andUsuarioModificoGreaterThanOrEqualTo(String value) {
            addCriterion("\"usuario_modifico\" >=", value, "usuarioModifico");
            return (Criteria) this;
        }

        public Criteria andUsuarioModificoLessThan(String value) {
            addCriterion("\"usuario_modifico\" <", value, "usuarioModifico");
            return (Criteria) this;
        }

        public Criteria andUsuarioModificoLessThanOrEqualTo(String value) {
            addCriterion("\"usuario_modifico\" <=", value, "usuarioModifico");
            return (Criteria) this;
        }

        public Criteria andUsuarioModificoLike(String value) {
            addCriterion("\"usuario_modifico\" like", value, "usuarioModifico");
            return (Criteria) this;
        }

        public Criteria andUsuarioModificoNotLike(String value) {
            addCriterion("\"usuario_modifico\" not like", value, "usuarioModifico");
            return (Criteria) this;
        }

        public Criteria andUsuarioModificoIn(List<String> values) {
            addCriterion("\"usuario_modifico\" in", values, "usuarioModifico");
            return (Criteria) this;
        }

        public Criteria andUsuarioModificoNotIn(List<String> values) {
            addCriterion("\"usuario_modifico\" not in", values, "usuarioModifico");
            return (Criteria) this;
        }

        public Criteria andUsuarioModificoBetween(String value1, String value2) {
            addCriterion("\"usuario_modifico\" between", value1, value2, "usuarioModifico");
            return (Criteria) this;
        }

        public Criteria andUsuarioModificoNotBetween(String value1, String value2) {
            addCriterion("\"usuario_modifico\" not between", value1, value2, "usuarioModifico");
            return (Criteria) this;
        }

        public Criteria andFechaModificoIsNull() {
            addCriterion("\"fecha_modifico\" is null");
            return (Criteria) this;
        }

        public Criteria andFechaModificoIsNotNull() {
            addCriterion("\"fecha_modifico\" is not null");
            return (Criteria) this;
        }

        public Criteria andFechaModificoEqualTo(Date value) {
            addCriterion("\"fecha_modifico\" =", value, "fechaModifico");
            return (Criteria) this;
        }

        public Criteria andFechaModificoNotEqualTo(Date value) {
            addCriterion("\"fecha_modifico\" <>", value, "fechaModifico");
            return (Criteria) this;
        }

        public Criteria andFechaModificoGreaterThan(Date value) {
            addCriterion("\"fecha_modifico\" >", value, "fechaModifico");
            return (Criteria) this;
        }

        public Criteria andFechaModificoGreaterThanOrEqualTo(Date value) {
            addCriterion("\"fecha_modifico\" >=", value, "fechaModifico");
            return (Criteria) this;
        }

        public Criteria andFechaModificoLessThan(Date value) {
            addCriterion("\"fecha_modifico\" <", value, "fechaModifico");
            return (Criteria) this;
        }

        public Criteria andFechaModificoLessThanOrEqualTo(Date value) {
            addCriterion("\"fecha_modifico\" <=", value, "fechaModifico");
            return (Criteria) this;
        }

        public Criteria andFechaModificoIn(List<Date> values) {
            addCriterion("\"fecha_modifico\" in", values, "fechaModifico");
            return (Criteria) this;
        }

        public Criteria andFechaModificoNotIn(List<Date> values) {
            addCriterion("\"fecha_modifico\" not in", values, "fechaModifico");
            return (Criteria) this;
        }

        public Criteria andFechaModificoBetween(Date value1, Date value2) {
            addCriterion("\"fecha_modifico\" between", value1, value2, "fechaModifico");
            return (Criteria) this;
        }

        public Criteria andFechaModificoNotBetween(Date value1, Date value2) {
            addCriterion("\"fecha_modifico\" not between", value1, value2, "fechaModifico");
            return (Criteria) this;
        }

        public Criteria andColorIsNull() {
            addCriterion("\"color\" is null");
            return (Criteria) this;
        }

        public Criteria andColorIsNotNull() {
            addCriterion("\"color\" is not null");
            return (Criteria) this;
        }

        public Criteria andColorEqualTo(Integer value) {
            addCriterion("\"color\" =", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorNotEqualTo(Integer value) {
            addCriterion("\"color\" <>", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorGreaterThan(Integer value) {
            addCriterion("\"color\" >", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorGreaterThanOrEqualTo(Integer value) {
            addCriterion("\"color\" >=", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorLessThan(Integer value) {
            addCriterion("\"color\" <", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorLessThanOrEqualTo(Integer value) {
            addCriterion("\"color\" <=", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorIn(List<Integer> values) {
            addCriterion("\"color\" in", values, "color");
            return (Criteria) this;
        }

        public Criteria andColorNotIn(List<Integer> values) {
            addCriterion("\"color\" not in", values, "color");
            return (Criteria) this;
        }

        public Criteria andColorBetween(Integer value1, Integer value2) {
            addCriterion("\"color\" between", value1, value2, "color");
            return (Criteria) this;
        }

        public Criteria andColorNotBetween(Integer value1, Integer value2) {
            addCriterion("\"color\" not between", value1, value2, "color");
            return (Criteria) this;
        }

        public Criteria andEstadoIsNull() {
            addCriterion("\"estado\" is null");
            return (Criteria) this;
        }

        public Criteria andEstadoIsNotNull() {
            addCriterion("\"estado\" is not null");
            return (Criteria) this;
        }

        public Criteria andEstadoEqualTo(Integer value) {
            addCriterion("\"estado\" =", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoNotEqualTo(Integer value) {
            addCriterion("\"estado\" <>", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoGreaterThan(Integer value) {
            addCriterion("\"estado\" >", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoGreaterThanOrEqualTo(Integer value) {
            addCriterion("\"estado\" >=", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoLessThan(Integer value) {
            addCriterion("\"estado\" <", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoLessThanOrEqualTo(Integer value) {
            addCriterion("\"estado\" <=", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoIn(List<Integer> values) {
            addCriterion("\"estado\" in", values, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoNotIn(List<Integer> values) {
            addCriterion("\"estado\" not in", values, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoBetween(Integer value1, Integer value2) {
            addCriterion("\"estado\" between", value1, value2, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoNotBetween(Integer value1, Integer value2) {
            addCriterion("\"estado\" not between", value1, value2, "estado");
            return (Criteria) this;
        }

        public Criteria andNombreLikeInsensitive(String value) {
            addCriterion("upper(\"nombre\") like", value.toUpperCase(), "nombre");
            return (Criteria) this;
        }

        public Criteria andCaracteristicaLikeInsensitive(String value) {
            addCriterion("upper(\"caracteristica\") like", value.toUpperCase(), "caracteristica");
            return (Criteria) this;
        }

        public Criteria andDesComentarioLikeInsensitive(String value) {
            addCriterion("upper(\"des_comentario\") like", value.toUpperCase(), "desComentario");
            return (Criteria) this;
        }

        public Criteria andUbicacionCatastroLikeInsensitive(String value) {
            addCriterion("upper(\"ubicacion_catastro\") like", value.toUpperCase(), "ubicacionCatastro");
            return (Criteria) this;
        }

        public Criteria andUsuarioRegistroLikeInsensitive(String value) {
            addCriterion("upper(\"usuario_registro\") like", value.toUpperCase(), "usuarioRegistro");
            return (Criteria) this;
        }

        public Criteria andUsuarioModificoLikeInsensitive(String value) {
            addCriterion("upper(\"usuario_modifico\") like", value.toUpperCase(), "usuarioModifico");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pataPerro.tm_mascota
     *
     * @mbg.generated do_not_delete_during_merge Thu Mar 16 14:09:49 COT 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pataPerro.tm_mascota
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}