package pe.com.pdp.domain.postgres;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import org.springframework.web.multipart.MultipartFile;

import pe.com.pdp.domain.model.GridModel;

public class Mascota extends GridModel implements Serializable{
    
	private static final long serialVersionUID = 1L;
	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_mascota.id
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_mascota.nombre
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    private String nombre;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_mascota.genero
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    private Integer genero;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_mascota.tamanio
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    private Integer tamanio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_mascota.raza
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    private Integer raza;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_mascota.distrito
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    private Integer distrito;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_mascota.caracteristica
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    private String caracteristica;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_mascota.ind_recibido
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    private Integer indRecibido;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_mascota.des_comentario
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    private String desComentario;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_mascota.ubicacion_catastro
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    private String ubicacionCatastro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_mascota.usuario_registro
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    private String usuarioRegistro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_mascota.fecha_registro
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    private Date fechaRegistro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_mascota.usuario_modifico
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    private String usuarioModifico;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_mascota.fecha_modifico
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    private Date fechaModifico;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_mascota.color
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    private Integer color;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_mascota.estado
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    private Integer estado;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_mascota.id
     *
     * @return the value of pataPerro.tm_mascota.id
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_mascota.id
     *
     * @param id the value for pataPerro.tm_mascota.id
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_mascota.nombre
     *
     * @return the value of pataPerro.tm_mascota.nombre
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_mascota.nombre
     *
     * @param nombre the value for pataPerro.tm_mascota.nombre
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_mascota.genero
     *
     * @return the value of pataPerro.tm_mascota.genero
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public Integer getGenero() {
        return genero;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_mascota.genero
     *
     * @param genero the value for pataPerro.tm_mascota.genero
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public void setGenero(Integer genero) {
        this.genero = genero;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_mascota.tamanio
     *
     * @return the value of pataPerro.tm_mascota.tamanio
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public Integer getTamanio() {
        return tamanio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_mascota.tamanio
     *
     * @param tamanio the value for pataPerro.tm_mascota.tamanio
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public void setTamanio(Integer tamanio) {
        this.tamanio = tamanio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_mascota.raza
     *
     * @return the value of pataPerro.tm_mascota.raza
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public Integer getRaza() {
        return raza;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_mascota.raza
     *
     * @param raza the value for pataPerro.tm_mascota.raza
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public void setRaza(Integer raza) {
        this.raza = raza;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_mascota.distrito
     *
     * @return the value of pataPerro.tm_mascota.distrito
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public Integer getDistrito() {
        return distrito;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_mascota.distrito
     *
     * @param distrito the value for pataPerro.tm_mascota.distrito
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public void setDistrito(Integer distrito) {
        this.distrito = distrito;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_mascota.caracteristica
     *
     * @return the value of pataPerro.tm_mascota.caracteristica
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public String getCaracteristica() {
        return caracteristica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_mascota.caracteristica
     *
     * @param caracteristica the value for pataPerro.tm_mascota.caracteristica
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public void setCaracteristica(String caracteristica) {
        this.caracteristica = caracteristica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_mascota.ind_recibido
     *
     * @return the value of pataPerro.tm_mascota.ind_recibido
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public Integer getIndRecibido() {
        return indRecibido;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_mascota.ind_recibido
     *
     * @param indRecibido the value for pataPerro.tm_mascota.ind_recibido
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public void setIndRecibido(Integer indRecibido) {
        this.indRecibido = indRecibido;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_mascota.des_comentario
     *
     * @return the value of pataPerro.tm_mascota.des_comentario
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public String getDesComentario() {
        return desComentario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_mascota.des_comentario
     *
     * @param desComentario the value for pataPerro.tm_mascota.des_comentario
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public void setDesComentario(String desComentario) {
        this.desComentario = desComentario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_mascota.ubicacion_catastro
     *
     * @return the value of pataPerro.tm_mascota.ubicacion_catastro
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public String getUbicacionCatastro() {
        return ubicacionCatastro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_mascota.ubicacion_catastro
     *
     * @param ubicacionCatastro the value for pataPerro.tm_mascota.ubicacion_catastro
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public void setUbicacionCatastro(String ubicacionCatastro) {
        this.ubicacionCatastro = ubicacionCatastro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_mascota.usuario_registro
     *
     * @return the value of pataPerro.tm_mascota.usuario_registro
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public String getUsuarioRegistro() {
        return usuarioRegistro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_mascota.usuario_registro
     *
     * @param usuarioRegistro the value for pataPerro.tm_mascota.usuario_registro
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public void setUsuarioRegistro(String usuarioRegistro) {
        this.usuarioRegistro = usuarioRegistro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_mascota.fecha_registro
     *
     * @return the value of pataPerro.tm_mascota.fecha_registro
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public Date getFechaRegistro() {
        return fechaRegistro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_mascota.fecha_registro
     *
     * @param fechaRegistro the value for pataPerro.tm_mascota.fecha_registro
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_mascota.usuario_modifico
     *
     * @return the value of pataPerro.tm_mascota.usuario_modifico
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public String getUsuarioModifico() {
        return usuarioModifico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_mascota.usuario_modifico
     *
     * @param usuarioModifico the value for pataPerro.tm_mascota.usuario_modifico
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public void setUsuarioModifico(String usuarioModifico) {
        this.usuarioModifico = usuarioModifico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_mascota.fecha_modifico
     *
     * @return the value of pataPerro.tm_mascota.fecha_modifico
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public Date getFechaModifico() {
        return fechaModifico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_mascota.fecha_modifico
     *
     * @param fechaModifico the value for pataPerro.tm_mascota.fecha_modifico
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public void setFechaModifico(Date fechaModifico) {
        this.fechaModifico = fechaModifico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_mascota.color
     *
     * @return the value of pataPerro.tm_mascota.color
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public Integer getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_mascota.color
     *
     * @param color the value for pataPerro.tm_mascota.color
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public void setColor(Integer color) {
        this.color = color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_mascota.estado
     *
     * @return the value of pataPerro.tm_mascota.estado
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public Integer getEstado() {
        return estado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_mascota.estado
     *
     * @param estado the value for pataPerro.tm_mascota.estado
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public void setEstado(Integer estado) {
        this.estado = estado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_mascota
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Mascota other = (Mascota) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getNombre() == null ? other.getNombre() == null : this.getNombre().equals(other.getNombre()))
            && (this.getGenero() == null ? other.getGenero() == null : this.getGenero().equals(other.getGenero()))
            && (this.getTamanio() == null ? other.getTamanio() == null : this.getTamanio().equals(other.getTamanio()))
            && (this.getRaza() == null ? other.getRaza() == null : this.getRaza().equals(other.getRaza()))
            && (this.getDistrito() == null ? other.getDistrito() == null : this.getDistrito().equals(other.getDistrito()))
            && (this.getCaracteristica() == null ? other.getCaracteristica() == null : this.getCaracteristica().equals(other.getCaracteristica()))
            && (this.getIndRecibido() == null ? other.getIndRecibido() == null : this.getIndRecibido().equals(other.getIndRecibido()))
            && (this.getDesComentario() == null ? other.getDesComentario() == null : this.getDesComentario().equals(other.getDesComentario()))
            && (this.getUbicacionCatastro() == null ? other.getUbicacionCatastro() == null : this.getUbicacionCatastro().equals(other.getUbicacionCatastro()))
            && (this.getUsuarioRegistro() == null ? other.getUsuarioRegistro() == null : this.getUsuarioRegistro().equals(other.getUsuarioRegistro()))
            && (this.getFechaRegistro() == null ? other.getFechaRegistro() == null : this.getFechaRegistro().equals(other.getFechaRegistro()))
            && (this.getUsuarioModifico() == null ? other.getUsuarioModifico() == null : this.getUsuarioModifico().equals(other.getUsuarioModifico()))
            && (this.getFechaModifico() == null ? other.getFechaModifico() == null : this.getFechaModifico().equals(other.getFechaModifico()))
            && (this.getColor() == null ? other.getColor() == null : this.getColor().equals(other.getColor()))
            && (this.getEstado() == null ? other.getEstado() == null : this.getEstado().equals(other.getEstado()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_mascota
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getNombre() == null) ? 0 : getNombre().hashCode());
        result = prime * result + ((getGenero() == null) ? 0 : getGenero().hashCode());
        result = prime * result + ((getTamanio() == null) ? 0 : getTamanio().hashCode());
        result = prime * result + ((getRaza() == null) ? 0 : getRaza().hashCode());
        result = prime * result + ((getDistrito() == null) ? 0 : getDistrito().hashCode());
        result = prime * result + ((getCaracteristica() == null) ? 0 : getCaracteristica().hashCode());
        result = prime * result + ((getIndRecibido() == null) ? 0 : getIndRecibido().hashCode());
        result = prime * result + ((getDesComentario() == null) ? 0 : getDesComentario().hashCode());
        result = prime * result + ((getUbicacionCatastro() == null) ? 0 : getUbicacionCatastro().hashCode());
        result = prime * result + ((getUsuarioRegistro() == null) ? 0 : getUsuarioRegistro().hashCode());
        result = prime * result + ((getFechaRegistro() == null) ? 0 : getFechaRegistro().hashCode());
        result = prime * result + ((getUsuarioModifico() == null) ? 0 : getUsuarioModifico().hashCode());
        result = prime * result + ((getFechaModifico() == null) ? 0 : getFechaModifico().hashCode());
        result = prime * result + ((getColor() == null) ? 0 : getColor().hashCode());
        result = prime * result + ((getEstado() == null) ? 0 : getEstado().hashCode());
        return result;
    }
    
    /** Atributos adicionales **/
    
    private MascotaFoto fotoPrincipal;
    
    private List<MascotaFoto> galeriaFotos;
    
    private MultipartFile fileFoto;
    
    private List<MultipartFile> filesFoto;
    
    private Integer personaId;
    
    private String desRaza;
    
    private String desColor;
    
    private String desGenero;
    
    private String desTamanio;
    
    private Persona persona;
    
    private Integer tipoDocumento;

    private String nroDocumento;
    
    private String nombreCompleto;
    
    
	public List<MultipartFile> getFilesFoto() {
		return filesFoto;
	}

	public void setFilesFoto(List<MultipartFile> filesFoto) {
		this.filesFoto = filesFoto;
	}

	public Persona getPersona() {
		return persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	public MascotaFoto getFotoPrincipal() {
		return fotoPrincipal;
	}

	public void setFotoPrincipal(MascotaFoto fotoPrincipal) {
		this.fotoPrincipal = fotoPrincipal;
	}

	public List<MascotaFoto> getGaleriaFotos() {
		return galeriaFotos;
	}

	public void setGaleriaFotos(List<MascotaFoto> galeriaFotos) {
		this.galeriaFotos = galeriaFotos;
	}

	public MultipartFile getFileFoto() {
		return fileFoto;
	}

	public void setFileFoto(MultipartFile fileFoto) {
		this.fileFoto = fileFoto;
	}

	public Integer getPersonaId() {
		return personaId;
	}

	public void setPersonaId(Integer personaId) {
		this.personaId = personaId;
	}

	public String getDesRaza() {
		return desRaza;
	}

	public void setDesRaza(String desRaza) {
		this.desRaza = desRaza;
	}

	public String getDesColor() {
		return desColor;
	}

	public void setDesColor(String desColor) {
		this.desColor = desColor;
	}

	public String getDesGenero() {
		return desGenero;
	}

	public void setDesGenero(String desGenero) {
		this.desGenero = desGenero;
	}

	public String getDesTamanio() {
		return desTamanio;
	}

	public void setDesTamanio(String desTamanio) {
		this.desTamanio = desTamanio;
	}

	public Integer getTipoDocumento() {
		return tipoDocumento;
	}

	public void setTipoDocumento(Integer tipoDocumento) {
		this.tipoDocumento = tipoDocumento;
	}

	public String getNroDocumento() {
		return nroDocumento;
	}

	public void setNroDocumento(String nroDocumento) {
		this.nroDocumento = nroDocumento;
	}

	public String getNombreCompleto() {
		return nombreCompleto;
	}

	public void setNombreCompleto(String nombreCompleto) {
		this.nombreCompleto = nombreCompleto;
	}
	
	
}