package pe.com.pdp.domain.postgres;

public class MascotaFoto {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.td_mascota_foto.id
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.td_mascota_foto.mascota_id
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    private Integer mascotaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.td_mascota_foto.foto
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    private String foto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.td_mascota_foto.ind_principal
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    private Integer indPrincipal;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.td_mascota_foto.id
     *
     * @return the value of pataPerro.td_mascota_foto.id
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.td_mascota_foto.id
     *
     * @param id the value for pataPerro.td_mascota_foto.id
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.td_mascota_foto.mascota_id
     *
     * @return the value of pataPerro.td_mascota_foto.mascota_id
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public Integer getMascotaId() {
        return mascotaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.td_mascota_foto.mascota_id
     *
     * @param mascotaId the value for pataPerro.td_mascota_foto.mascota_id
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public void setMascotaId(Integer mascotaId) {
        this.mascotaId = mascotaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.td_mascota_foto.foto
     *
     * @return the value of pataPerro.td_mascota_foto.foto
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public String getFoto() {
        return foto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.td_mascota_foto.foto
     *
     * @param foto the value for pataPerro.td_mascota_foto.foto
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public void setFoto(String foto) {
        this.foto = foto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.td_mascota_foto.ind_principal
     *
     * @return the value of pataPerro.td_mascota_foto.ind_principal
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public Integer getIndPrincipal() {
        return indPrincipal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.td_mascota_foto.ind_principal
     *
     * @param indPrincipal the value for pataPerro.td_mascota_foto.ind_principal
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public void setIndPrincipal(Integer indPrincipal) {
        this.indPrincipal = indPrincipal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.td_mascota_foto
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MascotaFoto other = (MascotaFoto) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getMascotaId() == null ? other.getMascotaId() == null : this.getMascotaId().equals(other.getMascotaId()))
            && (this.getFoto() == null ? other.getFoto() == null : this.getFoto().equals(other.getFoto()))
            && (this.getIndPrincipal() == null ? other.getIndPrincipal() == null : this.getIndPrincipal().equals(other.getIndPrincipal()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.td_mascota_foto
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getMascotaId() == null) ? 0 : getMascotaId().hashCode());
        result = prime * result + ((getFoto() == null) ? 0 : getFoto().hashCode());
        result = prime * result + ((getIndPrincipal() == null) ? 0 : getIndPrincipal().hashCode());
        return result;
    }
}