package pe.com.pdp.domain.postgres;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import org.springframework.web.multipart.MultipartFile;

import pe.com.pdp.domain.model.GridModel;

public class Negocio extends GridModel implements Serializable{
	private static final long serialVersionUID = 1L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pataPerro.tm_negocio.id
	 * @mbg.generated  Mon May 08 14:33:32 COT 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pataPerro.tm_negocio.titulo
	 * @mbg.generated  Mon May 08 14:33:32 COT 2017
	 */
	private String titulo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pataPerro.tm_negocio.descripcion
	 * @mbg.generated  Mon May 08 14:33:32 COT 2017
	 */
	private String descripcion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pataPerro.tm_negocio.foto
	 * @mbg.generated  Mon May 08 14:33:32 COT 2017
	 */
	private String foto;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pataPerro.tm_negocio.estado
	 * @mbg.generated  Mon May 08 14:33:32 COT 2017
	 */
	private Integer estado;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pataPerro.tm_negocio.id_tipo_negocio
	 * @mbg.generated  Mon May 08 14:33:32 COT 2017
	 */
	private Integer idTipoNegocio;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pataPerro.tm_negocio.ubicacion_catastro
	 * @mbg.generated  Mon May 08 14:33:32 COT 2017
	 */
	private String ubicacionCatastro;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pataPerro.tm_negocio.usuario_registro
	 * @mbg.generated  Mon May 08 14:33:32 COT 2017
	 */
	private String usuarioRegistro;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pataPerro.tm_negocio.fecha_registro
	 * @mbg.generated  Mon May 08 14:33:32 COT 2017
	 */
	private Date fechaRegistro;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pataPerro.tm_negocio.fecha_modifico
	 * @mbg.generated  Mon May 08 14:33:32 COT 2017
	 */
	private Date fechaModifico;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pataPerro.tm_negocio.usuario_modifico
	 * @mbg.generated  Mon May 08 14:33:32 COT 2017
	 */
	private String usuarioModifico;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pataPerro.tm_negocio.telefonos
	 * @mbg.generated  Mon May 08 14:33:32 COT 2017
	 */
	private String telefonos;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pataPerro.tm_negocio.direccion
	 * @mbg.generated  Mon May 08 14:33:32 COT 2017
	 */
	private String direccion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pataPerro.tm_negocio.horario
	 * @mbg.generated  Mon May 08 14:33:32 COT 2017
	 */
	private String horario;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pataPerro.tm_negocio.id
	 * @return  the value of pataPerro.tm_negocio.id
	 * @mbg.generated  Mon May 08 14:33:32 COT 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pataPerro.tm_negocio.id
	 * @param id  the value for pataPerro.tm_negocio.id
	 * @mbg.generated  Mon May 08 14:33:32 COT 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pataPerro.tm_negocio.titulo
	 * @return  the value of pataPerro.tm_negocio.titulo
	 * @mbg.generated  Mon May 08 14:33:32 COT 2017
	 */
	public String getTitulo() {
		return titulo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pataPerro.tm_negocio.titulo
	 * @param titulo  the value for pataPerro.tm_negocio.titulo
	 * @mbg.generated  Mon May 08 14:33:32 COT 2017
	 */
	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pataPerro.tm_negocio.descripcion
	 * @return  the value of pataPerro.tm_negocio.descripcion
	 * @mbg.generated  Mon May 08 14:33:32 COT 2017
	 */
	public String getDescripcion() {
		return descripcion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pataPerro.tm_negocio.descripcion
	 * @param descripcion  the value for pataPerro.tm_negocio.descripcion
	 * @mbg.generated  Mon May 08 14:33:32 COT 2017
	 */
	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pataPerro.tm_negocio.foto
	 * @return  the value of pataPerro.tm_negocio.foto
	 * @mbg.generated  Mon May 08 14:33:32 COT 2017
	 */
	public String getFoto() {
		return foto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pataPerro.tm_negocio.foto
	 * @param foto  the value for pataPerro.tm_negocio.foto
	 * @mbg.generated  Mon May 08 14:33:32 COT 2017
	 */
	public void setFoto(String foto) {
		this.foto = foto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pataPerro.tm_negocio.estado
	 * @return  the value of pataPerro.tm_negocio.estado
	 * @mbg.generated  Mon May 08 14:33:32 COT 2017
	 */
	public Integer getEstado() {
		return estado;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pataPerro.tm_negocio.estado
	 * @param estado  the value for pataPerro.tm_negocio.estado
	 * @mbg.generated  Mon May 08 14:33:32 COT 2017
	 */
	public void setEstado(Integer estado) {
		this.estado = estado;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pataPerro.tm_negocio.id_tipo_negocio
	 * @return  the value of pataPerro.tm_negocio.id_tipo_negocio
	 * @mbg.generated  Mon May 08 14:33:32 COT 2017
	 */
	public Integer getIdTipoNegocio() {
		return idTipoNegocio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pataPerro.tm_negocio.id_tipo_negocio
	 * @param idTipoNegocio  the value for pataPerro.tm_negocio.id_tipo_negocio
	 * @mbg.generated  Mon May 08 14:33:32 COT 2017
	 */
	public void setIdTipoNegocio(Integer idTipoNegocio) {
		this.idTipoNegocio = idTipoNegocio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pataPerro.tm_negocio.ubicacion_catastro
	 * @return  the value of pataPerro.tm_negocio.ubicacion_catastro
	 * @mbg.generated  Mon May 08 14:33:32 COT 2017
	 */
	public String getUbicacionCatastro() {
		return ubicacionCatastro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pataPerro.tm_negocio.ubicacion_catastro
	 * @param ubicacionCatastro  the value for pataPerro.tm_negocio.ubicacion_catastro
	 * @mbg.generated  Mon May 08 14:33:32 COT 2017
	 */
	public void setUbicacionCatastro(String ubicacionCatastro) {
		this.ubicacionCatastro = ubicacionCatastro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pataPerro.tm_negocio.usuario_registro
	 * @return  the value of pataPerro.tm_negocio.usuario_registro
	 * @mbg.generated  Mon May 08 14:33:32 COT 2017
	 */
	public String getUsuarioRegistro() {
		return usuarioRegistro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pataPerro.tm_negocio.usuario_registro
	 * @param usuarioRegistro  the value for pataPerro.tm_negocio.usuario_registro
	 * @mbg.generated  Mon May 08 14:33:32 COT 2017
	 */
	public void setUsuarioRegistro(String usuarioRegistro) {
		this.usuarioRegistro = usuarioRegistro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pataPerro.tm_negocio.fecha_registro
	 * @return  the value of pataPerro.tm_negocio.fecha_registro
	 * @mbg.generated  Mon May 08 14:33:32 COT 2017
	 */
	public Date getFechaRegistro() {
		return fechaRegistro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pataPerro.tm_negocio.fecha_registro
	 * @param fechaRegistro  the value for pataPerro.tm_negocio.fecha_registro
	 * @mbg.generated  Mon May 08 14:33:32 COT 2017
	 */
	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pataPerro.tm_negocio.fecha_modifico
	 * @return  the value of pataPerro.tm_negocio.fecha_modifico
	 * @mbg.generated  Mon May 08 14:33:32 COT 2017
	 */
	public Date getFechaModifico() {
		return fechaModifico;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pataPerro.tm_negocio.fecha_modifico
	 * @param fechaModifico  the value for pataPerro.tm_negocio.fecha_modifico
	 * @mbg.generated  Mon May 08 14:33:32 COT 2017
	 */
	public void setFechaModifico(Date fechaModifico) {
		this.fechaModifico = fechaModifico;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pataPerro.tm_negocio.usuario_modifico
	 * @return  the value of pataPerro.tm_negocio.usuario_modifico
	 * @mbg.generated  Mon May 08 14:33:32 COT 2017
	 */
	public String getUsuarioModifico() {
		return usuarioModifico;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pataPerro.tm_negocio.usuario_modifico
	 * @param usuarioModifico  the value for pataPerro.tm_negocio.usuario_modifico
	 * @mbg.generated  Mon May 08 14:33:32 COT 2017
	 */
	public void setUsuarioModifico(String usuarioModifico) {
		this.usuarioModifico = usuarioModifico;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pataPerro.tm_negocio.telefonos
	 * @return  the value of pataPerro.tm_negocio.telefonos
	 * @mbg.generated  Mon May 08 14:33:32 COT 2017
	 */
	public String getTelefonos() {
		return telefonos;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pataPerro.tm_negocio.telefonos
	 * @param telefonos  the value for pataPerro.tm_negocio.telefonos
	 * @mbg.generated  Mon May 08 14:33:32 COT 2017
	 */
	public void setTelefonos(String telefonos) {
		this.telefonos = telefonos;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pataPerro.tm_negocio.direccion
	 * @return  the value of pataPerro.tm_negocio.direccion
	 * @mbg.generated  Mon May 08 14:33:32 COT 2017
	 */
	public String getDireccion() {
		return direccion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pataPerro.tm_negocio.direccion
	 * @param direccion  the value for pataPerro.tm_negocio.direccion
	 * @mbg.generated  Mon May 08 14:33:32 COT 2017
	 */
	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pataPerro.tm_negocio.horario
	 * @return  the value of pataPerro.tm_negocio.horario
	 * @mbg.generated  Mon May 08 14:33:32 COT 2017
	 */
	public String getHorario() {
		return horario;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pataPerro.tm_negocio.horario
	 * @param horario  the value for pataPerro.tm_negocio.horario
	 * @mbg.generated  Mon May 08 14:33:32 COT 2017
	 */
	public void setHorario(String horario) {
		this.horario = horario;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pataPerro.tm_negocio
	 * @mbg.generated  Mon May 08 14:33:32 COT 2017
	 */@Override 
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		Negocio other = (Negocio) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getTitulo() == null ? other.getTitulo() == null : this.getTitulo().equals(other.getTitulo()))
				&& (this.getDescripcion() == null ? other.getDescripcion() == null
						: this.getDescripcion().equals(other.getDescripcion()))
				&& (this.getFoto() == null ? other.getFoto() == null : this.getFoto().equals(other.getFoto()))
				&& (this.getEstado() == null ? other.getEstado() == null : this.getEstado().equals(other.getEstado()))
				&& (this.getIdTipoNegocio() == null ? other.getIdTipoNegocio() == null
						: this.getIdTipoNegocio().equals(other.getIdTipoNegocio()))
				&& (this.getUbicacionCatastro() == null ? other.getUbicacionCatastro() == null
						: this.getUbicacionCatastro().equals(other.getUbicacionCatastro()))
				&& (this.getUsuarioRegistro() == null ? other.getUsuarioRegistro() == null
						: this.getUsuarioRegistro().equals(other.getUsuarioRegistro()))
				&& (this.getFechaRegistro() == null ? other.getFechaRegistro() == null
						: this.getFechaRegistro().equals(other.getFechaRegistro()))
				&& (this.getFechaModifico() == null ? other.getFechaModifico() == null
						: this.getFechaModifico().equals(other.getFechaModifico()))
				&& (this.getUsuarioModifico() == null ? other.getUsuarioModifico() == null
						: this.getUsuarioModifico().equals(other.getUsuarioModifico()))
				&& (this.getTelefonos() == null ? other.getTelefonos() == null
						: this.getTelefonos().equals(other.getTelefonos()))
				&& (this.getDireccion() == null ? other.getDireccion() == null
						: this.getDireccion().equals(other.getDireccion()))
				&& (this.getHorario() == null ? other.getHorario() == null
						: this.getHorario().equals(other.getHorario()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pataPerro.tm_negocio
	 * @mbg.generated  Mon May 08 14:33:32 COT 2017
	 */@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getTitulo() == null) ? 0 : getTitulo().hashCode());
		result = prime * result + ((getDescripcion() == null) ? 0 : getDescripcion().hashCode());
		result = prime * result + ((getFoto() == null) ? 0 : getFoto().hashCode());
		result = prime * result + ((getEstado() == null) ? 0 : getEstado().hashCode());
		result = prime * result + ((getIdTipoNegocio() == null) ? 0 : getIdTipoNegocio().hashCode());
		result = prime * result + ((getUbicacionCatastro() == null) ? 0 : getUbicacionCatastro().hashCode());
		result = prime * result + ((getUsuarioRegistro() == null) ? 0 : getUsuarioRegistro().hashCode());
		result = prime * result + ((getFechaRegistro() == null) ? 0 : getFechaRegistro().hashCode());
		result = prime * result + ((getFechaModifico() == null) ? 0 : getFechaModifico().hashCode());
		result = prime * result + ((getUsuarioModifico() == null) ? 0 : getUsuarioModifico().hashCode());
		result = prime * result + ((getTelefonos() == null) ? 0 : getTelefonos().hashCode());
		result = prime * result + ((getDireccion() == null) ? 0 : getDireccion().hashCode());
		result = prime * result + ((getHorario() == null) ? 0 : getHorario().hashCode());
		return result;
	}
	
    
	
	
	/** Atributos adicionales **/
    private MultipartFile fileFoto;
    private List<Integer> listNegociaCate;

	public MultipartFile getFileFoto() {
		return fileFoto;
	}

	public void setFileFoto(MultipartFile fileFoto) {
		this.fileFoto = fileFoto;
	}
	private List<NegocioCategoria> listCategoriasNegocio;

	public List<NegocioCategoria> getListCategoriasNegocio() {
		return listCategoriasNegocio;
	}

	public void setListCategoriasNegocio(List<NegocioCategoria> listCategoriasNegocio) {
		this.listCategoriasNegocio = listCategoriasNegocio;
	}

	public List<Integer> getListNegociaCate() {
		return listNegociaCate;
	}

	public void setListNegociaCate(List<Integer> listNegociaCate) {
		this.listNegociaCate = listNegociaCate;
	}
    
    
}