package pe.com.pdp.domain.postgres;

import java.io.Serializable;

public class NegocioCategoria  implements Serializable{
	
	private static final long serialVersionUID = 1L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.td_negocio_categoria.id
     *
     * @mbg.generated Mon May 08 13:20:13 COT 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.td_negocio_categoria.negocio_id
     *
     * @mbg.generated Mon May 08 13:20:13 COT 2017
     */
    private Integer negocioId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.td_negocio_categoria.categoria_id
     *
     * @mbg.generated Mon May 08 13:20:13 COT 2017
     */
    private Integer categoriaId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.td_negocio_categoria.id
     *
     * @return the value of pataPerro.td_negocio_categoria.id
     *
     * @mbg.generated Mon May 08 13:20:13 COT 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.td_negocio_categoria.id
     *
     * @param id the value for pataPerro.td_negocio_categoria.id
     *
     * @mbg.generated Mon May 08 13:20:13 COT 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.td_negocio_categoria.negocio_id
     *
     * @return the value of pataPerro.td_negocio_categoria.negocio_id
     *
     * @mbg.generated Mon May 08 13:20:13 COT 2017
     */
    public Integer getNegocioId() {
        return negocioId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.td_negocio_categoria.negocio_id
     *
     * @param negocioId the value for pataPerro.td_negocio_categoria.negocio_id
     *
     * @mbg.generated Mon May 08 13:20:13 COT 2017
     */
    public void setNegocioId(Integer negocioId) {
        this.negocioId = negocioId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.td_negocio_categoria.categoria_id
     *
     * @return the value of pataPerro.td_negocio_categoria.categoria_id
     *
     * @mbg.generated Mon May 08 13:20:13 COT 2017
     */
    public Integer getCategoriaId() {
        return categoriaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.td_negocio_categoria.categoria_id
     *
     * @param categoriaId the value for pataPerro.td_negocio_categoria.categoria_id
     *
     * @mbg.generated Mon May 08 13:20:13 COT 2017
     */
    public void setCategoriaId(Integer categoriaId) {
        this.categoriaId = categoriaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.td_negocio_categoria
     *
     * @mbg.generated Mon May 08 13:20:13 COT 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        NegocioCategoria other = (NegocioCategoria) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getNegocioId() == null ? other.getNegocioId() == null : this.getNegocioId().equals(other.getNegocioId()))
            && (this.getCategoriaId() == null ? other.getCategoriaId() == null : this.getCategoriaId().equals(other.getCategoriaId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.td_negocio_categoria
     *
     * @mbg.generated Mon May 08 13:20:13 COT 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getNegocioId() == null) ? 0 : getNegocioId().hashCode());
        result = prime * result + ((getCategoriaId() == null) ? 0 : getCategoriaId().hashCode());
        return result;
    }
}