package pe.com.pdp.domain.postgres;

import java.io.Serializable;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

import pe.com.pdp.domain.model.GridModel;

public class Notificacion extends GridModel implements Serializable{
	
	private static final long serialVersionUID = 1L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_notificacion.id
     *
     * @mbg.generated Wed May 10 13:35:30 COT 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_notificacion.tipo_notificacion
     *
     * @mbg.generated Wed May 10 13:35:30 COT 2017
     */
    private Integer tipoNotificacion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_notificacion.tipo_medio
     *
     * @mbg.generated Wed May 10 13:35:30 COT 2017
     */
    private Integer tipoMedio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_notificacion.descripcion
     *
     * @mbg.generated Wed May 10 13:35:30 COT 2017
     */
    private String descripcion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_notificacion.usuario_emisor
     *
     * @mbg.generated Wed May 10 13:35:30 COT 2017
     */
    private String usuarioEmisor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_notificacion.usuario_emisor_id
     *
     * @mbg.generated Wed May 10 13:35:30 COT 2017
     */
    private Integer usuarioEmisorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_notificacion.usuario_destino
     *
     * @mbg.generated Wed May 10 13:35:30 COT 2017
     */
    private String usuarioDestino;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_notificacion.usuario_destino_id
     *
     * @mbg.generated Wed May 10 13:35:30 COT 2017
     */
    private Integer usuarioDestinoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_notificacion.fecha_recepcion
     *
     * @mbg.generated Wed May 10 13:35:30 COT 2017
     */
    @DateTimeFormat(pattern="dd/MM/yyyy")
    private Date fechaRecepcion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_notificacion.estado
     *
     * @mbg.generated Wed May 10 13:35:30 COT 2017
     */
    private Integer estado;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_notificacion.fecha_registro
     *
     * @mbg.generated Wed May 10 13:35:30 COT 2017
     */
    private Date fechaRegistro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_notificacion.usuario_registro
     *
     * @mbg.generated Wed May 10 13:35:30 COT 2017
     */
    private String usuarioRegistro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_notificacion.fecha_modifico
     *
     * @mbg.generated Wed May 10 13:35:30 COT 2017
     */
    private Date fechaModifico;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_notificacion.usuario_modifico
     *
     * @mbg.generated Wed May 10 13:35:30 COT 2017
     */
    private String usuarioModifico;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_notificacion.fecha_emision
     *
     * @mbg.generated Wed May 10 13:35:30 COT 2017
     */
    @DateTimeFormat(pattern="dd/MM/yyyy")
    private Date fechaEmision;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_notificacion.ind_leido
     *
     * @mbg.generated Wed May 10 13:35:30 COT 2017
     */
    private Integer indLeido;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_notificacion.id_relacion
     *
     * @mbg.generated Wed May 10 13:35:30 COT 2017
     */
    private Integer idRelacion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_notificacion.desParametro1  
     *
     * @mbg.generated Wed May 10 13:35:30 COT 2017
     */
    private String desparametro1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_notificacion.desParametro2
     *
     * @mbg.generated Wed May 10 13:35:30 COT 2017
     */
    private String desparametro2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_notificacion.id
     *
     * @return the value of pataPerro.tm_notificacion.id
     *
     * @mbg.generated Wed May 10 13:35:30 COT 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_notificacion.id
     *
     * @param id the value for pataPerro.tm_notificacion.id
     *
     * @mbg.generated Wed May 10 13:35:30 COT 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_notificacion.tipo_notificacion
     *
     * @return the value of pataPerro.tm_notificacion.tipo_notificacion
     *
     * @mbg.generated Wed May 10 13:35:30 COT 2017
     */
    public Integer getTipoNotificacion() {
        return tipoNotificacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_notificacion.tipo_notificacion
     *
     * @param tipoNotificacion the value for pataPerro.tm_notificacion.tipo_notificacion
     *
     * @mbg.generated Wed May 10 13:35:30 COT 2017
     */
    public void setTipoNotificacion(Integer tipoNotificacion) {
        this.tipoNotificacion = tipoNotificacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_notificacion.tipo_medio
     *
     * @return the value of pataPerro.tm_notificacion.tipo_medio
     *
     * @mbg.generated Wed May 10 13:35:30 COT 2017
     */
    public Integer getTipoMedio() {
        return tipoMedio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_notificacion.tipo_medio
     *
     * @param tipoMedio the value for pataPerro.tm_notificacion.tipo_medio
     *
     * @mbg.generated Wed May 10 13:35:30 COT 2017
     */
    public void setTipoMedio(Integer tipoMedio) {
        this.tipoMedio = tipoMedio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_notificacion.descripcion
     *
     * @return the value of pataPerro.tm_notificacion.descripcion
     *
     * @mbg.generated Wed May 10 13:35:30 COT 2017
     */
    public String getDescripcion() {
        return descripcion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_notificacion.descripcion
     *
     * @param descripcion the value for pataPerro.tm_notificacion.descripcion
     *
     * @mbg.generated Wed May 10 13:35:30 COT 2017
     */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_notificacion.usuario_emisor
     *
     * @return the value of pataPerro.tm_notificacion.usuario_emisor
     *
     * @mbg.generated Wed May 10 13:35:30 COT 2017
     */
    public String getUsuarioEmisor() {
        return usuarioEmisor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_notificacion.usuario_emisor
     *
     * @param usuarioEmisor the value for pataPerro.tm_notificacion.usuario_emisor
     *
     * @mbg.generated Wed May 10 13:35:30 COT 2017
     */
    public void setUsuarioEmisor(String usuarioEmisor) {
        this.usuarioEmisor = usuarioEmisor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_notificacion.usuario_emisor_id
     *
     * @return the value of pataPerro.tm_notificacion.usuario_emisor_id
     *
     * @mbg.generated Wed May 10 13:35:30 COT 2017
     */
    public Integer getUsuarioEmisorId() {
        return usuarioEmisorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_notificacion.usuario_emisor_id
     *
     * @param usuarioEmisorId the value for pataPerro.tm_notificacion.usuario_emisor_id
     *
     * @mbg.generated Wed May 10 13:35:30 COT 2017
     */
    public void setUsuarioEmisorId(Integer usuarioEmisorId) {
        this.usuarioEmisorId = usuarioEmisorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_notificacion.usuario_destino
     *
     * @return the value of pataPerro.tm_notificacion.usuario_destino
     *
     * @mbg.generated Wed May 10 13:35:30 COT 2017
     */
    public String getUsuarioDestino() {
        return usuarioDestino;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_notificacion.usuario_destino
     *
     * @param usuarioDestino the value for pataPerro.tm_notificacion.usuario_destino
     *
     * @mbg.generated Wed May 10 13:35:30 COT 2017
     */
    public void setUsuarioDestino(String usuarioDestino) {
        this.usuarioDestino = usuarioDestino;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_notificacion.usuario_destino_id
     *
     * @return the value of pataPerro.tm_notificacion.usuario_destino_id
     *
     * @mbg.generated Wed May 10 13:35:30 COT 2017
     */
    public Integer getUsuarioDestinoId() {
        return usuarioDestinoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_notificacion.usuario_destino_id
     *
     * @param usuarioDestinoId the value for pataPerro.tm_notificacion.usuario_destino_id
     *
     * @mbg.generated Wed May 10 13:35:30 COT 2017
     */
    public void setUsuarioDestinoId(Integer usuarioDestinoId) {
        this.usuarioDestinoId = usuarioDestinoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_notificacion.fecha_recepcion
     *
     * @return the value of pataPerro.tm_notificacion.fecha_recepcion
     *
     * @mbg.generated Wed May 10 13:35:30 COT 2017
     */
    public Date getFechaRecepcion() {
        return fechaRecepcion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_notificacion.fecha_recepcion
     *
     * @param fechaRecepcion the value for pataPerro.tm_notificacion.fecha_recepcion
     *
     * @mbg.generated Wed May 10 13:35:30 COT 2017
     */
    public void setFechaRecepcion(Date fechaRecepcion) {
        this.fechaRecepcion = fechaRecepcion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_notificacion.estado
     *
     * @return the value of pataPerro.tm_notificacion.estado
     *
     * @mbg.generated Wed May 10 13:35:30 COT 2017
     */
    public Integer getEstado() {
        return estado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_notificacion.estado
     *
     * @param estado the value for pataPerro.tm_notificacion.estado
     *
     * @mbg.generated Wed May 10 13:35:30 COT 2017
     */
    public void setEstado(Integer estado) {
        this.estado = estado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_notificacion.fecha_registro
     *
     * @return the value of pataPerro.tm_notificacion.fecha_registro
     *
     * @mbg.generated Wed May 10 13:35:30 COT 2017
     */
    public Date getFechaRegistro() {
        return fechaRegistro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_notificacion.fecha_registro
     *
     * @param fechaRegistro the value for pataPerro.tm_notificacion.fecha_registro
     *
     * @mbg.generated Wed May 10 13:35:30 COT 2017
     */
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_notificacion.usuario_registro
     *
     * @return the value of pataPerro.tm_notificacion.usuario_registro
     *
     * @mbg.generated Wed May 10 13:35:30 COT 2017
     */
    public String getUsuarioRegistro() {
        return usuarioRegistro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_notificacion.usuario_registro
     *
     * @param usuarioRegistro the value for pataPerro.tm_notificacion.usuario_registro
     *
     * @mbg.generated Wed May 10 13:35:30 COT 2017
     */
    public void setUsuarioRegistro(String usuarioRegistro) {
        this.usuarioRegistro = usuarioRegistro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_notificacion.fecha_modifico
     *
     * @return the value of pataPerro.tm_notificacion.fecha_modifico
     *
     * @mbg.generated Wed May 10 13:35:30 COT 2017
     */
    public Date getFechaModifico() {
        return fechaModifico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_notificacion.fecha_modifico
     *
     * @param fechaModifico the value for pataPerro.tm_notificacion.fecha_modifico
     *
     * @mbg.generated Wed May 10 13:35:30 COT 2017
     */
    public void setFechaModifico(Date fechaModifico) {
        this.fechaModifico = fechaModifico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_notificacion.usuario_modifico
     *
     * @return the value of pataPerro.tm_notificacion.usuario_modifico
     *
     * @mbg.generated Wed May 10 13:35:30 COT 2017
     */
    public String getUsuarioModifico() {
        return usuarioModifico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_notificacion.usuario_modifico
     *
     * @param usuarioModifico the value for pataPerro.tm_notificacion.usuario_modifico
     *
     * @mbg.generated Wed May 10 13:35:30 COT 2017
     */
    public void setUsuarioModifico(String usuarioModifico) {
        this.usuarioModifico = usuarioModifico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_notificacion.fecha_emision
     *
     * @return the value of pataPerro.tm_notificacion.fecha_emision
     *
     * @mbg.generated Wed May 10 13:35:30 COT 2017
     */
    public Date getFechaEmision() {
        return fechaEmision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_notificacion.fecha_emision
     *
     * @param fechaEmision the value for pataPerro.tm_notificacion.fecha_emision
     *
     * @mbg.generated Wed May 10 13:35:30 COT 2017
     */
    public void setFechaEmision(Date fechaEmision) {
        this.fechaEmision = fechaEmision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_notificacion.ind_leido
     *
     * @return the value of pataPerro.tm_notificacion.ind_leido
     *
     * @mbg.generated Wed May 10 13:35:30 COT 2017
     */
    public Integer getIndLeido() {
        return indLeido;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_notificacion.ind_leido
     *
     * @param indLeido the value for pataPerro.tm_notificacion.ind_leido
     *
     * @mbg.generated Wed May 10 13:35:30 COT 2017
     */
    public void setIndLeido(Integer indLeido) {
        this.indLeido = indLeido;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_notificacion.id_relacion
     *
     * @return the value of pataPerro.tm_notificacion.id_relacion
     *
     * @mbg.generated Wed May 10 13:35:30 COT 2017
     */
    public Integer getIdRelacion() {
        return idRelacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_notificacion.id_relacion
     *
     * @param idRelacion the value for pataPerro.tm_notificacion.id_relacion
     *
     * @mbg.generated Wed May 10 13:35:30 COT 2017
     */
    public void setIdRelacion(Integer idRelacion) {
        this.idRelacion = idRelacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_notificacion.desParametro1  
     *
     * @return the value of pataPerro.tm_notificacion.desParametro1  
     *
     * @mbg.generated Wed May 10 13:35:30 COT 2017
     */
    public String getDesparametro1() {
        return desparametro1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_notificacion.desParametro1  
     *
     * @param desparametro1 the value for pataPerro.tm_notificacion.desParametro1  
     *
     * @mbg.generated Wed May 10 13:35:30 COT 2017
     */
    public void setDesparametro1(String desparametro1) {
        this.desparametro1 = desparametro1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_notificacion.desParametro2
     *
     * @return the value of pataPerro.tm_notificacion.desParametro2
     *
     * @mbg.generated Wed May 10 13:35:30 COT 2017
     */
    public String getDesparametro2() {
        return desparametro2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_notificacion.desParametro2
     *
     * @param desparametro2 the value for pataPerro.tm_notificacion.desParametro2
     *
     * @mbg.generated Wed May 10 13:35:30 COT 2017
     */
    public void setDesparametro2(String desparametro2) {
        this.desparametro2 = desparametro2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_notificacion
     *
     * @mbg.generated Wed May 10 13:35:30 COT 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Notificacion other = (Notificacion) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getTipoNotificacion() == null ? other.getTipoNotificacion() == null : this.getTipoNotificacion().equals(other.getTipoNotificacion()))
            && (this.getTipoMedio() == null ? other.getTipoMedio() == null : this.getTipoMedio().equals(other.getTipoMedio()))
            && (this.getDescripcion() == null ? other.getDescripcion() == null : this.getDescripcion().equals(other.getDescripcion()))
            && (this.getUsuarioEmisor() == null ? other.getUsuarioEmisor() == null : this.getUsuarioEmisor().equals(other.getUsuarioEmisor()))
            && (this.getUsuarioEmisorId() == null ? other.getUsuarioEmisorId() == null : this.getUsuarioEmisorId().equals(other.getUsuarioEmisorId()))
            && (this.getUsuarioDestino() == null ? other.getUsuarioDestino() == null : this.getUsuarioDestino().equals(other.getUsuarioDestino()))
            && (this.getUsuarioDestinoId() == null ? other.getUsuarioDestinoId() == null : this.getUsuarioDestinoId().equals(other.getUsuarioDestinoId()))
            && (this.getFechaRecepcion() == null ? other.getFechaRecepcion() == null : this.getFechaRecepcion().equals(other.getFechaRecepcion()))
            && (this.getEstado() == null ? other.getEstado() == null : this.getEstado().equals(other.getEstado()))
            && (this.getFechaRegistro() == null ? other.getFechaRegistro() == null : this.getFechaRegistro().equals(other.getFechaRegistro()))
            && (this.getUsuarioRegistro() == null ? other.getUsuarioRegistro() == null : this.getUsuarioRegistro().equals(other.getUsuarioRegistro()))
            && (this.getFechaModifico() == null ? other.getFechaModifico() == null : this.getFechaModifico().equals(other.getFechaModifico()))
            && (this.getUsuarioModifico() == null ? other.getUsuarioModifico() == null : this.getUsuarioModifico().equals(other.getUsuarioModifico()))
            && (this.getFechaEmision() == null ? other.getFechaEmision() == null : this.getFechaEmision().equals(other.getFechaEmision()))
            && (this.getIndLeido() == null ? other.getIndLeido() == null : this.getIndLeido().equals(other.getIndLeido()))
            && (this.getIdRelacion() == null ? other.getIdRelacion() == null : this.getIdRelacion().equals(other.getIdRelacion()))
            && (this.getDesparametro1() == null ? other.getDesparametro1() == null : this.getDesparametro1().equals(other.getDesparametro1()))
            && (this.getDesparametro2() == null ? other.getDesparametro2() == null : this.getDesparametro2().equals(other.getDesparametro2()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_notificacion
     *
     * @mbg.generated Wed May 10 13:35:30 COT 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getTipoNotificacion() == null) ? 0 : getTipoNotificacion().hashCode());
        result = prime * result + ((getTipoMedio() == null) ? 0 : getTipoMedio().hashCode());
        result = prime * result + ((getDescripcion() == null) ? 0 : getDescripcion().hashCode());
        result = prime * result + ((getUsuarioEmisor() == null) ? 0 : getUsuarioEmisor().hashCode());
        result = prime * result + ((getUsuarioEmisorId() == null) ? 0 : getUsuarioEmisorId().hashCode());
        result = prime * result + ((getUsuarioDestino() == null) ? 0 : getUsuarioDestino().hashCode());
        result = prime * result + ((getUsuarioDestinoId() == null) ? 0 : getUsuarioDestinoId().hashCode());
        result = prime * result + ((getFechaRecepcion() == null) ? 0 : getFechaRecepcion().hashCode());
        result = prime * result + ((getEstado() == null) ? 0 : getEstado().hashCode());
        result = prime * result + ((getFechaRegistro() == null) ? 0 : getFechaRegistro().hashCode());
        result = prime * result + ((getUsuarioRegistro() == null) ? 0 : getUsuarioRegistro().hashCode());
        result = prime * result + ((getFechaModifico() == null) ? 0 : getFechaModifico().hashCode());
        result = prime * result + ((getUsuarioModifico() == null) ? 0 : getUsuarioModifico().hashCode());
        result = prime * result + ((getFechaEmision() == null) ? 0 : getFechaEmision().hashCode());
        result = prime * result + ((getIndLeido() == null) ? 0 : getIndLeido().hashCode());
        result = prime * result + ((getIdRelacion() == null) ? 0 : getIdRelacion().hashCode());
        result = prime * result + ((getDesparametro1() == null) ? 0 : getDesparametro1().hashCode());
        result = prime * result + ((getDesparametro2() == null) ? 0 : getDesparametro2().hashCode());
        return result;
    }
    
    /** Atributos adicionales **/
    private Integer rolId;
    private Usuario usuario;

	public Integer getRolId() {
		return rolId;
	}

	public void setRolId(Integer rolId) {
		this.rolId = rolId;
	}

	public Usuario getUsuario() {
		return usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}
	
	
    
}