package pe.com.pdp.domain.postgres;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OpcionCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pataPerro.tm_opcion
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pataPerro.tm_opcion
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pataPerro.tm_opcion
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_opcion
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public OpcionCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_opcion
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_opcion
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_opcion
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_opcion
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_opcion
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_opcion
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_opcion
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_opcion
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_opcion
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_opcion
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pataPerro.tm_opcion
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("\"id\" is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("\"id\" is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("\"id\" =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("\"id\" <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("\"id\" >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("\"id\" >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("\"id\" <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("\"id\" <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("\"id\" in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("\"id\" not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("\"id\" between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("\"id\" not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNombreIsNull() {
            addCriterion("\"nombre\" is null");
            return (Criteria) this;
        }

        public Criteria andNombreIsNotNull() {
            addCriterion("\"nombre\" is not null");
            return (Criteria) this;
        }

        public Criteria andNombreEqualTo(String value) {
            addCriterion("\"nombre\" =", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreNotEqualTo(String value) {
            addCriterion("\"nombre\" <>", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreGreaterThan(String value) {
            addCriterion("\"nombre\" >", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreGreaterThanOrEqualTo(String value) {
            addCriterion("\"nombre\" >=", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreLessThan(String value) {
            addCriterion("\"nombre\" <", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreLessThanOrEqualTo(String value) {
            addCriterion("\"nombre\" <=", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreLike(String value) {
            addCriterion("\"nombre\" like", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreNotLike(String value) {
            addCriterion("\"nombre\" not like", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreIn(List<String> values) {
            addCriterion("\"nombre\" in", values, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreNotIn(List<String> values) {
            addCriterion("\"nombre\" not in", values, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreBetween(String value1, String value2) {
            addCriterion("\"nombre\" between", value1, value2, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreNotBetween(String value1, String value2) {
            addCriterion("\"nombre\" not between", value1, value2, "nombre");
            return (Criteria) this;
        }

        public Criteria andAccionIsNull() {
            addCriterion("\"accion\" is null");
            return (Criteria) this;
        }

        public Criteria andAccionIsNotNull() {
            addCriterion("\"accion\" is not null");
            return (Criteria) this;
        }

        public Criteria andAccionEqualTo(String value) {
            addCriterion("\"accion\" =", value, "accion");
            return (Criteria) this;
        }

        public Criteria andAccionNotEqualTo(String value) {
            addCriterion("\"accion\" <>", value, "accion");
            return (Criteria) this;
        }

        public Criteria andAccionGreaterThan(String value) {
            addCriterion("\"accion\" >", value, "accion");
            return (Criteria) this;
        }

        public Criteria andAccionGreaterThanOrEqualTo(String value) {
            addCriterion("\"accion\" >=", value, "accion");
            return (Criteria) this;
        }

        public Criteria andAccionLessThan(String value) {
            addCriterion("\"accion\" <", value, "accion");
            return (Criteria) this;
        }

        public Criteria andAccionLessThanOrEqualTo(String value) {
            addCriterion("\"accion\" <=", value, "accion");
            return (Criteria) this;
        }

        public Criteria andAccionLike(String value) {
            addCriterion("\"accion\" like", value, "accion");
            return (Criteria) this;
        }

        public Criteria andAccionNotLike(String value) {
            addCriterion("\"accion\" not like", value, "accion");
            return (Criteria) this;
        }

        public Criteria andAccionIn(List<String> values) {
            addCriterion("\"accion\" in", values, "accion");
            return (Criteria) this;
        }

        public Criteria andAccionNotIn(List<String> values) {
            addCriterion("\"accion\" not in", values, "accion");
            return (Criteria) this;
        }

        public Criteria andAccionBetween(String value1, String value2) {
            addCriterion("\"accion\" between", value1, value2, "accion");
            return (Criteria) this;
        }

        public Criteria andAccionNotBetween(String value1, String value2) {
            addCriterion("\"accion\" not between", value1, value2, "accion");
            return (Criteria) this;
        }

        public Criteria andIndPadreIsNull() {
            addCriterion("\"ind_padre\" is null");
            return (Criteria) this;
        }

        public Criteria andIndPadreIsNotNull() {
            addCriterion("\"ind_padre\" is not null");
            return (Criteria) this;
        }

        public Criteria andIndPadreEqualTo(Integer value) {
            addCriterion("\"ind_padre\" =", value, "indPadre");
            return (Criteria) this;
        }

        public Criteria andIndPadreNotEqualTo(Integer value) {
            addCriterion("\"ind_padre\" <>", value, "indPadre");
            return (Criteria) this;
        }

        public Criteria andIndPadreGreaterThan(Integer value) {
            addCriterion("\"ind_padre\" >", value, "indPadre");
            return (Criteria) this;
        }

        public Criteria andIndPadreGreaterThanOrEqualTo(Integer value) {
            addCriterion("\"ind_padre\" >=", value, "indPadre");
            return (Criteria) this;
        }

        public Criteria andIndPadreLessThan(Integer value) {
            addCriterion("\"ind_padre\" <", value, "indPadre");
            return (Criteria) this;
        }

        public Criteria andIndPadreLessThanOrEqualTo(Integer value) {
            addCriterion("\"ind_padre\" <=", value, "indPadre");
            return (Criteria) this;
        }

        public Criteria andIndPadreIn(List<Integer> values) {
            addCriterion("\"ind_padre\" in", values, "indPadre");
            return (Criteria) this;
        }

        public Criteria andIndPadreNotIn(List<Integer> values) {
            addCriterion("\"ind_padre\" not in", values, "indPadre");
            return (Criteria) this;
        }

        public Criteria andIndPadreBetween(Integer value1, Integer value2) {
            addCriterion("\"ind_padre\" between", value1, value2, "indPadre");
            return (Criteria) this;
        }

        public Criteria andIndPadreNotBetween(Integer value1, Integer value2) {
            addCriterion("\"ind_padre\" not between", value1, value2, "indPadre");
            return (Criteria) this;
        }

        public Criteria andModuloIsNull() {
            addCriterion("\"modulo\" is null");
            return (Criteria) this;
        }

        public Criteria andModuloIsNotNull() {
            addCriterion("\"modulo\" is not null");
            return (Criteria) this;
        }

        public Criteria andModuloEqualTo(Integer value) {
            addCriterion("\"modulo\" =", value, "modulo");
            return (Criteria) this;
        }

        public Criteria andModuloNotEqualTo(Integer value) {
            addCriterion("\"modulo\" <>", value, "modulo");
            return (Criteria) this;
        }

        public Criteria andModuloGreaterThan(Integer value) {
            addCriterion("\"modulo\" >", value, "modulo");
            return (Criteria) this;
        }

        public Criteria andModuloGreaterThanOrEqualTo(Integer value) {
            addCriterion("\"modulo\" >=", value, "modulo");
            return (Criteria) this;
        }

        public Criteria andModuloLessThan(Integer value) {
            addCriterion("\"modulo\" <", value, "modulo");
            return (Criteria) this;
        }

        public Criteria andModuloLessThanOrEqualTo(Integer value) {
            addCriterion("\"modulo\" <=", value, "modulo");
            return (Criteria) this;
        }

        public Criteria andModuloIn(List<Integer> values) {
            addCriterion("\"modulo\" in", values, "modulo");
            return (Criteria) this;
        }

        public Criteria andModuloNotIn(List<Integer> values) {
            addCriterion("\"modulo\" not in", values, "modulo");
            return (Criteria) this;
        }

        public Criteria andModuloBetween(Integer value1, Integer value2) {
            addCriterion("\"modulo\" between", value1, value2, "modulo");
            return (Criteria) this;
        }

        public Criteria andModuloNotBetween(Integer value1, Integer value2) {
            addCriterion("\"modulo\" not between", value1, value2, "modulo");
            return (Criteria) this;
        }

        public Criteria andIndTipoMenuIsNull() {
            addCriterion("\"ind_tipo_menu\" is null");
            return (Criteria) this;
        }

        public Criteria andIndTipoMenuIsNotNull() {
            addCriterion("\"ind_tipo_menu\" is not null");
            return (Criteria) this;
        }

        public Criteria andIndTipoMenuEqualTo(Integer value) {
            addCriterion("\"ind_tipo_menu\" =", value, "indTipoMenu");
            return (Criteria) this;
        }

        public Criteria andIndTipoMenuNotEqualTo(Integer value) {
            addCriterion("\"ind_tipo_menu\" <>", value, "indTipoMenu");
            return (Criteria) this;
        }

        public Criteria andIndTipoMenuGreaterThan(Integer value) {
            addCriterion("\"ind_tipo_menu\" >", value, "indTipoMenu");
            return (Criteria) this;
        }

        public Criteria andIndTipoMenuGreaterThanOrEqualTo(Integer value) {
            addCriterion("\"ind_tipo_menu\" >=", value, "indTipoMenu");
            return (Criteria) this;
        }

        public Criteria andIndTipoMenuLessThan(Integer value) {
            addCriterion("\"ind_tipo_menu\" <", value, "indTipoMenu");
            return (Criteria) this;
        }

        public Criteria andIndTipoMenuLessThanOrEqualTo(Integer value) {
            addCriterion("\"ind_tipo_menu\" <=", value, "indTipoMenu");
            return (Criteria) this;
        }

        public Criteria andIndTipoMenuIn(List<Integer> values) {
            addCriterion("\"ind_tipo_menu\" in", values, "indTipoMenu");
            return (Criteria) this;
        }

        public Criteria andIndTipoMenuNotIn(List<Integer> values) {
            addCriterion("\"ind_tipo_menu\" not in", values, "indTipoMenu");
            return (Criteria) this;
        }

        public Criteria andIndTipoMenuBetween(Integer value1, Integer value2) {
            addCriterion("\"ind_tipo_menu\" between", value1, value2, "indTipoMenu");
            return (Criteria) this;
        }

        public Criteria andIndTipoMenuNotBetween(Integer value1, Integer value2) {
            addCriterion("\"ind_tipo_menu\" not between", value1, value2, "indTipoMenu");
            return (Criteria) this;
        }

        public Criteria andEstadoIsNull() {
            addCriterion("\"estado\" is null");
            return (Criteria) this;
        }

        public Criteria andEstadoIsNotNull() {
            addCriterion("\"estado\" is not null");
            return (Criteria) this;
        }

        public Criteria andEstadoEqualTo(Integer value) {
            addCriterion("\"estado\" =", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoNotEqualTo(Integer value) {
            addCriterion("\"estado\" <>", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoGreaterThan(Integer value) {
            addCriterion("\"estado\" >", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoGreaterThanOrEqualTo(Integer value) {
            addCriterion("\"estado\" >=", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoLessThan(Integer value) {
            addCriterion("\"estado\" <", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoLessThanOrEqualTo(Integer value) {
            addCriterion("\"estado\" <=", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoIn(List<Integer> values) {
            addCriterion("\"estado\" in", values, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoNotIn(List<Integer> values) {
            addCriterion("\"estado\" not in", values, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoBetween(Integer value1, Integer value2) {
            addCriterion("\"estado\" between", value1, value2, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoNotBetween(Integer value1, Integer value2) {
            addCriterion("\"estado\" not between", value1, value2, "estado");
            return (Criteria) this;
        }

        public Criteria andOrdenIsNull() {
            addCriterion("\"orden\" is null");
            return (Criteria) this;
        }

        public Criteria andOrdenIsNotNull() {
            addCriterion("\"orden\" is not null");
            return (Criteria) this;
        }

        public Criteria andOrdenEqualTo(Integer value) {
            addCriterion("\"orden\" =", value, "orden");
            return (Criteria) this;
        }

        public Criteria andOrdenNotEqualTo(Integer value) {
            addCriterion("\"orden\" <>", value, "orden");
            return (Criteria) this;
        }

        public Criteria andOrdenGreaterThan(Integer value) {
            addCriterion("\"orden\" >", value, "orden");
            return (Criteria) this;
        }

        public Criteria andOrdenGreaterThanOrEqualTo(Integer value) {
            addCriterion("\"orden\" >=", value, "orden");
            return (Criteria) this;
        }

        public Criteria andOrdenLessThan(Integer value) {
            addCriterion("\"orden\" <", value, "orden");
            return (Criteria) this;
        }

        public Criteria andOrdenLessThanOrEqualTo(Integer value) {
            addCriterion("\"orden\" <=", value, "orden");
            return (Criteria) this;
        }

        public Criteria andOrdenIn(List<Integer> values) {
            addCriterion("\"orden\" in", values, "orden");
            return (Criteria) this;
        }

        public Criteria andOrdenNotIn(List<Integer> values) {
            addCriterion("\"orden\" not in", values, "orden");
            return (Criteria) this;
        }

        public Criteria andOrdenBetween(Integer value1, Integer value2) {
            addCriterion("\"orden\" between", value1, value2, "orden");
            return (Criteria) this;
        }

        public Criteria andOrdenNotBetween(Integer value1, Integer value2) {
            addCriterion("\"orden\" not between", value1, value2, "orden");
            return (Criteria) this;
        }

        public Criteria andUsuarioRegistroIsNull() {
            addCriterion("\"usuario_registro\" is null");
            return (Criteria) this;
        }

        public Criteria andUsuarioRegistroIsNotNull() {
            addCriterion("\"usuario_registro\" is not null");
            return (Criteria) this;
        }

        public Criteria andUsuarioRegistroEqualTo(String value) {
            addCriterion("\"usuario_registro\" =", value, "usuarioRegistro");
            return (Criteria) this;
        }

        public Criteria andUsuarioRegistroNotEqualTo(String value) {
            addCriterion("\"usuario_registro\" <>", value, "usuarioRegistro");
            return (Criteria) this;
        }

        public Criteria andUsuarioRegistroGreaterThan(String value) {
            addCriterion("\"usuario_registro\" >", value, "usuarioRegistro");
            return (Criteria) this;
        }

        public Criteria andUsuarioRegistroGreaterThanOrEqualTo(String value) {
            addCriterion("\"usuario_registro\" >=", value, "usuarioRegistro");
            return (Criteria) this;
        }

        public Criteria andUsuarioRegistroLessThan(String value) {
            addCriterion("\"usuario_registro\" <", value, "usuarioRegistro");
            return (Criteria) this;
        }

        public Criteria andUsuarioRegistroLessThanOrEqualTo(String value) {
            addCriterion("\"usuario_registro\" <=", value, "usuarioRegistro");
            return (Criteria) this;
        }

        public Criteria andUsuarioRegistroLike(String value) {
            addCriterion("\"usuario_registro\" like", value, "usuarioRegistro");
            return (Criteria) this;
        }

        public Criteria andUsuarioRegistroNotLike(String value) {
            addCriterion("\"usuario_registro\" not like", value, "usuarioRegistro");
            return (Criteria) this;
        }

        public Criteria andUsuarioRegistroIn(List<String> values) {
            addCriterion("\"usuario_registro\" in", values, "usuarioRegistro");
            return (Criteria) this;
        }

        public Criteria andUsuarioRegistroNotIn(List<String> values) {
            addCriterion("\"usuario_registro\" not in", values, "usuarioRegistro");
            return (Criteria) this;
        }

        public Criteria andUsuarioRegistroBetween(String value1, String value2) {
            addCriterion("\"usuario_registro\" between", value1, value2, "usuarioRegistro");
            return (Criteria) this;
        }

        public Criteria andUsuarioRegistroNotBetween(String value1, String value2) {
            addCriterion("\"usuario_registro\" not between", value1, value2, "usuarioRegistro");
            return (Criteria) this;
        }

        public Criteria andFechaRegistroIsNull() {
            addCriterion("\"fecha_registro\" is null");
            return (Criteria) this;
        }

        public Criteria andFechaRegistroIsNotNull() {
            addCriterion("\"fecha_registro\" is not null");
            return (Criteria) this;
        }

        public Criteria andFechaRegistroEqualTo(Date value) {
            addCriterion("\"fecha_registro\" =", value, "fechaRegistro");
            return (Criteria) this;
        }

        public Criteria andFechaRegistroNotEqualTo(Date value) {
            addCriterion("\"fecha_registro\" <>", value, "fechaRegistro");
            return (Criteria) this;
        }

        public Criteria andFechaRegistroGreaterThan(Date value) {
            addCriterion("\"fecha_registro\" >", value, "fechaRegistro");
            return (Criteria) this;
        }

        public Criteria andFechaRegistroGreaterThanOrEqualTo(Date value) {
            addCriterion("\"fecha_registro\" >=", value, "fechaRegistro");
            return (Criteria) this;
        }

        public Criteria andFechaRegistroLessThan(Date value) {
            addCriterion("\"fecha_registro\" <", value, "fechaRegistro");
            return (Criteria) this;
        }

        public Criteria andFechaRegistroLessThanOrEqualTo(Date value) {
            addCriterion("\"fecha_registro\" <=", value, "fechaRegistro");
            return (Criteria) this;
        }

        public Criteria andFechaRegistroIn(List<Date> values) {
            addCriterion("\"fecha_registro\" in", values, "fechaRegistro");
            return (Criteria) this;
        }

        public Criteria andFechaRegistroNotIn(List<Date> values) {
            addCriterion("\"fecha_registro\" not in", values, "fechaRegistro");
            return (Criteria) this;
        }

        public Criteria andFechaRegistroBetween(Date value1, Date value2) {
            addCriterion("\"fecha_registro\" between", value1, value2, "fechaRegistro");
            return (Criteria) this;
        }

        public Criteria andFechaRegistroNotBetween(Date value1, Date value2) {
            addCriterion("\"fecha_registro\" not between", value1, value2, "fechaRegistro");
            return (Criteria) this;
        }

        public Criteria andUsuarioModificoIsNull() {
            addCriterion("\"usuario_modifico\" is null");
            return (Criteria) this;
        }

        public Criteria andUsuarioModificoIsNotNull() {
            addCriterion("\"usuario_modifico\" is not null");
            return (Criteria) this;
        }

        public Criteria andUsuarioModificoEqualTo(String value) {
            addCriterion("\"usuario_modifico\" =", value, "usuarioModifico");
            return (Criteria) this;
        }

        public Criteria andUsuarioModificoNotEqualTo(String value) {
            addCriterion("\"usuario_modifico\" <>", value, "usuarioModifico");
            return (Criteria) this;
        }

        public Criteria andUsuarioModificoGreaterThan(String value) {
            addCriterion("\"usuario_modifico\" >", value, "usuarioModifico");
            return (Criteria) this;
        }

        public Criteria andUsuarioModificoGreaterThanOrEqualTo(String value) {
            addCriterion("\"usuario_modifico\" >=", value, "usuarioModifico");
            return (Criteria) this;
        }

        public Criteria andUsuarioModificoLessThan(String value) {
            addCriterion("\"usuario_modifico\" <", value, "usuarioModifico");
            return (Criteria) this;
        }

        public Criteria andUsuarioModificoLessThanOrEqualTo(String value) {
            addCriterion("\"usuario_modifico\" <=", value, "usuarioModifico");
            return (Criteria) this;
        }

        public Criteria andUsuarioModificoLike(String value) {
            addCriterion("\"usuario_modifico\" like", value, "usuarioModifico");
            return (Criteria) this;
        }

        public Criteria andUsuarioModificoNotLike(String value) {
            addCriterion("\"usuario_modifico\" not like", value, "usuarioModifico");
            return (Criteria) this;
        }

        public Criteria andUsuarioModificoIn(List<String> values) {
            addCriterion("\"usuario_modifico\" in", values, "usuarioModifico");
            return (Criteria) this;
        }

        public Criteria andUsuarioModificoNotIn(List<String> values) {
            addCriterion("\"usuario_modifico\" not in", values, "usuarioModifico");
            return (Criteria) this;
        }

        public Criteria andUsuarioModificoBetween(String value1, String value2) {
            addCriterion("\"usuario_modifico\" between", value1, value2, "usuarioModifico");
            return (Criteria) this;
        }

        public Criteria andUsuarioModificoNotBetween(String value1, String value2) {
            addCriterion("\"usuario_modifico\" not between", value1, value2, "usuarioModifico");
            return (Criteria) this;
        }

        public Criteria andFechaModificoIsNull() {
            addCriterion("\"fecha_modifico\" is null");
            return (Criteria) this;
        }

        public Criteria andFechaModificoIsNotNull() {
            addCriterion("\"fecha_modifico\" is not null");
            return (Criteria) this;
        }

        public Criteria andFechaModificoEqualTo(Date value) {
            addCriterion("\"fecha_modifico\" =", value, "fechaModifico");
            return (Criteria) this;
        }

        public Criteria andFechaModificoNotEqualTo(Date value) {
            addCriterion("\"fecha_modifico\" <>", value, "fechaModifico");
            return (Criteria) this;
        }

        public Criteria andFechaModificoGreaterThan(Date value) {
            addCriterion("\"fecha_modifico\" >", value, "fechaModifico");
            return (Criteria) this;
        }

        public Criteria andFechaModificoGreaterThanOrEqualTo(Date value) {
            addCriterion("\"fecha_modifico\" >=", value, "fechaModifico");
            return (Criteria) this;
        }

        public Criteria andFechaModificoLessThan(Date value) {
            addCriterion("\"fecha_modifico\" <", value, "fechaModifico");
            return (Criteria) this;
        }

        public Criteria andFechaModificoLessThanOrEqualTo(Date value) {
            addCriterion("\"fecha_modifico\" <=", value, "fechaModifico");
            return (Criteria) this;
        }

        public Criteria andFechaModificoIn(List<Date> values) {
            addCriterion("\"fecha_modifico\" in", values, "fechaModifico");
            return (Criteria) this;
        }

        public Criteria andFechaModificoNotIn(List<Date> values) {
            addCriterion("\"fecha_modifico\" not in", values, "fechaModifico");
            return (Criteria) this;
        }

        public Criteria andFechaModificoBetween(Date value1, Date value2) {
            addCriterion("\"fecha_modifico\" between", value1, value2, "fechaModifico");
            return (Criteria) this;
        }

        public Criteria andFechaModificoNotBetween(Date value1, Date value2) {
            addCriterion("\"fecha_modifico\" not between", value1, value2, "fechaModifico");
            return (Criteria) this;
        }

        public Criteria andNombreLikeInsensitive(String value) {
            addCriterion("upper(\"nombre\") like", value.toUpperCase(), "nombre");
            return (Criteria) this;
        }

        public Criteria andAccionLikeInsensitive(String value) {
            addCriterion("upper(\"accion\") like", value.toUpperCase(), "accion");
            return (Criteria) this;
        }

        public Criteria andUsuarioRegistroLikeInsensitive(String value) {
            addCriterion("upper(\"usuario_registro\") like", value.toUpperCase(), "usuarioRegistro");
            return (Criteria) this;
        }

        public Criteria andUsuarioModificoLikeInsensitive(String value) {
            addCriterion("upper(\"usuario_modifico\") like", value.toUpperCase(), "usuarioModifico");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pataPerro.tm_opcion
     *
     * @mbg.generated do_not_delete_during_merge Thu Mar 16 14:09:49 COT 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pataPerro.tm_opcion
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}