package pe.com.pdp.domain.postgres;

import java.io.Serializable;
import java.util.Date;

import pe.com.pdp.domain.model.GridModel;

public class Opcion extends GridModel implements Serializable {
	
	private static final long serialVersionUID = 1L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_opcion.id
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_opcion.nombre
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    private String nombre;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_opcion.accion
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    private String accion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_opcion.ind_padre
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    private Integer indPadre;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_opcion.modulo
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    private Integer modulo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_opcion.ind_tipo_menu
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    private Integer indTipoMenu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_opcion.estado
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    private Integer estado;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_opcion.orden
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    private Integer orden;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_opcion.usuario_registro
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    private String usuarioRegistro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_opcion.fecha_registro
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    private Date fechaRegistro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_opcion.usuario_modifico
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    private String usuarioModifico;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_opcion.fecha_modifico
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    private Date fechaModifico;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_opcion.id
     *
     * @return the value of pataPerro.tm_opcion.id
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_opcion.id
     *
     * @param id the value for pataPerro.tm_opcion.id
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_opcion.nombre
     *
     * @return the value of pataPerro.tm_opcion.nombre
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_opcion.nombre
     *
     * @param nombre the value for pataPerro.tm_opcion.nombre
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_opcion.accion
     *
     * @return the value of pataPerro.tm_opcion.accion
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public String getAccion() {
        return accion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_opcion.accion
     *
     * @param accion the value for pataPerro.tm_opcion.accion
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public void setAccion(String accion) {
        this.accion = accion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_opcion.ind_padre
     *
     * @return the value of pataPerro.tm_opcion.ind_padre
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public Integer getIndPadre() {
        return indPadre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_opcion.ind_padre
     *
     * @param indPadre the value for pataPerro.tm_opcion.ind_padre
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public void setIndPadre(Integer indPadre) {
        this.indPadre = indPadre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_opcion.modulo
     *
     * @return the value of pataPerro.tm_opcion.modulo
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public Integer getModulo() {
        return modulo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_opcion.modulo
     *
     * @param modulo the value for pataPerro.tm_opcion.modulo
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public void setModulo(Integer modulo) {
        this.modulo = modulo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_opcion.ind_tipo_menu
     *
     * @return the value of pataPerro.tm_opcion.ind_tipo_menu
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public Integer getIndTipoMenu() {
        return indTipoMenu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_opcion.ind_tipo_menu
     *
     * @param indTipoMenu the value for pataPerro.tm_opcion.ind_tipo_menu
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public void setIndTipoMenu(Integer indTipoMenu) {
        this.indTipoMenu = indTipoMenu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_opcion.estado
     *
     * @return the value of pataPerro.tm_opcion.estado
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public Integer getEstado() {
        return estado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_opcion.estado
     *
     * @param estado the value for pataPerro.tm_opcion.estado
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public void setEstado(Integer estado) {
        this.estado = estado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_opcion.orden
     *
     * @return the value of pataPerro.tm_opcion.orden
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public Integer getOrden() {
        return orden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_opcion.orden
     *
     * @param orden the value for pataPerro.tm_opcion.orden
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public void setOrden(Integer orden) {
        this.orden = orden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_opcion.usuario_registro
     *
     * @return the value of pataPerro.tm_opcion.usuario_registro
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public String getUsuarioRegistro() {
        return usuarioRegistro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_opcion.usuario_registro
     *
     * @param usuarioRegistro the value for pataPerro.tm_opcion.usuario_registro
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public void setUsuarioRegistro(String usuarioRegistro) {
        this.usuarioRegistro = usuarioRegistro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_opcion.fecha_registro
     *
     * @return the value of pataPerro.tm_opcion.fecha_registro
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public Date getFechaRegistro() {
        return fechaRegistro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_opcion.fecha_registro
     *
     * @param fechaRegistro the value for pataPerro.tm_opcion.fecha_registro
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_opcion.usuario_modifico
     *
     * @return the value of pataPerro.tm_opcion.usuario_modifico
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public String getUsuarioModifico() {
        return usuarioModifico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_opcion.usuario_modifico
     *
     * @param usuarioModifico the value for pataPerro.tm_opcion.usuario_modifico
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public void setUsuarioModifico(String usuarioModifico) {
        this.usuarioModifico = usuarioModifico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_opcion.fecha_modifico
     *
     * @return the value of pataPerro.tm_opcion.fecha_modifico
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public Date getFechaModifico() {
        return fechaModifico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_opcion.fecha_modifico
     *
     * @param fechaModifico the value for pataPerro.tm_opcion.fecha_modifico
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public void setFechaModifico(Date fechaModifico) {
        this.fechaModifico = fechaModifico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_opcion
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Opcion other = (Opcion) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getNombre() == null ? other.getNombre() == null : this.getNombre().equals(other.getNombre()))
            && (this.getAccion() == null ? other.getAccion() == null : this.getAccion().equals(other.getAccion()))
            && (this.getIndPadre() == null ? other.getIndPadre() == null : this.getIndPadre().equals(other.getIndPadre()))
            && (this.getModulo() == null ? other.getModulo() == null : this.getModulo().equals(other.getModulo()))
            && (this.getIndTipoMenu() == null ? other.getIndTipoMenu() == null : this.getIndTipoMenu().equals(other.getIndTipoMenu()))
            && (this.getEstado() == null ? other.getEstado() == null : this.getEstado().equals(other.getEstado()))
            && (this.getOrden() == null ? other.getOrden() == null : this.getOrden().equals(other.getOrden()))
            && (this.getUsuarioRegistro() == null ? other.getUsuarioRegistro() == null : this.getUsuarioRegistro().equals(other.getUsuarioRegistro()))
            && (this.getFechaRegistro() == null ? other.getFechaRegistro() == null : this.getFechaRegistro().equals(other.getFechaRegistro()))
            && (this.getUsuarioModifico() == null ? other.getUsuarioModifico() == null : this.getUsuarioModifico().equals(other.getUsuarioModifico()))
            && (this.getFechaModifico() == null ? other.getFechaModifico() == null : this.getFechaModifico().equals(other.getFechaModifico()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_opcion
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getNombre() == null) ? 0 : getNombre().hashCode());
        result = prime * result + ((getAccion() == null) ? 0 : getAccion().hashCode());
        result = prime * result + ((getIndPadre() == null) ? 0 : getIndPadre().hashCode());
        result = prime * result + ((getModulo() == null) ? 0 : getModulo().hashCode());
        result = prime * result + ((getIndTipoMenu() == null) ? 0 : getIndTipoMenu().hashCode());
        result = prime * result + ((getEstado() == null) ? 0 : getEstado().hashCode());
        result = prime * result + ((getOrden() == null) ? 0 : getOrden().hashCode());
        result = prime * result + ((getUsuarioRegistro() == null) ? 0 : getUsuarioRegistro().hashCode());
        result = prime * result + ((getFechaRegistro() == null) ? 0 : getFechaRegistro().hashCode());
        result = prime * result + ((getUsuarioModifico() == null) ? 0 : getUsuarioModifico().hashCode());
        result = prime * result + ((getFechaModifico() == null) ? 0 : getFechaModifico().hashCode());
        return result;
    }
    
    /**Atributos Adicionales**/
	
	private Integer indJerarquia;
	private Integer padreId;
	private Integer hijoId;
	

	public Integer getIndJerarquia() {
		return indJerarquia;
	}

	public void setIndJerarquia(Integer indJerarquia) {
		this.indJerarquia = indJerarquia;
	}

	public Integer getPadreId() {
		return padreId;
	}

	public void setPadreId(Integer padreId) {
		this.padreId = padreId;
	}

	public Integer getHijoId() {
		return hijoId;
	}

	public void setHijoId(Integer hijoId) {
		this.hijoId = hijoId;
	}
}