package pe.com.pdp.domain.postgres;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import org.springframework.format.annotation.DateTimeFormat;

import pe.com.pdp.domain.model.GridModel;

public class Persona extends GridModel implements Serializable{
	
	private static final long serialVersionUID = 1L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_persona.id
     *
     * @mbg.generated Thu Apr 06 02:12:57 COT 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_persona.descripcion
     *
     * @mbg.generated Thu Apr 06 02:12:57 COT 2017
     */
    private String descripcion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_persona.tipo_documento
     *
     * @mbg.generated Thu Apr 06 02:12:57 COT 2017
     */
    private Integer tipoDocumento;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_persona.nro_documento
     *
     * @mbg.generated Thu Apr 06 02:12:57 COT 2017
     */
    private String nroDocumento;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_persona.nombres
     *
     * @mbg.generated Thu Apr 06 02:12:57 COT 2017
     */
    private String nombres;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_persona.apellido_materno
     *
     * @mbg.generated Thu Apr 06 02:12:57 COT 2017
     */
    private String apellidoMaterno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_persona.apellido_paterno
     *
     * @mbg.generated Thu Apr 06 02:12:57 COT 2017
     */
    private String apellidoPaterno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_persona.genero
     *
     * @mbg.generated Thu Apr 06 02:12:57 COT 2017
     */
    private Integer genero;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_persona.nombre_completo
     *
     * @mbg.generated Thu Apr 06 02:12:57 COT 2017
     */
    private String nombreCompleto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_persona.estado
     *
     * @mbg.generated Thu Apr 06 02:12:57 COT 2017
     */
    private Integer estado;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_persona.ubicacion_catastro
     *
     * @mbg.generated Thu Apr 06 02:12:57 COT 2017
     */
    private String ubicacionCatastro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_persona.tipo_persona
     *
     * @mbg.generated Thu Apr 06 02:12:57 COT 2017
     */
    private Integer tipoPersona;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_persona.fecha_nacimiento
     *
     * @mbg.generated Thu Apr 06 02:12:57 COT 2017
     */
    @DateTimeFormat(pattern="dd/MM/yyyy")
    private Date fechaNacimiento;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_persona.ind_padre
     *
     * @mbg.generated Thu Apr 06 02:12:57 COT 2017
     */
    private Integer indPadre;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_persona.usuario_registro
     *
     * @mbg.generated Thu Apr 06 02:12:57 COT 2017
     */
    private String usuarioRegistro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_persona.fecha_registro
     *
     * @mbg.generated Thu Apr 06 02:12:57 COT 2017
     */
    private Date fechaRegistro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_persona.usuario_modifico
     *
     * @mbg.generated Thu Apr 06 02:12:57 COT 2017
     */
    private String usuarioModifico;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_persona.fecha_modifico
     *
     * @mbg.generated Thu Apr 06 02:12:57 COT 2017
     */
    private Date fechaModifico;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_persona.pais
     *
     * @mbg.generated Thu Apr 06 02:12:57 COT 2017
     */
    private Integer pais;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_persona.distrito
     *
     * @mbg.generated Thu Apr 06 02:12:57 COT 2017
     */
    private Integer distrito;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_persona.id
     *
     * @return the value of pataPerro.tm_persona.id
     *
     * @mbg.generated Thu Apr 06 02:12:57 COT 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_persona.id
     *
     * @param id the value for pataPerro.tm_persona.id
     *
     * @mbg.generated Thu Apr 06 02:12:57 COT 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_persona.descripcion
     *
     * @return the value of pataPerro.tm_persona.descripcion
     *
     * @mbg.generated Thu Apr 06 02:12:57 COT 2017
     */
    public String getDescripcion() {
        return descripcion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_persona.descripcion
     *
     * @param descripcion the value for pataPerro.tm_persona.descripcion
     *
     * @mbg.generated Thu Apr 06 02:12:57 COT 2017
     */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_persona.tipo_documento
     *
     * @return the value of pataPerro.tm_persona.tipo_documento
     *
     * @mbg.generated Thu Apr 06 02:12:57 COT 2017
     */
    public Integer getTipoDocumento() {
        return tipoDocumento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_persona.tipo_documento
     *
     * @param tipoDocumento the value for pataPerro.tm_persona.tipo_documento
     *
     * @mbg.generated Thu Apr 06 02:12:57 COT 2017
     */
    public void setTipoDocumento(Integer tipoDocumento) {
        this.tipoDocumento = tipoDocumento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_persona.nro_documento
     *
     * @return the value of pataPerro.tm_persona.nro_documento
     *
     * @mbg.generated Thu Apr 06 02:12:57 COT 2017
     */
    public String getNroDocumento() {
        return nroDocumento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_persona.nro_documento
     *
     * @param nroDocumento the value for pataPerro.tm_persona.nro_documento
     *
     * @mbg.generated Thu Apr 06 02:12:57 COT 2017
     */
    public void setNroDocumento(String nroDocumento) {
        this.nroDocumento = nroDocumento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_persona.nombres
     *
     * @return the value of pataPerro.tm_persona.nombres
     *
     * @mbg.generated Thu Apr 06 02:12:57 COT 2017
     */
    public String getNombres() {
        return nombres;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_persona.nombres
     *
     * @param nombres the value for pataPerro.tm_persona.nombres
     *
     * @mbg.generated Thu Apr 06 02:12:57 COT 2017
     */
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_persona.apellido_materno
     *
     * @return the value of pataPerro.tm_persona.apellido_materno
     *
     * @mbg.generated Thu Apr 06 02:12:57 COT 2017
     */
    public String getApellidoMaterno() {
        return apellidoMaterno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_persona.apellido_materno
     *
     * @param apellidoMaterno the value for pataPerro.tm_persona.apellido_materno
     *
     * @mbg.generated Thu Apr 06 02:12:57 COT 2017
     */
    public void setApellidoMaterno(String apellidoMaterno) {
        this.apellidoMaterno = apellidoMaterno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_persona.apellido_paterno
     *
     * @return the value of pataPerro.tm_persona.apellido_paterno
     *
     * @mbg.generated Thu Apr 06 02:12:57 COT 2017
     */
    public String getApellidoPaterno() {
        return apellidoPaterno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_persona.apellido_paterno
     *
     * @param apellidoPaterno the value for pataPerro.tm_persona.apellido_paterno
     *
     * @mbg.generated Thu Apr 06 02:12:57 COT 2017
     */
    public void setApellidoPaterno(String apellidoPaterno) {
        this.apellidoPaterno = apellidoPaterno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_persona.genero
     *
     * @return the value of pataPerro.tm_persona.genero
     *
     * @mbg.generated Thu Apr 06 02:12:57 COT 2017
     */
    public Integer getGenero() {
        return genero;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_persona.genero
     *
     * @param genero the value for pataPerro.tm_persona.genero
     *
     * @mbg.generated Thu Apr 06 02:12:57 COT 2017
     */
    public void setGenero(Integer genero) {
        this.genero = genero;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_persona.nombre_completo
     *
     * @return the value of pataPerro.tm_persona.nombre_completo
     *
     * @mbg.generated Thu Apr 06 02:12:57 COT 2017
     */
    public String getNombreCompleto() {
        return nombreCompleto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_persona.nombre_completo
     *
     * @param nombreCompleto the value for pataPerro.tm_persona.nombre_completo
     *
     * @mbg.generated Thu Apr 06 02:12:57 COT 2017
     */
    public void setNombreCompleto(String nombreCompleto) {
        this.nombreCompleto = nombreCompleto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_persona.estado
     *
     * @return the value of pataPerro.tm_persona.estado
     *
     * @mbg.generated Thu Apr 06 02:12:57 COT 2017
     */
    public Integer getEstado() {
        return estado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_persona.estado
     *
     * @param estado the value for pataPerro.tm_persona.estado
     *
     * @mbg.generated Thu Apr 06 02:12:57 COT 2017
     */
    public void setEstado(Integer estado) {
        this.estado = estado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_persona.ubicacion_catastro
     *
     * @return the value of pataPerro.tm_persona.ubicacion_catastro
     *
     * @mbg.generated Thu Apr 06 02:12:57 COT 2017
     */
    public String getUbicacionCatastro() {
        return ubicacionCatastro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_persona.ubicacion_catastro
     *
     * @param ubicacionCatastro the value for pataPerro.tm_persona.ubicacion_catastro
     *
     * @mbg.generated Thu Apr 06 02:12:57 COT 2017
     */
    public void setUbicacionCatastro(String ubicacionCatastro) {
        this.ubicacionCatastro = ubicacionCatastro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_persona.tipo_persona
     *
     * @return the value of pataPerro.tm_persona.tipo_persona
     *
     * @mbg.generated Thu Apr 06 02:12:57 COT 2017
     */
    public Integer getTipoPersona() {
        return tipoPersona;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_persona.tipo_persona
     *
     * @param tipoPersona the value for pataPerro.tm_persona.tipo_persona
     *
     * @mbg.generated Thu Apr 06 02:12:57 COT 2017
     */
    public void setTipoPersona(Integer tipoPersona) {
        this.tipoPersona = tipoPersona;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_persona.fecha_nacimiento
     *
     * @return the value of pataPerro.tm_persona.fecha_nacimiento
     *
     * @mbg.generated Thu Apr 06 02:12:57 COT 2017
     */
    public Date getFechaNacimiento() {
        return fechaNacimiento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_persona.fecha_nacimiento
     *
     * @param fechaNacimiento the value for pataPerro.tm_persona.fecha_nacimiento
     *
     * @mbg.generated Thu Apr 06 02:12:57 COT 2017
     */
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_persona.ind_padre
     *
     * @return the value of pataPerro.tm_persona.ind_padre
     *
     * @mbg.generated Thu Apr 06 02:12:57 COT 2017
     */
    public Integer getIndPadre() {
        return indPadre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_persona.ind_padre
     *
     * @param indPadre the value for pataPerro.tm_persona.ind_padre
     *
     * @mbg.generated Thu Apr 06 02:12:57 COT 2017
     */
    public void setIndPadre(Integer indPadre) {
        this.indPadre = indPadre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_persona.usuario_registro
     *
     * @return the value of pataPerro.tm_persona.usuario_registro
     *
     * @mbg.generated Thu Apr 06 02:12:57 COT 2017
     */
    public String getUsuarioRegistro() {
        return usuarioRegistro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_persona.usuario_registro
     *
     * @param usuarioRegistro the value for pataPerro.tm_persona.usuario_registro
     *
     * @mbg.generated Thu Apr 06 02:12:57 COT 2017
     */
    public void setUsuarioRegistro(String usuarioRegistro) {
        this.usuarioRegistro = usuarioRegistro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_persona.fecha_registro
     *
     * @return the value of pataPerro.tm_persona.fecha_registro
     *
     * @mbg.generated Thu Apr 06 02:12:57 COT 2017
     */
    public Date getFechaRegistro() {
        return fechaRegistro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_persona.fecha_registro
     *
     * @param fechaRegistro the value for pataPerro.tm_persona.fecha_registro
     *
     * @mbg.generated Thu Apr 06 02:12:57 COT 2017
     */
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_persona.usuario_modifico
     *
     * @return the value of pataPerro.tm_persona.usuario_modifico
     *
     * @mbg.generated Thu Apr 06 02:12:57 COT 2017
     */
    public String getUsuarioModifico() {
        return usuarioModifico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_persona.usuario_modifico
     *
     * @param usuarioModifico the value for pataPerro.tm_persona.usuario_modifico
     *
     * @mbg.generated Thu Apr 06 02:12:57 COT 2017
     */
    public void setUsuarioModifico(String usuarioModifico) {
        this.usuarioModifico = usuarioModifico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_persona.fecha_modifico
     *
     * @return the value of pataPerro.tm_persona.fecha_modifico
     *
     * @mbg.generated Thu Apr 06 02:12:57 COT 2017
     */
    public Date getFechaModifico() {
        return fechaModifico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_persona.fecha_modifico
     *
     * @param fechaModifico the value for pataPerro.tm_persona.fecha_modifico
     *
     * @mbg.generated Thu Apr 06 02:12:57 COT 2017
     */
    public void setFechaModifico(Date fechaModifico) {
        this.fechaModifico = fechaModifico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_persona.pais
     *
     * @return the value of pataPerro.tm_persona.pais
     *
     * @mbg.generated Thu Apr 06 02:12:57 COT 2017
     */
    public Integer getPais() {
        return pais;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_persona.pais
     *
     * @param pais the value for pataPerro.tm_persona.pais
     *
     * @mbg.generated Thu Apr 06 02:12:57 COT 2017
     */
    public void setPais(Integer pais) {
        this.pais = pais;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_persona.distrito
     *
     * @return the value of pataPerro.tm_persona.distrito
     *
     * @mbg.generated Thu Apr 06 02:12:57 COT 2017
     */
    public Integer getDistrito() {
        return distrito;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_persona.distrito
     *
     * @param distrito the value for pataPerro.tm_persona.distrito
     *
     * @mbg.generated Thu Apr 06 02:12:57 COT 2017
     */
    public void setDistrito(Integer distrito) {
        this.distrito = distrito;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_persona
     *
     * @mbg.generated Thu Apr 06 02:12:57 COT 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Persona other = (Persona) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getDescripcion() == null ? other.getDescripcion() == null : this.getDescripcion().equals(other.getDescripcion()))
            && (this.getTipoDocumento() == null ? other.getTipoDocumento() == null : this.getTipoDocumento().equals(other.getTipoDocumento()))
            && (this.getNroDocumento() == null ? other.getNroDocumento() == null : this.getNroDocumento().equals(other.getNroDocumento()))
            && (this.getNombres() == null ? other.getNombres() == null : this.getNombres().equals(other.getNombres()))
            && (this.getApellidoMaterno() == null ? other.getApellidoMaterno() == null : this.getApellidoMaterno().equals(other.getApellidoMaterno()))
            && (this.getApellidoPaterno() == null ? other.getApellidoPaterno() == null : this.getApellidoPaterno().equals(other.getApellidoPaterno()))
            && (this.getGenero() == null ? other.getGenero() == null : this.getGenero().equals(other.getGenero()))
            && (this.getNombreCompleto() == null ? other.getNombreCompleto() == null : this.getNombreCompleto().equals(other.getNombreCompleto()))
            && (this.getEstado() == null ? other.getEstado() == null : this.getEstado().equals(other.getEstado()))
            && (this.getUbicacionCatastro() == null ? other.getUbicacionCatastro() == null : this.getUbicacionCatastro().equals(other.getUbicacionCatastro()))
            && (this.getTipoPersona() == null ? other.getTipoPersona() == null : this.getTipoPersona().equals(other.getTipoPersona()))
            && (this.getFechaNacimiento() == null ? other.getFechaNacimiento() == null : this.getFechaNacimiento().equals(other.getFechaNacimiento()))
            && (this.getIndPadre() == null ? other.getIndPadre() == null : this.getIndPadre().equals(other.getIndPadre()))
            && (this.getUsuarioRegistro() == null ? other.getUsuarioRegistro() == null : this.getUsuarioRegistro().equals(other.getUsuarioRegistro()))
            && (this.getFechaRegistro() == null ? other.getFechaRegistro() == null : this.getFechaRegistro().equals(other.getFechaRegistro()))
            && (this.getUsuarioModifico() == null ? other.getUsuarioModifico() == null : this.getUsuarioModifico().equals(other.getUsuarioModifico()))
            && (this.getFechaModifico() == null ? other.getFechaModifico() == null : this.getFechaModifico().equals(other.getFechaModifico()))
            && (this.getPais() == null ? other.getPais() == null : this.getPais().equals(other.getPais()))
            && (this.getDistrito() == null ? other.getDistrito() == null : this.getDistrito().equals(other.getDistrito()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_persona
     *
     * @mbg.generated Thu Apr 06 02:12:57 COT 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getDescripcion() == null) ? 0 : getDescripcion().hashCode());
        result = prime * result + ((getTipoDocumento() == null) ? 0 : getTipoDocumento().hashCode());
        result = prime * result + ((getNroDocumento() == null) ? 0 : getNroDocumento().hashCode());
        result = prime * result + ((getNombres() == null) ? 0 : getNombres().hashCode());
        result = prime * result + ((getApellidoMaterno() == null) ? 0 : getApellidoMaterno().hashCode());
        result = prime * result + ((getApellidoPaterno() == null) ? 0 : getApellidoPaterno().hashCode());
        result = prime * result + ((getGenero() == null) ? 0 : getGenero().hashCode());
        result = prime * result + ((getNombreCompleto() == null) ? 0 : getNombreCompleto().hashCode());
        result = prime * result + ((getEstado() == null) ? 0 : getEstado().hashCode());
        result = prime * result + ((getUbicacionCatastro() == null) ? 0 : getUbicacionCatastro().hashCode());
        result = prime * result + ((getTipoPersona() == null) ? 0 : getTipoPersona().hashCode());
        result = prime * result + ((getFechaNacimiento() == null) ? 0 : getFechaNacimiento().hashCode());
        result = prime * result + ((getIndPadre() == null) ? 0 : getIndPadre().hashCode());
        result = prime * result + ((getUsuarioRegistro() == null) ? 0 : getUsuarioRegistro().hashCode());
        result = prime * result + ((getFechaRegistro() == null) ? 0 : getFechaRegistro().hashCode());
        result = prime * result + ((getUsuarioModifico() == null) ? 0 : getUsuarioModifico().hashCode());
        result = prime * result + ((getFechaModifico() == null) ? 0 : getFechaModifico().hashCode());
        result = prime * result + ((getPais() == null) ? 0 : getPais().hashCode());
        result = prime * result + ((getDistrito() == null) ? 0 : getDistrito().hashCode());
        return result;
    }
    
    /** Atributos adicionales **/
    private Contacto contactoPrincipal;
    private Email emailPrincipal;
    private Ubigeo ubigeo;
    
    
    private List<Email> listEmail=new ArrayList<Email>();
    private List<Contacto> listContacto=new ArrayList<Contacto>();
    

	public Contacto getContactoPrincipal() {
		return contactoPrincipal;
	}

	public void setContactoPrincipal(Contacto contactoPrincipal) {
		this.contactoPrincipal = contactoPrincipal;
	}

	public Email getEmailPrincipal() {
		return emailPrincipal;
	}

	public void setEmailPrincipal(Email emailPrincipal) {
		this.emailPrincipal = emailPrincipal;
	}

	public List<Email> getListEmail() {
		return listEmail;
	}

	public void setListEmail(List<Email> listEmail) {
		this.listEmail = listEmail;
	}

	public List<Contacto> getListContacto() {
		return listContacto;
	}

	public void setListContacto(List<Contacto> listContacto) {
		this.listContacto = listContacto;
	}

	public Ubigeo getUbigeo() {
		return ubigeo;
	}

	public void setUbigeo(Ubigeo ubigeo) {
		this.ubigeo = ubigeo;
	}
	
	
}