package pe.com.pdp.domain.postgres;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import pe.com.pdp.domain.model.GridModel;

public class Rol extends GridModel implements Serializable {
   
	private static final long serialVersionUID = 1L;
	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_rol.id
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_rol.nombre
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    private String nombre;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_rol.tipo
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    private Integer tipo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_rol.estado
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    private Integer estado;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_rol.fecha_registro
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    private Date fechaRegistro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_rol.usuario_registro
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    private String usuarioRegistro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_rol.fecha_modifico
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    private Date fechaModifico;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pataPerro.tm_rol.usuario_modifico
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    private String usuarioModifico;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_rol.id
     *
     * @return the value of pataPerro.tm_rol.id
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_rol.id
     *
     * @param id the value for pataPerro.tm_rol.id
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_rol.nombre
     *
     * @return the value of pataPerro.tm_rol.nombre
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_rol.nombre
     *
     * @param nombre the value for pataPerro.tm_rol.nombre
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_rol.tipo
     *
     * @return the value of pataPerro.tm_rol.tipo
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public Integer getTipo() {
        return tipo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_rol.tipo
     *
     * @param tipo the value for pataPerro.tm_rol.tipo
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public void setTipo(Integer tipo) {
        this.tipo = tipo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_rol.estado
     *
     * @return the value of pataPerro.tm_rol.estado
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public Integer getEstado() {
        return estado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_rol.estado
     *
     * @param estado the value for pataPerro.tm_rol.estado
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public void setEstado(Integer estado) {
        this.estado = estado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_rol.fecha_registro
     *
     * @return the value of pataPerro.tm_rol.fecha_registro
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public Date getFechaRegistro() {
        return fechaRegistro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_rol.fecha_registro
     *
     * @param fechaRegistro the value for pataPerro.tm_rol.fecha_registro
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_rol.usuario_registro
     *
     * @return the value of pataPerro.tm_rol.usuario_registro
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public String getUsuarioRegistro() {
        return usuarioRegistro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_rol.usuario_registro
     *
     * @param usuarioRegistro the value for pataPerro.tm_rol.usuario_registro
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public void setUsuarioRegistro(String usuarioRegistro) {
        this.usuarioRegistro = usuarioRegistro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_rol.fecha_modifico
     *
     * @return the value of pataPerro.tm_rol.fecha_modifico
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public Date getFechaModifico() {
        return fechaModifico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_rol.fecha_modifico
     *
     * @param fechaModifico the value for pataPerro.tm_rol.fecha_modifico
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public void setFechaModifico(Date fechaModifico) {
        this.fechaModifico = fechaModifico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pataPerro.tm_rol.usuario_modifico
     *
     * @return the value of pataPerro.tm_rol.usuario_modifico
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public String getUsuarioModifico() {
        return usuarioModifico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pataPerro.tm_rol.usuario_modifico
     *
     * @param usuarioModifico the value for pataPerro.tm_rol.usuario_modifico
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    public void setUsuarioModifico(String usuarioModifico) {
        this.usuarioModifico = usuarioModifico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_rol
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Rol other = (Rol) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getNombre() == null ? other.getNombre() == null : this.getNombre().equals(other.getNombre()))
            && (this.getTipo() == null ? other.getTipo() == null : this.getTipo().equals(other.getTipo()))
            && (this.getEstado() == null ? other.getEstado() == null : this.getEstado().equals(other.getEstado()))
            && (this.getFechaRegistro() == null ? other.getFechaRegistro() == null : this.getFechaRegistro().equals(other.getFechaRegistro()))
            && (this.getUsuarioRegistro() == null ? other.getUsuarioRegistro() == null : this.getUsuarioRegistro().equals(other.getUsuarioRegistro()))
            && (this.getFechaModifico() == null ? other.getFechaModifico() == null : this.getFechaModifico().equals(other.getFechaModifico()))
            && (this.getUsuarioModifico() == null ? other.getUsuarioModifico() == null : this.getUsuarioModifico().equals(other.getUsuarioModifico()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_rol
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getNombre() == null) ? 0 : getNombre().hashCode());
        result = prime * result + ((getTipo() == null) ? 0 : getTipo().hashCode());
        result = prime * result + ((getEstado() == null) ? 0 : getEstado().hashCode());
        result = prime * result + ((getFechaRegistro() == null) ? 0 : getFechaRegistro().hashCode());
        result = prime * result + ((getUsuarioRegistro() == null) ? 0 : getUsuarioRegistro().hashCode());
        result = prime * result + ((getFechaModifico() == null) ? 0 : getFechaModifico().hashCode());
        result = prime * result + ((getUsuarioModifico() == null) ? 0 : getUsuarioModifico().hashCode());
        return result;
    }
    
    /**-Atributos adicionales-**/
    
    private String desTipoRol;

	public String getDesTipoRol() {
		return desTipoRol;
	}

	public void setDesTipoRol(String desTipoRol) {
		this.desTipoRol = desTipoRol;
	}
    
	private List<RolOpcion> opcionesPorRol;

	public List<RolOpcion> getOpcionesPorRol() {
		return opcionesPorRol;
	}

	public void setOpcionesPorRol(List<RolOpcion> opcionesPorRol) {
		this.opcionesPorRol = opcionesPorRol;
	}
}