package pe.com.pdp.domain.postgres;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UsuarioCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pataPerro.tm_usuario
     *
     * @mbggenerated Sun May 14 00:04:04 COT 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pataPerro.tm_usuario
     *
     * @mbggenerated Sun May 14 00:04:04 COT 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pataPerro.tm_usuario
     *
     * @mbggenerated Sun May 14 00:04:04 COT 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_usuario
     *
     * @mbggenerated Sun May 14 00:04:04 COT 2017
     */
    public UsuarioCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_usuario
     *
     * @mbggenerated Sun May 14 00:04:04 COT 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_usuario
     *
     * @mbggenerated Sun May 14 00:04:04 COT 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_usuario
     *
     * @mbggenerated Sun May 14 00:04:04 COT 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_usuario
     *
     * @mbggenerated Sun May 14 00:04:04 COT 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_usuario
     *
     * @mbggenerated Sun May 14 00:04:04 COT 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_usuario
     *
     * @mbggenerated Sun May 14 00:04:04 COT 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_usuario
     *
     * @mbggenerated Sun May 14 00:04:04 COT 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_usuario
     *
     * @mbggenerated Sun May 14 00:04:04 COT 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_usuario
     *
     * @mbggenerated Sun May 14 00:04:04 COT 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_usuario
     *
     * @mbggenerated Sun May 14 00:04:04 COT 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pataPerro.tm_usuario
     *
     * @mbggenerated Sun May 14 00:04:04 COT 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("\"id\" is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("\"id\" is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("\"id\" =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("\"id\" <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("\"id\" >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("\"id\" >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("\"id\" <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("\"id\" <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("\"id\" in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("\"id\" not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("\"id\" between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("\"id\" not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPersonaIdIsNull() {
            addCriterion("\"persona_id\" is null");
            return (Criteria) this;
        }

        public Criteria andPersonaIdIsNotNull() {
            addCriterion("\"persona_id\" is not null");
            return (Criteria) this;
        }

        public Criteria andPersonaIdEqualTo(Integer value) {
            addCriterion("\"persona_id\" =", value, "personaId");
            return (Criteria) this;
        }

        public Criteria andPersonaIdNotEqualTo(Integer value) {
            addCriterion("\"persona_id\" <>", value, "personaId");
            return (Criteria) this;
        }

        public Criteria andPersonaIdGreaterThan(Integer value) {
            addCriterion("\"persona_id\" >", value, "personaId");
            return (Criteria) this;
        }

        public Criteria andPersonaIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("\"persona_id\" >=", value, "personaId");
            return (Criteria) this;
        }

        public Criteria andPersonaIdLessThan(Integer value) {
            addCriterion("\"persona_id\" <", value, "personaId");
            return (Criteria) this;
        }

        public Criteria andPersonaIdLessThanOrEqualTo(Integer value) {
            addCriterion("\"persona_id\" <=", value, "personaId");
            return (Criteria) this;
        }

        public Criteria andPersonaIdIn(List<Integer> values) {
            addCriterion("\"persona_id\" in", values, "personaId");
            return (Criteria) this;
        }

        public Criteria andPersonaIdNotIn(List<Integer> values) {
            addCriterion("\"persona_id\" not in", values, "personaId");
            return (Criteria) this;
        }

        public Criteria andPersonaIdBetween(Integer value1, Integer value2) {
            addCriterion("\"persona_id\" between", value1, value2, "personaId");
            return (Criteria) this;
        }

        public Criteria andPersonaIdNotBetween(Integer value1, Integer value2) {
            addCriterion("\"persona_id\" not between", value1, value2, "personaId");
            return (Criteria) this;
        }

        public Criteria andUsuarioIsNull() {
            addCriterion("\"usuario\" is null");
            return (Criteria) this;
        }

        public Criteria andUsuarioIsNotNull() {
            addCriterion("\"usuario\" is not null");
            return (Criteria) this;
        }

        public Criteria andUsuarioEqualTo(String value) {
            addCriterion("upper(\"usuario\") =", value.toUpperCase(), "usuario");
            return (Criteria) this;
        }

        public Criteria andUsuarioNotEqualTo(String value) {
            addCriterion("\"usuario\" <>", value, "usuario");
            return (Criteria) this;
        }

        public Criteria andUsuarioGreaterThan(String value) {
            addCriterion("\"usuario\" >", value, "usuario");
            return (Criteria) this;
        }

        public Criteria andUsuarioGreaterThanOrEqualTo(String value) {
            addCriterion("\"usuario\" >=", value, "usuario");
            return (Criteria) this;
        }

        public Criteria andUsuarioLessThan(String value) {
            addCriterion("\"usuario\" <", value, "usuario");
            return (Criteria) this;
        }

        public Criteria andUsuarioLessThanOrEqualTo(String value) {
            addCriterion("\"usuario\" <=", value, "usuario");
            return (Criteria) this;
        }

        public Criteria andUsuarioLike(String value) {
            addCriterion("\"usuario\" like", value, "usuario");
            return (Criteria) this;
        }

        public Criteria andUsuarioNotLike(String value) {
            addCriterion("\"usuario\" not like", value, "usuario");
            return (Criteria) this;
        }

        public Criteria andUsuarioIn(List<String> values) {
            addCriterion("\"usuario\" in", values, "usuario");
            return (Criteria) this;
        }

        public Criteria andUsuarioNotIn(List<String> values) {
            addCriterion("\"usuario\" not in", values, "usuario");
            return (Criteria) this;
        }

        public Criteria andUsuarioBetween(String value1, String value2) {
            addCriterion("\"usuario\" between", value1, value2, "usuario");
            return (Criteria) this;
        }

        public Criteria andUsuarioNotBetween(String value1, String value2) {
            addCriterion("\"usuario\" not between", value1, value2, "usuario");
            return (Criteria) this;
        }

        public Criteria andPassIsNull() {
            addCriterion("\"pass\" is null");
            return (Criteria) this;
        }

        public Criteria andPassIsNotNull() {
            addCriterion("\"pass\" is not null");
            return (Criteria) this;
        }

        public Criteria andPassEqualTo(String value) {
            addCriterion("\"pass\" =", value, "pass");
            return (Criteria) this;
        }

        public Criteria andPassNotEqualTo(String value) {
            addCriterion("\"pass\" <>", value, "pass");
            return (Criteria) this;
        }

        public Criteria andPassGreaterThan(String value) {
            addCriterion("\"pass\" >", value, "pass");
            return (Criteria) this;
        }

        public Criteria andPassGreaterThanOrEqualTo(String value) {
            addCriterion("\"pass\" >=", value, "pass");
            return (Criteria) this;
        }

        public Criteria andPassLessThan(String value) {
            addCriterion("\"pass\" <", value, "pass");
            return (Criteria) this;
        }

        public Criteria andPassLessThanOrEqualTo(String value) {
            addCriterion("\"pass\" <=", value, "pass");
            return (Criteria) this;
        }

        public Criteria andPassLike(String value) {
            addCriterion("\"pass\" like", value, "pass");
            return (Criteria) this;
        }

        public Criteria andPassNotLike(String value) {
            addCriterion("\"pass\" not like", value, "pass");
            return (Criteria) this;
        }

        public Criteria andPassIn(List<String> values) {
            addCriterion("\"pass\" in", values, "pass");
            return (Criteria) this;
        }

        public Criteria andPassNotIn(List<String> values) {
            addCriterion("\"pass\" not in", values, "pass");
            return (Criteria) this;
        }

        public Criteria andPassBetween(String value1, String value2) {
            addCriterion("\"pass\" between", value1, value2, "pass");
            return (Criteria) this;
        }

        public Criteria andPassNotBetween(String value1, String value2) {
            addCriterion("\"pass\" not between", value1, value2, "pass");
            return (Criteria) this;
        }

        public Criteria andEstadoIsNull() {
            addCriterion("\"estado\" is null");
            return (Criteria) this;
        }

        public Criteria andEstadoIsNotNull() {
            addCriterion("\"estado\" is not null");
            return (Criteria) this;
        }

        public Criteria andEstadoEqualTo(Integer value) {
            addCriterion("\"estado\" =", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoNotEqualTo(Integer value) {
            addCriterion("\"estado\" <>", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoGreaterThan(Integer value) {
            addCriterion("\"estado\" >", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoGreaterThanOrEqualTo(Integer value) {
            addCriterion("\"estado\" >=", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoLessThan(Integer value) {
            addCriterion("\"estado\" <", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoLessThanOrEqualTo(Integer value) {
            addCriterion("\"estado\" <=", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoIn(List<Integer> values) {
            addCriterion("\"estado\" in", values, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoNotIn(List<Integer> values) {
            addCriterion("\"estado\" not in", values, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoBetween(Integer value1, Integer value2) {
            addCriterion("\"estado\" between", value1, value2, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoNotBetween(Integer value1, Integer value2) {
            addCriterion("\"estado\" not between", value1, value2, "estado");
            return (Criteria) this;
        }

        public Criteria andIndAlertaIsNull() {
            addCriterion("\"ind_alerta\" is null");
            return (Criteria) this;
        }

        public Criteria andIndAlertaIsNotNull() {
            addCriterion("\"ind_alerta\" is not null");
            return (Criteria) this;
        }

        public Criteria andIndAlertaEqualTo(Integer value) {
            addCriterion("\"ind_alerta\" =", value, "indAlerta");
            return (Criteria) this;
        }

        public Criteria andIndAlertaNotEqualTo(Integer value) {
            addCriterion("\"ind_alerta\" <>", value, "indAlerta");
            return (Criteria) this;
        }

        public Criteria andIndAlertaGreaterThan(Integer value) {
            addCriterion("\"ind_alerta\" >", value, "indAlerta");
            return (Criteria) this;
        }

        public Criteria andIndAlertaGreaterThanOrEqualTo(Integer value) {
            addCriterion("\"ind_alerta\" >=", value, "indAlerta");
            return (Criteria) this;
        }

        public Criteria andIndAlertaLessThan(Integer value) {
            addCriterion("\"ind_alerta\" <", value, "indAlerta");
            return (Criteria) this;
        }

        public Criteria andIndAlertaLessThanOrEqualTo(Integer value) {
            addCriterion("\"ind_alerta\" <=", value, "indAlerta");
            return (Criteria) this;
        }

        public Criteria andIndAlertaIn(List<Integer> values) {
            addCriterion("\"ind_alerta\" in", values, "indAlerta");
            return (Criteria) this;
        }

        public Criteria andIndAlertaNotIn(List<Integer> values) {
            addCriterion("\"ind_alerta\" not in", values, "indAlerta");
            return (Criteria) this;
        }

        public Criteria andIndAlertaBetween(Integer value1, Integer value2) {
            addCriterion("\"ind_alerta\" between", value1, value2, "indAlerta");
            return (Criteria) this;
        }

        public Criteria andIndAlertaNotBetween(Integer value1, Integer value2) {
            addCriterion("\"ind_alerta\" not between", value1, value2, "indAlerta");
            return (Criteria) this;
        }

        public Criteria andUsuarioRegistroIsNull() {
            addCriterion("\"usuario_registro\" is null");
            return (Criteria) this;
        }

        public Criteria andUsuarioRegistroIsNotNull() {
            addCriterion("\"usuario_registro\" is not null");
            return (Criteria) this;
        }

        public Criteria andUsuarioRegistroEqualTo(String value) {
            addCriterion("\"usuario_registro\" =", value, "usuarioRegistro");
            return (Criteria) this;
        }

        public Criteria andUsuarioRegistroNotEqualTo(String value) {
            addCriterion("\"usuario_registro\" <>", value, "usuarioRegistro");
            return (Criteria) this;
        }

        public Criteria andUsuarioRegistroGreaterThan(String value) {
            addCriterion("\"usuario_registro\" >", value, "usuarioRegistro");
            return (Criteria) this;
        }

        public Criteria andUsuarioRegistroGreaterThanOrEqualTo(String value) {
            addCriterion("\"usuario_registro\" >=", value, "usuarioRegistro");
            return (Criteria) this;
        }

        public Criteria andUsuarioRegistroLessThan(String value) {
            addCriterion("\"usuario_registro\" <", value, "usuarioRegistro");
            return (Criteria) this;
        }

        public Criteria andUsuarioRegistroLessThanOrEqualTo(String value) {
            addCriterion("\"usuario_registro\" <=", value, "usuarioRegistro");
            return (Criteria) this;
        }

        public Criteria andUsuarioRegistroLike(String value) {
            addCriterion("\"usuario_registro\" like", value, "usuarioRegistro");
            return (Criteria) this;
        }

        public Criteria andUsuarioRegistroNotLike(String value) {
            addCriterion("\"usuario_registro\" not like", value, "usuarioRegistro");
            return (Criteria) this;
        }

        public Criteria andUsuarioRegistroIn(List<String> values) {
            addCriterion("\"usuario_registro\" in", values, "usuarioRegistro");
            return (Criteria) this;
        }

        public Criteria andUsuarioRegistroNotIn(List<String> values) {
            addCriterion("\"usuario_registro\" not in", values, "usuarioRegistro");
            return (Criteria) this;
        }

        public Criteria andUsuarioRegistroBetween(String value1, String value2) {
            addCriterion("\"usuario_registro\" between", value1, value2, "usuarioRegistro");
            return (Criteria) this;
        }

        public Criteria andUsuarioRegistroNotBetween(String value1, String value2) {
            addCriterion("\"usuario_registro\" not between", value1, value2, "usuarioRegistro");
            return (Criteria) this;
        }

        public Criteria andFechaRegistroIsNull() {
            addCriterion("\"fecha_registro\" is null");
            return (Criteria) this;
        }

        public Criteria andFechaRegistroIsNotNull() {
            addCriterion("\"fecha_registro\" is not null");
            return (Criteria) this;
        }

        public Criteria andFechaRegistroEqualTo(Date value) {
            addCriterion("\"fecha_registro\" =", value, "fechaRegistro");
            return (Criteria) this;
        }

        public Criteria andFechaRegistroNotEqualTo(Date value) {
            addCriterion("\"fecha_registro\" <>", value, "fechaRegistro");
            return (Criteria) this;
        }

        public Criteria andFechaRegistroGreaterThan(Date value) {
            addCriterion("\"fecha_registro\" >", value, "fechaRegistro");
            return (Criteria) this;
        }

        public Criteria andFechaRegistroGreaterThanOrEqualTo(Date value) {
            addCriterion("\"fecha_registro\" >=", value, "fechaRegistro");
            return (Criteria) this;
        }

        public Criteria andFechaRegistroLessThan(Date value) {
            addCriterion("\"fecha_registro\" <", value, "fechaRegistro");
            return (Criteria) this;
        }

        public Criteria andFechaRegistroLessThanOrEqualTo(Date value) {
            addCriterion("\"fecha_registro\" <=", value, "fechaRegistro");
            return (Criteria) this;
        }

        public Criteria andFechaRegistroIn(List<Date> values) {
            addCriterion("\"fecha_registro\" in", values, "fechaRegistro");
            return (Criteria) this;
        }

        public Criteria andFechaRegistroNotIn(List<Date> values) {
            addCriterion("\"fecha_registro\" not in", values, "fechaRegistro");
            return (Criteria) this;
        }

        public Criteria andFechaRegistroBetween(Date value1, Date value2) {
            addCriterion("\"fecha_registro\" between", value1, value2, "fechaRegistro");
            return (Criteria) this;
        }

        public Criteria andFechaRegistroNotBetween(Date value1, Date value2) {
            addCriterion("\"fecha_registro\" not between", value1, value2, "fechaRegistro");
            return (Criteria) this;
        }

        public Criteria andUsuarioModificoIsNull() {
            addCriterion("\"usuario_modifico\" is null");
            return (Criteria) this;
        }

        public Criteria andUsuarioModificoIsNotNull() {
            addCriterion("\"usuario_modifico\" is not null");
            return (Criteria) this;
        }

        public Criteria andUsuarioModificoEqualTo(String value) {
            addCriterion("\"usuario_modifico\" =", value, "usuarioModifico");
            return (Criteria) this;
        }

        public Criteria andUsuarioModificoNotEqualTo(String value) {
            addCriterion("\"usuario_modifico\" <>", value, "usuarioModifico");
            return (Criteria) this;
        }

        public Criteria andUsuarioModificoGreaterThan(String value) {
            addCriterion("\"usuario_modifico\" >", value, "usuarioModifico");
            return (Criteria) this;
        }

        public Criteria andUsuarioModificoGreaterThanOrEqualTo(String value) {
            addCriterion("\"usuario_modifico\" >=", value, "usuarioModifico");
            return (Criteria) this;
        }

        public Criteria andUsuarioModificoLessThan(String value) {
            addCriterion("\"usuario_modifico\" <", value, "usuarioModifico");
            return (Criteria) this;
        }

        public Criteria andUsuarioModificoLessThanOrEqualTo(String value) {
            addCriterion("\"usuario_modifico\" <=", value, "usuarioModifico");
            return (Criteria) this;
        }

        public Criteria andUsuarioModificoLike(String value) {
            addCriterion("\"usuario_modifico\" like", value, "usuarioModifico");
            return (Criteria) this;
        }

        public Criteria andUsuarioModificoNotLike(String value) {
            addCriterion("\"usuario_modifico\" not like", value, "usuarioModifico");
            return (Criteria) this;
        }

        public Criteria andUsuarioModificoIn(List<String> values) {
            addCriterion("\"usuario_modifico\" in", values, "usuarioModifico");
            return (Criteria) this;
        }

        public Criteria andUsuarioModificoNotIn(List<String> values) {
            addCriterion("\"usuario_modifico\" not in", values, "usuarioModifico");
            return (Criteria) this;
        }

        public Criteria andUsuarioModificoBetween(String value1, String value2) {
            addCriterion("\"usuario_modifico\" between", value1, value2, "usuarioModifico");
            return (Criteria) this;
        }

        public Criteria andUsuarioModificoNotBetween(String value1, String value2) {
            addCriterion("\"usuario_modifico\" not between", value1, value2, "usuarioModifico");
            return (Criteria) this;
        }

        public Criteria andFechaModificoIsNull() {
            addCriterion("\"fecha_modifico\" is null");
            return (Criteria) this;
        }

        public Criteria andFechaModificoIsNotNull() {
            addCriterion("\"fecha_modifico\" is not null");
            return (Criteria) this;
        }

        public Criteria andFechaModificoEqualTo(Date value) {
            addCriterion("\"fecha_modifico\" =", value, "fechaModifico");
            return (Criteria) this;
        }

        public Criteria andFechaModificoNotEqualTo(Date value) {
            addCriterion("\"fecha_modifico\" <>", value, "fechaModifico");
            return (Criteria) this;
        }

        public Criteria andFechaModificoGreaterThan(Date value) {
            addCriterion("\"fecha_modifico\" >", value, "fechaModifico");
            return (Criteria) this;
        }

        public Criteria andFechaModificoGreaterThanOrEqualTo(Date value) {
            addCriterion("\"fecha_modifico\" >=", value, "fechaModifico");
            return (Criteria) this;
        }

        public Criteria andFechaModificoLessThan(Date value) {
            addCriterion("\"fecha_modifico\" <", value, "fechaModifico");
            return (Criteria) this;
        }

        public Criteria andFechaModificoLessThanOrEqualTo(Date value) {
            addCriterion("\"fecha_modifico\" <=", value, "fechaModifico");
            return (Criteria) this;
        }

        public Criteria andFechaModificoIn(List<Date> values) {
            addCriterion("\"fecha_modifico\" in", values, "fechaModifico");
            return (Criteria) this;
        }

        public Criteria andFechaModificoNotIn(List<Date> values) {
            addCriterion("\"fecha_modifico\" not in", values, "fechaModifico");
            return (Criteria) this;
        }

        public Criteria andFechaModificoBetween(Date value1, Date value2) {
            addCriterion("\"fecha_modifico\" between", value1, value2, "fechaModifico");
            return (Criteria) this;
        }

        public Criteria andFechaModificoNotBetween(Date value1, Date value2) {
            addCriterion("\"fecha_modifico\" not between", value1, value2, "fechaModifico");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioFbIsNull() {
            addCriterion("\"ID_USUARIO_FB\" is null");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioFbIsNotNull() {
            addCriterion("\"ID_USUARIO_FB\" is not null");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioFbEqualTo(String value) {
            addCriterion("\"ID_USUARIO_FB\" =", value, "idUsuarioFb");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioFbNotEqualTo(String value) {
            addCriterion("\"ID_USUARIO_FB\" <>", value, "idUsuarioFb");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioFbGreaterThan(String value) {
            addCriterion("\"ID_USUARIO_FB\" >", value, "idUsuarioFb");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioFbGreaterThanOrEqualTo(String value) {
            addCriterion("\"ID_USUARIO_FB\" >=", value, "idUsuarioFb");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioFbLessThan(String value) {
            addCriterion("\"ID_USUARIO_FB\" <", value, "idUsuarioFb");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioFbLessThanOrEqualTo(String value) {
            addCriterion("\"ID_USUARIO_FB\" <=", value, "idUsuarioFb");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioFbLike(String value) {
            addCriterion("\"ID_USUARIO_FB\" like", value, "idUsuarioFb");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioFbNotLike(String value) {
            addCriterion("\"ID_USUARIO_FB\" not like", value, "idUsuarioFb");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioFbIn(List<String> values) {
            addCriterion("\"ID_USUARIO_FB\" in", values, "idUsuarioFb");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioFbNotIn(List<String> values) {
            addCriterion("\"ID_USUARIO_FB\" not in", values, "idUsuarioFb");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioFbBetween(String value1, String value2) {
            addCriterion("\"ID_USUARIO_FB\" between", value1, value2, "idUsuarioFb");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioFbNotBetween(String value1, String value2) {
            addCriterion("\"ID_USUARIO_FB\" not between", value1, value2, "idUsuarioFb");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioGoIsNull() {
            addCriterion("\"ID_USUARIO_GO\" is null");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioGoIsNotNull() {
            addCriterion("\"ID_USUARIO_GO\" is not null");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioGoEqualTo(String value) {
            addCriterion("\"ID_USUARIO_GO\" =", value, "idUsuarioGo");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioGoNotEqualTo(String value) {
            addCriterion("\"ID_USUARIO_GO\" <>", value, "idUsuarioGo");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioGoGreaterThan(String value) {
            addCriterion("\"ID_USUARIO_GO\" >", value, "idUsuarioGo");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioGoGreaterThanOrEqualTo(String value) {
            addCriterion("\"ID_USUARIO_GO\" >=", value, "idUsuarioGo");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioGoLessThan(String value) {
            addCriterion("\"ID_USUARIO_GO\" <", value, "idUsuarioGo");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioGoLessThanOrEqualTo(String value) {
            addCriterion("\"ID_USUARIO_GO\" <=", value, "idUsuarioGo");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioGoLike(String value) {
            addCriterion("\"ID_USUARIO_GO\" like", value, "idUsuarioGo");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioGoNotLike(String value) {
            addCriterion("\"ID_USUARIO_GO\" not like", value, "idUsuarioGo");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioGoIn(List<String> values) {
            addCriterion("\"ID_USUARIO_GO\" in", values, "idUsuarioGo");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioGoNotIn(List<String> values) {
            addCriterion("\"ID_USUARIO_GO\" not in", values, "idUsuarioGo");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioGoBetween(String value1, String value2) {
            addCriterion("\"ID_USUARIO_GO\" between", value1, value2, "idUsuarioGo");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioGoNotBetween(String value1, String value2) {
            addCriterion("\"ID_USUARIO_GO\" not between", value1, value2, "idUsuarioGo");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioTwIsNull() {
            addCriterion("\"ID_USUARIO_TW\" is null");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioTwIsNotNull() {
            addCriterion("\"ID_USUARIO_TW\" is not null");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioTwEqualTo(String value) {
            addCriterion("\"ID_USUARIO_TW\" =", value, "idUsuarioTw");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioTwNotEqualTo(String value) {
            addCriterion("\"ID_USUARIO_TW\" <>", value, "idUsuarioTw");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioTwGreaterThan(String value) {
            addCriterion("\"ID_USUARIO_TW\" >", value, "idUsuarioTw");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioTwGreaterThanOrEqualTo(String value) {
            addCriterion("\"ID_USUARIO_TW\" >=", value, "idUsuarioTw");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioTwLessThan(String value) {
            addCriterion("\"ID_USUARIO_TW\" <", value, "idUsuarioTw");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioTwLessThanOrEqualTo(String value) {
            addCriterion("\"ID_USUARIO_TW\" <=", value, "idUsuarioTw");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioTwLike(String value) {
            addCriterion("\"ID_USUARIO_TW\" like", value, "idUsuarioTw");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioTwNotLike(String value) {
            addCriterion("\"ID_USUARIO_TW\" not like", value, "idUsuarioTw");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioTwIn(List<String> values) {
            addCriterion("\"ID_USUARIO_TW\" in", values, "idUsuarioTw");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioTwNotIn(List<String> values) {
            addCriterion("\"ID_USUARIO_TW\" not in", values, "idUsuarioTw");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioTwBetween(String value1, String value2) {
            addCriterion("\"ID_USUARIO_TW\" between", value1, value2, "idUsuarioTw");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioTwNotBetween(String value1, String value2) {
            addCriterion("\"ID_USUARIO_TW\" not between", value1, value2, "idUsuarioTw");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioIgIsNull() {
            addCriterion("\"ID_USUARIO_IG\" is null");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioIgIsNotNull() {
            addCriterion("\"ID_USUARIO_IG\" is not null");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioIgEqualTo(String value) {
            addCriterion("\"ID_USUARIO_IG\" =", value, "idUsuarioIg");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioIgNotEqualTo(String value) {
            addCriterion("\"ID_USUARIO_IG\" <>", value, "idUsuarioIg");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioIgGreaterThan(String value) {
            addCriterion("\"ID_USUARIO_IG\" >", value, "idUsuarioIg");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioIgGreaterThanOrEqualTo(String value) {
            addCriterion("\"ID_USUARIO_IG\" >=", value, "idUsuarioIg");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioIgLessThan(String value) {
            addCriterion("\"ID_USUARIO_IG\" <", value, "idUsuarioIg");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioIgLessThanOrEqualTo(String value) {
            addCriterion("\"ID_USUARIO_IG\" <=", value, "idUsuarioIg");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioIgLike(String value) {
            addCriterion("\"ID_USUARIO_IG\" like", value, "idUsuarioIg");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioIgNotLike(String value) {
            addCriterion("\"ID_USUARIO_IG\" not like", value, "idUsuarioIg");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioIgIn(List<String> values) {
            addCriterion("\"ID_USUARIO_IG\" in", values, "idUsuarioIg");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioIgNotIn(List<String> values) {
            addCriterion("\"ID_USUARIO_IG\" not in", values, "idUsuarioIg");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioIgBetween(String value1, String value2) {
            addCriterion("\"ID_USUARIO_IG\" between", value1, value2, "idUsuarioIg");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioIgNotBetween(String value1, String value2) {
            addCriterion("\"ID_USUARIO_IG\" not between", value1, value2, "idUsuarioIg");
            return (Criteria) this;
        }

        public Criteria andUsuarioLikeInsensitive(String value) {
            addCriterion("upper(\"usuario\") like", value.toUpperCase(), "usuario");
            return (Criteria) this;
        }

        public Criteria andPassLikeInsensitive(String value) {
            addCriterion("upper(\"pass\") like", value.toUpperCase(), "pass");
            return (Criteria) this;
        }

        public Criteria andUsuarioRegistroLikeInsensitive(String value) {
            addCriterion("upper(\"usuario_registro\") like", value.toUpperCase(), "usuarioRegistro");
            return (Criteria) this;
        }

        public Criteria andUsuarioModificoLikeInsensitive(String value) {
            addCriterion("upper(\"usuario_modifico\") like", value.toUpperCase(), "usuarioModifico");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioFbLikeInsensitive(String value) {
            addCriterion("upper(\"ID_USUARIO_FB\") like", value.toUpperCase(), "idUsuarioFb");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioGoLikeInsensitive(String value) {
            addCriterion("upper(\"ID_USUARIO_GO\") like", value.toUpperCase(), "idUsuarioGo");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioTwLikeInsensitive(String value) {
            addCriterion("upper(\"ID_USUARIO_TW\") like", value.toUpperCase(), "idUsuarioTw");
            return (Criteria) this;
        }

        public Criteria andIdUsuarioIgLikeInsensitive(String value) {
            addCriterion("upper(\"ID_USUARIO_IG\") like", value.toUpperCase(), "idUsuarioIg");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pataPerro.tm_usuario
     *
     * @mbggenerated do_not_delete_during_merge Sun May 14 00:04:04 COT 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pataPerro.tm_usuario
     *
     * @mbggenerated Sun May 14 00:04:04 COT 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}