package pe.com.pdp.dao.postgres;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import pe.com.pdp.domain.postgres.Busqueda;
import pe.com.pdp.domain.postgres.BusquedaCriteria;

public interface BusquedaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_busqueda
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    int countByExample(BusquedaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_busqueda
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    int deleteByExample(BusquedaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_busqueda
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_busqueda
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    int insert(Busqueda record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_busqueda
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    int insertSelective(Busqueda record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_busqueda
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    List<Busqueda> selectByExample(BusquedaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_busqueda
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    Busqueda selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_busqueda
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    int updateByExampleSelective(@Param("record") Busqueda record, @Param("example") BusquedaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_busqueda
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    int updateByExample(@Param("record") Busqueda record, @Param("example") BusquedaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_busqueda
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    int updateByPrimaryKeySelective(Busqueda record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_busqueda
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    int updateByPrimaryKey(Busqueda record);
    
    List<Map<String, Object>> selectByBusquedaMascota( Map<String, Object>  parametros);
	int countBusquedaMascotas(Map<String, Object>  parametros);
	Map<String, Object> getBusquedaVigencia(Map<String, Object> param);
}