package pe.com.pdp.dao.postgres;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pe.com.pdp.domain.postgres.BusquedaFoto;
import pe.com.pdp.domain.postgres.BusquedaFotoCriteria;

public interface BusquedaFotoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.td_busqueda_foto
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    long countByExample(BusquedaFotoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.td_busqueda_foto
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    int deleteByExample(BusquedaFotoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.td_busqueda_foto
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.td_busqueda_foto
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    int insert(BusquedaFoto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.td_busqueda_foto
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    int insertSelective(BusquedaFoto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.td_busqueda_foto
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    List<BusquedaFoto> selectByExample(BusquedaFotoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.td_busqueda_foto
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    BusquedaFoto selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.td_busqueda_foto
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    int updateByExampleSelective(@Param("record") BusquedaFoto record, @Param("example") BusquedaFotoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.td_busqueda_foto
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    int updateByExample(@Param("record") BusquedaFoto record, @Param("example") BusquedaFotoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.td_busqueda_foto
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    int updateByPrimaryKeySelective(BusquedaFoto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.td_busqueda_foto
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    int updateByPrimaryKey(BusquedaFoto record);
}