package pe.com.pdp.dao.postgres;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pe.com.pdp.domain.postgres.EncontradoFoto;
import pe.com.pdp.domain.postgres.EncontradoFotoCriteria;

public interface EncontradoFotoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.td_encontrado_foto
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    long countByExample(EncontradoFotoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.td_encontrado_foto
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    int deleteByExample(EncontradoFotoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.td_encontrado_foto
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.td_encontrado_foto
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    int insert(EncontradoFoto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.td_encontrado_foto
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    int insertSelective(EncontradoFoto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.td_encontrado_foto
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    List<EncontradoFoto> selectByExample(EncontradoFotoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.td_encontrado_foto
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    EncontradoFoto selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.td_encontrado_foto
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    int updateByExampleSelective(@Param("record") EncontradoFoto record, @Param("example") EncontradoFotoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.td_encontrado_foto
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    int updateByExample(@Param("record") EncontradoFoto record, @Param("example") EncontradoFotoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.td_encontrado_foto
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    int updateByPrimaryKeySelective(EncontradoFoto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.td_encontrado_foto
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    int updateByPrimaryKey(EncontradoFoto record);
}