package pe.com.pdp.dao.postgres;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import pe.com.pdp.domain.postgres.Encontrado;
import pe.com.pdp.domain.postgres.EncontradoCriteria;

public interface EncontradoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_encontrado
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    int countByExample(EncontradoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_encontrado
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    int deleteByExample(EncontradoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_encontrado
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_encontrado
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    int insert(Encontrado record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_encontrado
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    int insertSelective(Encontrado record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_encontrado
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    List<Encontrado> selectByExample(EncontradoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_encontrado
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    Encontrado selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_encontrado
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    int updateByExampleSelective(@Param("record") Encontrado record, @Param("example") EncontradoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_encontrado
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    int updateByExample(@Param("record") Encontrado record, @Param("example") EncontradoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_encontrado
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    int updateByPrimaryKeySelective(Encontrado record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_encontrado
     *
     * @mbggenerated Wed Jun 14 23:04:58 COT 2017
     */
    int updateByPrimaryKey(Encontrado record);
    
    /**Adicional**/
	List<Map<String, Object>> selectByEncontreMascota( Map<String, Object>  parametros);
	int countEncontreMascotas(Map<String, Object>  parametros);
	Map<String, Object> getEncontradoVigencia(Map<String, Object> param);
}