package pe.com.pdp.dao.postgres;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import pe.com.pdp.domain.postgres.GrupoElemento;
import pe.com.pdp.domain.postgres.GrupoElementoCriteria;

public interface GrupoElementoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_grupo_elemento
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    long countByExample(GrupoElementoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_grupo_elemento
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    int deleteByExample(GrupoElementoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_grupo_elemento
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_grupo_elemento
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    int insert(GrupoElemento record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_grupo_elemento
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    int insertSelective(GrupoElemento record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_grupo_elemento
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    List<GrupoElemento> selectByExample(GrupoElementoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_grupo_elemento
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    GrupoElemento selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_grupo_elemento
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    int updateByExampleSelective(@Param("record") GrupoElemento record, @Param("example") GrupoElementoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_grupo_elemento
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    int updateByExample(@Param("record") GrupoElemento record, @Param("example") GrupoElementoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_grupo_elemento
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    int updateByPrimaryKeySelective(GrupoElemento record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_grupo_elemento
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    int updateByPrimaryKey(GrupoElemento record);
    
    /**Metodos Adicionales**/
    List<Map<String, Object>> selectByGrupoElemento( Map<String, Object>  parametros);
	int countGrupoElemento(Map<String, Object>  parametros);
}