package pe.com.pdp.dao.postgres;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pe.com.pdp.domain.postgres.MascotaFoto;
import pe.com.pdp.domain.postgres.MascotaFotoCriteria;

public interface MascotaFotoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.td_mascota_foto
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    long countByExample(MascotaFotoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.td_mascota_foto
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    int deleteByExample(MascotaFotoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.td_mascota_foto
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.td_mascota_foto
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    int insert(MascotaFoto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.td_mascota_foto
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    int insertSelective(MascotaFoto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.td_mascota_foto
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    List<MascotaFoto> selectByExample(MascotaFotoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.td_mascota_foto
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    MascotaFoto selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.td_mascota_foto
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    int updateByExampleSelective(@Param("record") MascotaFoto record, @Param("example") MascotaFotoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.td_mascota_foto
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    int updateByExample(@Param("record") MascotaFoto record, @Param("example") MascotaFotoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.td_mascota_foto
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    int updateByPrimaryKeySelective(MascotaFoto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.td_mascota_foto
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    int updateByPrimaryKey(MascotaFoto record);
}