package pe.com.pdp.dao.postgres;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import pe.com.pdp.domain.postgres.Mascota;
import pe.com.pdp.domain.postgres.MascotaCriteria;

public interface MascotaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_mascota
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    long countByExample(MascotaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_mascota
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    int deleteByExample(MascotaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_mascota
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_mascota
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    int insert(Mascota record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_mascota
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    int insertSelective(Mascota record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_mascota
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    List<Mascota> selectByExample(MascotaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_mascota
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    Mascota selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_mascota
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    int updateByExampleSelective(@Param("record") Mascota record, @Param("example") MascotaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_mascota
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    int updateByExample(@Param("record") Mascota record, @Param("example") MascotaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_mascota
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    int updateByPrimaryKeySelective(Mascota record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_mascota
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    int updateByPrimaryKey(Mascota record);
    
    

    /**
     * Listar mascotas enlazadas a una persona
     */
    List<Mascota> listarMascotasPersona(Mascota mascota);
    
    /**Adicional**/
   	List<Map<String, Object>> selectByMascota( Map<String, Object>  parametros);
  	int countMascotas(Map<String, Object>  parametros);
    
}