package pe.com.pdp.dao.postgres;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import pe.com.pdp.domain.postgres.Negocio;
import pe.com.pdp.domain.postgres.NegocioCriteria;

public interface NegocioMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_negocio
     *
     * @mbg.generated Mon May 08 14:33:32 COT 2017
     */
    long countByExample(NegocioCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_negocio
     *
     * @mbg.generated Mon May 08 14:33:32 COT 2017
     */
    int deleteByExample(NegocioCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_negocio
     *
     * @mbg.generated Mon May 08 14:33:32 COT 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_negocio
     *
     * @mbg.generated Mon May 08 14:33:32 COT 2017
     */
    int insert(Negocio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_negocio
     *
     * @mbg.generated Mon May 08 14:33:32 COT 2017
     */
    int insertSelective(Negocio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_negocio
     *
     * @mbg.generated Mon May 08 14:33:32 COT 2017
     */
    List<Negocio> selectByExample(NegocioCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_negocio
     *
     * @mbg.generated Mon May 08 14:33:32 COT 2017
     */
    Negocio selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_negocio
     *
     * @mbg.generated Mon May 08 14:33:32 COT 2017
     */
    int updateByExampleSelective(@Param("record") Negocio record, @Param("example") NegocioCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_negocio
     *
     * @mbg.generated Mon May 08 14:33:32 COT 2017
     */
    int updateByExample(@Param("record") Negocio record, @Param("example") NegocioCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_negocio
     *
     * @mbg.generated Mon May 08 14:33:32 COT 2017
     */
    int updateByPrimaryKeySelective(Negocio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_negocio
     *
     * @mbg.generated Mon May 08 14:33:32 COT 2017
     */
    int updateByPrimaryKey(Negocio record);
    
    /**Metodos Adicionales**/
    List<Map<String, Object>> selectByNegocio( Map<String, Object>  parametros);
	int countNegocios(Map<String, Object>  parametros);
}