package pe.com.pdp.dao.postgres;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import pe.com.pdp.domain.postgres.Notificacion;
import pe.com.pdp.domain.postgres.NotificacionCriteria;

public interface NotificacionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_notificacion
     *
     * @mbg.generated Wed May 10 13:35:30 COT 2017
     */
    long countByExample(NotificacionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_notificacion
     *
     * @mbg.generated Wed May 10 13:35:30 COT 2017
     */
    int deleteByExample(NotificacionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_notificacion
     *
     * @mbg.generated Wed May 10 13:35:30 COT 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_notificacion
     *
     * @mbg.generated Wed May 10 13:35:30 COT 2017
     */
    int insert(Notificacion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_notificacion
     *
     * @mbg.generated Wed May 10 13:35:30 COT 2017
     */
    int insertSelective(Notificacion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_notificacion
     *
     * @mbg.generated Wed May 10 13:35:30 COT 2017
     */
    List<Notificacion> selectByExample(NotificacionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_notificacion
     *
     * @mbg.generated Wed May 10 13:35:30 COT 2017
     */
    Notificacion selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_notificacion
     *
     * @mbg.generated Wed May 10 13:35:30 COT 2017
     */
    int updateByExampleSelective(@Param("record") Notificacion record, @Param("example") NotificacionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_notificacion
     *
     * @mbg.generated Wed May 10 13:35:30 COT 2017
     */
    int updateByExample(@Param("record") Notificacion record, @Param("example") NotificacionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_notificacion
     *
     * @mbg.generated Wed May 10 13:35:30 COT 2017
     */
    int updateByPrimaryKeySelective(Notificacion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_notificacion
     *
     * @mbg.generated Wed May 10 13:35:30 COT 2017
     */
    int updateByPrimaryKey(Notificacion record);
    
    /**Metodos Adicionales**/
    List<Map<String, Object>> selectByNotificacion( Map<String, Object>  parametros);
	int countNotificaciones(Map<String, Object>  parametros);
}