package pe.com.pdp.dao.postgres;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pe.com.pdp.domain.postgres.PersonaMascota;
import pe.com.pdp.domain.postgres.PersonaMascotaCriteria;

public interface PersonaMascotaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.td_persona_mascota
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    long countByExample(PersonaMascotaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.td_persona_mascota
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    int deleteByExample(PersonaMascotaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.td_persona_mascota
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.td_persona_mascota
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    int insert(PersonaMascota record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.td_persona_mascota
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    int insertSelective(PersonaMascota record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.td_persona_mascota
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    List<PersonaMascota> selectByExample(PersonaMascotaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.td_persona_mascota
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    PersonaMascota selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.td_persona_mascota
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    int updateByExampleSelective(@Param("record") PersonaMascota record, @Param("example") PersonaMascotaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.td_persona_mascota
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    int updateByExample(@Param("record") PersonaMascota record, @Param("example") PersonaMascotaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.td_persona_mascota
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    int updateByPrimaryKeySelective(PersonaMascota record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.td_persona_mascota
     *
     * @mbg.generated Thu Mar 16 14:09:49 COT 2017
     */
    int updateByPrimaryKey(PersonaMascota record);
}