package pe.com.pdp.dao.postgres;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import pe.com.pdp.domain.postgres.Persona;
import pe.com.pdp.domain.postgres.PersonaCriteria;

public interface PersonaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_persona
     *
     * @mbg.generated Thu Apr 06 02:12:57 COT 2017
     */
    long countByExample(PersonaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_persona
     *
     * @mbg.generated Thu Apr 06 02:12:57 COT 2017
     */
    int deleteByExample(PersonaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_persona
     *
     * @mbg.generated Thu Apr 06 02:12:57 COT 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_persona
     *
     * @mbg.generated Thu Apr 06 02:12:57 COT 2017
     */
    int insert(Persona record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_persona
     *
     * @mbg.generated Thu Apr 06 02:12:57 COT 2017
     */
    int insertSelective(Persona record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_persona
     *
     * @mbg.generated Thu Apr 06 02:12:57 COT 2017
     */
    List<Persona> selectByExample(PersonaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_persona
     *
     * @mbg.generated Thu Apr 06 02:12:57 COT 2017
     */
    Persona selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_persona
     *
     * @mbg.generated Thu Apr 06 02:12:57 COT 2017
     */
    int updateByExampleSelective(@Param("record") Persona record, @Param("example") PersonaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_persona
     *
     * @mbg.generated Thu Apr 06 02:12:57 COT 2017
     */
    int updateByExample(@Param("record") Persona record, @Param("example") PersonaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_persona
     *
     * @mbg.generated Thu Apr 06 02:12:57 COT 2017
     */
    int updateByPrimaryKeySelective(Persona record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.tm_persona
     *
     * @mbg.generated Thu Apr 06 02:12:57 COT 2017
     */
    int updateByPrimaryKey(Persona record);
    
    /**Adicional**/
   	List<Map<String, Object>> selectByPersona( Map<String, Object>  parametros);
  	int selectCountByPersona(Map<String, Object>  parametros);
}