package pe.com.pdp.dao.postgres;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import pe.com.pdp.domain.postgres.RolOpcion;
import pe.com.pdp.domain.postgres.RolOpcionCriteria;

public interface RolOpcionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.td_rol_opcion
     *
     * @mbg.generated Wed Apr 26 22:49:11 COT 2017
     */
    long countByExample(RolOpcionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.td_rol_opcion
     *
     * @mbg.generated Wed Apr 26 22:49:11 COT 2017
     */
    int deleteByExample(RolOpcionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.td_rol_opcion
     *
     * @mbg.generated Wed Apr 26 22:49:11 COT 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.td_rol_opcion
     *
     * @mbg.generated Wed Apr 26 22:49:11 COT 2017
     */
    int insert(RolOpcion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.td_rol_opcion
     *
     * @mbg.generated Wed Apr 26 22:49:11 COT 2017
     */
    int insertSelective(RolOpcion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.td_rol_opcion
     *
     * @mbg.generated Wed Apr 26 22:49:11 COT 2017
     */
    List<RolOpcion> selectByExample(RolOpcionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.td_rol_opcion
     *
     * @mbg.generated Wed Apr 26 22:49:11 COT 2017
     */
    RolOpcion selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.td_rol_opcion
     *
     * @mbg.generated Wed Apr 26 22:49:11 COT 2017
     */
    int updateByExampleSelective(@Param("record") RolOpcion record, @Param("example") RolOpcionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.td_rol_opcion
     *
     * @mbg.generated Wed Apr 26 22:49:11 COT 2017
     */
    int updateByExample(@Param("record") RolOpcion record, @Param("example") RolOpcionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.td_rol_opcion
     *
     * @mbg.generated Wed Apr 26 22:49:11 COT 2017
     */
    int updateByPrimaryKeySelective(RolOpcion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pataPerro.td_rol_opcion
     *
     * @mbg.generated Wed Apr 26 22:49:12 COT 2017
     */
    int updateByPrimaryKey(RolOpcion record);
    
	List<Map<String, Object>> selectMenu(Map<String, Object> params);
	
	/**
	 * Este metodo obtiene la lista de opciones por rol para el mantenimiento de opciones por rol
	 */
	List<Map<String, Object>> selectTreeRolOpcion(Map<String, Object> params);
}